### ISSUE TITLE
[suggestion] Random things Mod support

### ISSUE THREAD

**Issue by reddler97** [jaredlll08/ModTweaker#282]
i didn't see a suggestion for this mod, so i though i'd make one. This mod has 1 maybe two crafting mechanics, 1 being the "Imbuing Station", and the other might be the "Dyeing Machine"

I am new here so please tell me if this mod is "Too Small", or something similar

CurseForge, and Minecraft Forums:
http://minecraft.curseforge.com/projects/random-things
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1289551-random-things-3-5

Source Code via github:
https://github.com/lumien231/Random-Things

**Comment by Voidi** [comment]
https://github.com/jaredlll08/ModTweaker2/wiki/Requesting-Mod-Support

**Comment by Yulife** [comment]
Random things is 1.10 :)

**Comment by jaredlll08** [comment]
Just btw, no mod is too small, if it is relevant and adds stuff that needs to be tweaked, it is ok :)

**Comment by jaredlll08** [comment]
The dying machine isn't possible, but I implemented the imbuing station
