### ISSUE TITLE
TiCon Smeltery doesn't recognize wildcard registrations.

### ISSUE THREAD

**Issue by AnrDaemon** [jaredlll08/ModTweaker#329]
I don't know, if this is an issue with TiCon or ModTweaker, but a recipe, such as 

```
mods.tconstruct.Smeltery.addMelting(<ore:sandstone>, <liquid:glass.molten> * 384, 800, <minecraft:sandstone>);
```

will not make any sandstone melt.

**Comment by Yulife** [comment]
Once TiC support is fixed I'll look if it works

**Comment by majix560** [comment]
TiC support is supposedly fixed now...just waiting for the fix to be released.

**Comment by Kiyaku** [comment]
I'll try to compile it and check it out, see if it works now. 
Is there a planned release coming sometime soon?

**Comment by jaredlll08** [comment]
I vaguely remember fixing this. If not, just open it back up
