### ISSUE TITLE
[1.7.10] /minetweaker tconstruct [HANDLER] - "Invalid argument for command"

### ISSUE THREAD

**Issue by AnrDaemon** [jaredlll08/ModTweaker#330]
Whatever argument I give to `/minetweaker tconstruct ...`, it always spit "Invalid argument for command".
Just `/minetweaker tconstruct` without arguments works, though. If arguments were removed, [the wiki](http://minetweaker3.powerofbytes.com/wiki/ModTweaker:TConstruct_Support) needs changes.

**Comment by Yulife** [comment]
Commands dont work 1.10.2 at all? @jaredlll08

**Comment by AnrDaemon** [comment]
There MineTweaker for 1.10? O.o >.<

**Comment by jaredlll08** [comment]
No, but there was is crafttweaker for 1.10 😜

**Comment by AnrDaemon** [comment]
Well, then…

**Comment by majix560** [comment]
Minetweaker isn't registering tconstruct at all for me.
Says it's not a valid member.

[Console Log - http://pastebin.com/KE6tQMwX](http://pastebin.com/KE6tQMwX)
Here are the various allow scripts I've tried.
[http://pastebin.com/JP9H1vy4](http://pastebin.com/JP9H1vy4)

**Comment by jaredlll08** [comment]
Minetweaker.log file?

**Comment by majix560** [comment]
[minetweaker.log](http://pastebin.com/RyzwxCQu)

**Comment by jaredlll08** [comment]
oh yea, It's a known issue, it will get fixed, just a bit burnt out lately

**Comment by jaredlll08** [comment]
ok so, the original issue, is a 1.7.10 issue, meaning it won't get fixed, @majix560's issue is already fixed, I'm closing this

**Comment by majix560** [comment]
@jaredlll08 when will the fix be released?
It's ModTweaker 2 v2.0.0 for 1.10.2 that I've only ever used and it's the latest/only version for 1.10.2,
and the one that minetweaker log.
So when will the fix be released?

**Comment by majix560** [comment]
@jaredlll08 do you have an eta. when the fix will be released or not?

**Comment by AnrDaemon** [comment]
Can you not pester him every hour? Have some patience.

**Comment by jaredlll08** [comment]
Nah, leave him, for every eta he asks for (which has been about 3 now), I'm
just adding an extra 2 days each, so 6 extra days of waiting :)

**Comment by bookerthegeek** [comment]
@jaredlllo8 lmao

@majix560 ... stfu
