### ISSUE TITLE
[Suggestion] [1.10] Blood Magic support

### ISSUE THREAD

**Issue by Fortanono** [jaredlll08/ModTweaker#333]
It should all be easy enough, but I want most of it there for a pack I'm making. Alchemy Table, Arcane Ash, Hellfire Forge and of course the Blood Altar itself.

**Comment by jaredlll08** [comment]
This is more of a @WayOfTime issue.

P.S. I'm happy to take the support over.

**Comment by pobiega** [comment]
I'm working on this in my fork and will submit a PR soon. Got the Hellfire Forge working fully so far.

**Comment by squirrelkiller** [comment]
Please @ me on this one once said PR gets pulled into the mod. This would be of major benefit to me with [Safety Lost](https://minecraft.curseforge.com/projects/safety-lost) and likely other future modpack developers.

**Comment by pobiega** [comment]
@squirrelkiller This was merged a few days ago and 2.0.5 has it.

**Comment by squirrelkiller** [comment]
Thank you.

**Comment by Yulife** [comment]
I'll write some documentation for the new Blood Magic soon, then it'll be on the wiki :)
