### ISSUE TITLE
trouble with thaumcraft wand recipe

### ISSUE THREAD

**Issue by wizard1399** [jaredlll08/ModTweaker#335]
hello,
I keep getting a error excuting null  whenever I try to reload the following: 

print("Initializing Thaumcraft ...");

# - Wands
recipes.addShaped.mirrored(<Thaumcraft:WandCasting>.withTag({cap: "iron", rod: "living wood"}),
  [ [<Thaumcraft:WandCap>, null, null],
    [null, <Botania:manaResource:3>, null],
    [null, null, <Thaumcraft:WandCap>]
  ]);

print("Finished Thaumcraft start up");

Is this an issue with my coding or a recipe that is not tweakable?

**Comment by Voidi** [comment]
First, this repo is about ModTweaker which provides Minetweaker Support for various Craftmechanismen from Mods. Everything else is a Minetweaker issue.
Second, read https://github.com/MineTweaker/Modtweaker/wiki/Bug-Reporting-Guidelines

**Comment by Yulife** [comment]
Can you post it in the Minetweaker repo please? :)

**Comment by wizard1399** [comment]
Sorry, the Thaumcraft wiki for mod tweaker mentioned that some recipes are not tweakable and if we had questions we should post here. Thus I have done so. I will post this over on the minetweaker issue tracker to see what they have to say.

**Comment by Voidi** [comment]
the function is `recipes.addShapedMirrored` not `recipes.addShaped.mirrored`

**Comment by wizard1399** [comment]
Thanks! That fixed it. Sometimes I look at code for so long that I fail to see the obvious.
