### ISSUE TITLE
[1.10.2] Requesting Mod Support for Roots

### ISSUE THREAD

**Issue by SnowShock35** [jaredlll08/ModTweaker#336]
Hello,

I'd like to make a request to have Roots support added to ModTweaker.

Roots is an up and coming mod in the 1.10.2 era of modded Minecraft and is very interesting and unique in its ideas and development. The mod features several crafting handlers that I'd feel would make for a great addition to ModTweaker for 1.10.2 and beyond if the mod continues to be around which from the initial response of the mod is likely. 

A link to the Roots CurseForge thread can be found [here](http://minecraft.curseforge.com/projects/roots).

Thanks for reading.

**Comment by jaredlll08** [comment]
This will be done in Roots.
