### ISSUE TITLE
addTableRecipe Casting Failure in MC1.7.10

### ISSUE THREAD

**Issue by LakMoore** [jaredlll08/ModTweaker#337]
MC 1.7.10
With latest Tinkers, ExtraTiC, NEI, MineTweaker and ModTweaker

The following script adds the recipe to NEI but the smeltery will not actually pour the fluid onto the cast.

`mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:toolrod:173>, <liquid:red.aurum.molten> * 72, <TConstruct:metalPattern:1>, false, 80);`

It works for the ingot cast but fails for all other casts.  Any ideas what is wrong?

Cheers

Lak

**Comment by jaredlll08** [comment]
what cast is `<TConstruct:metalPattern:1>` ?
also 1.7.10 is no longer supported.

**Comment by LakMoore** [comment]
Meta ID=1 is the tool rod cast, but I have scripted all the casts and the only one that works is the ingot cast which is the same string with Meta ID = 0 (or omitted, it works either way)

Sorry for trying to use old code but there are lots of great mods out there that have not updated beyond 1.7.10. :-/

**Comment by jaredlll08** [comment]
maybe try downgrading tinkers?

**Comment by jaredlll08** [comment]
@LakMoore any updates after downgrading tinkers?

**Comment by LakMoore** [comment]
Hey, sorry I didn't try that.  It would have been a good test that I might look into in the future.  If you would prefer to close this ticket for now, that makes total sense.  Cheers.

**Comment by jaredlll08** [comment]
Yea, I'm going to close it for now, but feel free to reopen
