### ISSUE TITLE
/mt chiselGroups - No such minetweaker command

### ISSUE THREAD

**Issue by LaVidaYokel** [jaredlll08/ModTweaker#339]
Forge 12.18.1.2027
Chisel 1.9.4-0.0.6.33
Crafttweaker 1.10.2-3.0.10
Modtweaker2 2.0.0

likewise for /mt chiselVariations

**Comment by jaredlll08** [comment]
Chisel is currently not supported

**Comment by LaVidaYokel** [comment]
Well that would explain that :)

**Comment by aikpoppel** [comment]
Not fixed in ModTweaker 2.0.3.

Forge: 12.18.1.2088
Chisel: 0.0.6.46
CraftTweaker: 3.0.11
ModTweaker 2.0.3
