### ISSUE TITLE
[1.10.2] Would it be possible to add harvestcraft machine support?

### ISSUE THREAD

**Issue by Sunconure11** [jaredlll08/ModTweaker#344]
Since this won't happen on 1.7.10, would it be possible to add support for Harvestcraft's machines on 1.10.2? If this is not possible, what is stopping you?

**Comment by MakerTim** [comment]
https://github.com/MatrexsVigil/harvestcraft/blob/22d1c1738d1fd8ac3e43f7144c552a456832dc76/java/com/pam/harvestcraft/item/PresserRecipes.java

Pressers and other stuff of pam is officially private and no api

it is still posible; but not intended by pam

what i would do is first off -> request at pam that that kind of stuff is made public
and then come back to ask for support
(on the other side, reflection could do it still...)

**Comment by jaredlll08** [comment]
@matrexsVigil this ok with you?

**Comment by jaredlll08** [comment]
1.7 is no longer supported. 1.7.10 is 2 years / 4 versions old now, it is time to move on. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately

**Comment by MakerTim** [comment]
@jaredlll08 this is not a 1.7 request ;)

**Comment by jaredlll08** [comment]
welp, the bot is a bit buggy

**Comment by jaredlll08** [comment]
All of their stuff is private, and @matrexsVigil never got back to me if it was ok for me to hack into it. So I'm closing this.
