### ISSUE TITLE
[1.10.2] Forestry Carpenter can only use specific liquids when adding recipes

### ISSUE THREAD

**Issue by Gredh** [jaredlll08/ModTweaker#348]
Forestry (5.2.9.241)
CraftTweaker (3.0.10)
ModTweaker2 (2.0.1)
Jei (3.9.0.246)

Creating a recipe using Carpenter.addRecipe that uses an input fluid that is not normally used by the Carpenter loads flawlessly (and appears in JEI). However you are not able to craft it as the carpenter block refuses to accept the newly defined liquid even if you try to pipe the liquid in or use tin cans.

An example is by creating a recipe that takes cobblestone as an input and outputs obsidian using lava as the input fluid (liquid:lava). Since the carpenter normally only accepts either [Seed Oil, Water, or Honey], the recipe cannot be made as left clicking the can-input slot of the carpenter with lava cans refuses to accept the liquid into its buffer.

![p1](https://cloud.githubusercontent.com/assets/21289385/18032847/75dec204-6d4e-11e6-8b66-e669a98f5489.jpg)

![p2](https://cloud.githubusercontent.com/assets/21289385/18032852/7d9106ce-6d4e-11e6-9328-ed2119be3230.jpg)

**Comment by grundyboy34** [comment]
This issue exists again, I think due to [0e270c6](https://github.com/jaredlll08/ModTweaker/commit/0e270c617df7fc9c87133cb0e0d7ac867cd39792#diff-011cf8f362069ef690e143d00b949b39)

Hoping this can be fixed, but if you don't support 1.10.2 anymore, I get it.
