### ISSUE TITLE
[1.10.2] Import not working

### ISSUE THREAD

**Issue by DoughnutDev** [jaredlll08/ModTweaker#349]
I can not import things like import mods.ic2.Compressor; this without an error saying invalid expression token: import.

**Comment by jaredlll08** [comment]
Well there is no ic2 support, try with support that is added.

**Comment by DoughnutDev** [comment]
Well I want to add a compressor recipe is there another way?

**Comment by jaredlll08** [comment]
Right now, there is no ic2 support. So wait for me to release it.

**Comment by jaredlll08** [comment]
this isn't a modtweaker issue anyway, it is a minetweaker one and it has been fixed.
