### ISSUE TITLE
[1.8.9] Modtweaker not detecting Crafttweaker?

### ISSUE THREAD

**Issue by abculatter2** [jaredlll08/ModTweaker#351]
Sorry if this issue has been fixed and I have the wrong version or something equally stupid, but when I try to boot with CraftTweaker 3.0.10 for 1.8.9, and Modtweaker2 1.0.0 (both the latest versions for 1.8.9, according to Curse) forge pops up with an error saying that it can't find any version of CraftTweaker.

**Comment by jaredlll08** [comment]
Not gna be fixed. 1.8.9 is dead, modtweaker side and mod side)(I'm going by
the downloads crafttweaker gets per version), sorry
