### ISSUE TITLE
[1.10.2] Removing Tinkers Casting Table Recipe doesn't work

### ISSUE THREAD

**Issue by tommyTT** [jaredlll08/ModTweaker#354]
I tried playing around with the integration for Tinkers Construct and wanted to try out a simple example straight from the wiki, so this is my ZenScript (the file is named tinkers.zs and in the main script folder, no other content):
`mods.tconstruct.Casting.removeTableRecipe(<minecraft:iron_ingot>);`
When I start up a test world I get an error in chat:
> ERROR: [ModTweaker] Exception in getStaticObject()
> ERROR: [ModTweaker] Could not retrieve any static object for the provided field names.
> ERROR: Error executing tinkers.zs: null

The Minetweaker Log (see below) shows multiple exceptions and of course the casting recipe is still there.

Versions:
Minecraft: 1.10.2
Forge: 12.18.1.2077

Mods:
  jei_1.10.2-3.9.2.251
  Mantle-1.10.2-0.10.4
  CraftTweaker-1.10.2-3.0.11
  ModTweaker2-2.0.2
  TConstruct-1.10.2-2.4.0

Logs:
Minecraft: http://paste.ee/p/54SMr
Minetweaker: http://paste.ee/p/kJOYC

**Comment by tommyTT** [comment]
So, since you are busy at the moment, I looked into it myself. Unfortunately the github repository is not at version 2.0.2, but while debugging, I found the error. There is an additional space in the following call in the TConstructHelper class, that causes an error:
`tableCasting = (List)ReflectionHelper.getStaticObject(TinkerRegistry.class, new String[]{"tableCastRegistry "});`

**Comment by jaredlll08** [comment]
@tommyTT thanks!
