### ISSUE TITLE
[Suggestion] Mekanism V9 Support [1.10.2]

### ISSUE THREAD

**Issue by Bluedog444** [jaredlll08/ModTweaker#359]
Hey Jared,
I was wondering if Mekanism V9 support was/is being worked on. This may be more in Aidan Brady's department though.

Cheers for the fantastic mod.

Kind Regards Bluedog444 :)

**Comment by jaredlll08** [comment]
It is my department, I'm currently extremely busy with school work and
exams, so no new support will be coming right now, only bug fixes when I
have time, so it will come, just not right now, or soon

**Comment by Bluedog444** [comment]
That's fair enough. Thanks for the quick reply.

**Comment by davqvist** [comment]
I was getting an error removing a recipe from a Mekanism machine following this: http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Mekanism_Support
But now I found this issue, so it seems Mekanism support isn't implemented yet for 1.10.2 as it's still open, is this true? Just letting you know that I'm really interested in it.

**Comment by jaredlll08** [comment]
If support was added. This issue would be closed.

**Comment by davqvist** [comment]
Yeah I figured, sorry for bothering you. Thanks for your awesome work.

**Comment by jaredlll08** [comment]
Mekanism will not receive support anytime soon, from what I can tell, it is not in dev right now, there is a huge amount of issues that aren't being attended to and I don't want to waste my time on a dead mod.

**Comment by Dragnier** [comment]
Not completely dead: [mention of rewrite](https://github.com/aidancbrady/Mekanism/issues/4167)

**Comment by jaredlll08** [comment]
A rewrite not by Aiden? Not getting my support.

**Comment by aidancbrady** [comment]
@jaredlll08, I'm getting back on track on track with development. Your studies take priority, but if you have some free time I'd be happy to help you update your Mekanism support.

**Comment by Slater022** [comment]
@aidancbrady Mother of God you are really my fav mod dev ! You take your time but you take your mod seriously ! :D I was wondering how to tweak Mekanism recipes :D

**Comment by jaredlll08** [comment]
@aidencbrady do you have discord? If so, join my server and we can talk there / move to a pm
https://discord.gg/3VBK9ar

**Comment by RedGuy54** [comment]
Any progress on this?

**Comment by RedGuy54** [comment]
@aidancbrady @jaredlll08 Any progress on this?

**Comment by jaredlll08** [comment]
@RedGuy54 the progress is, mekanism is focusing on 1.11 and Modtweaker is still in 1.10.2, at some point, I will port it, I am unsure when I will do so however

**Comment by RedGuy54** [comment]
Okay, I'm still on 1.10.2 as well so whenever it's possilbe.

**Comment by josephcsible** [comment]
Now that Mekanism is fully back to life, and both it and ModTweaker are on 1.12, can this be reopened?

**Comment by tomelfring** [comment]
I've started working on CraftTweaker support, bundled within Mekanism 1.12 (maybe 1.11 if it's easily backported) ;) Would take some time, but it has been started

**Comment by coleweinman** [comment]
@thommy101 @jaredlll08 Support for 1.12 coming is VERY exciting, and support for 1.11 would also be amazing.

**Comment by jaredlll08** [comment]
@thommy101 feel free to take the code from 1.7.10 and update it :)

**Comment by josephcsible** [comment]
For anyone watching this issue that didn't see already, @thommy101 created aidancbrady/Mekanism#4641 to add this.
