### ISSUE TITLE
[Suggestions]

### ISSUE THREAD

**Issue by mightydanp** [jaredlll08/ModTweaker#364]
I want to suggest a few things that i would like you to add.
- Add changeable Mining levels for blocks.
- Ability to disable a function of a tool. example: Making a pickaxe unable to mine a block.
- Change harvest levels of tools. This should be a alternative fix if you cannot disable a tools functionality. But still be good to have.
- Ability to disable a modifier from a tool material. example: stone not having stone bound.

**Comment by jaredlll08** [comment]
Looked into, not possible

**Comment by mightydanp** [comment]
this is possible i have changed block mining level  and tool mining level in my mod i am working on.

**Comment by jaredlll08** [comment]
You sure? I have tried this before, and what I saw was that vanilla hardcoded some of their stuff, making it impossible to do it in a minetweaker environment

**Comment by mightydanp** [comment]
in forge there is a veriable where you can change the mining level of a block or a tool. Ive been using it in my mod. its the same way you would set the mining level of your tool or a block but with the block you want to change in the first peramitor

**Comment by jaredlll08** [comment]
So you are telling me that this whole method from ItemPickaxe can be made useless with a variable?
http://www.blamejared.com/content/FzWOw.txt

**Comment by mightydanp** [comment]
i used this to changed mining levels of blocks which worked
	public static void registerBlockMiningLevel() {
		setBlockMiningLevel(Blocks.IRON_ORE, "pickaxe", 2);
		setBlockMiningLevel(Blocks.GOLD_ORE, "pickaxe", 2);
		setBlockMiningLevel(Blocks.EMERALD_ORE, "pickaxe", 3);
		setBlockMiningLevel(Blocks.OBSIDIAN, "pickaxe", 3);
		setBlockMiningLevel(Blocks.DIAMOND_ORE, "pickaxe", 4);
	}

and i used this to change mining level of pickaxes.

	public static void registerBlockMiningLevel() {
		setItemMiningLevel(Items.STONE_PICKAXE, "pickaxe", 1);
		setItemMiningLevel(Items.GOLDEN_PICKAXE, "pickaxe", 1);
		setItemMiningLevel(pickaxeBronze, "pickaxe", 2);
		setItemMiningLevel(Items.IRON_PICKAXE, "pickaxe", 2);
		setItemMiningLevel(Items.DIAMOND_PICKAXE, "pickaxe", 4);
		setItemMiningLevel(pickaxeSteel, "pickaxe", 3);
	}

**Comment by jaredlll08** [comment]
And where is that method?

**Comment by mightydanp** [comment]
public static void setBlockMiningLevel(Block block,String toolUsed, int miningLevel) {
		block.setHarvestLevel(toolUsed ,miningLevel);
	}

	public static void setItemMiningLevel(Item item,String toolUsed, int miningLevel) {
		item.setHarvestLevel(toolUsed ,miningLevel);
	}
}
