### ISSUE TITLE
Tinkers setHarvestLevel

### ISSUE THREAD

**Issue by mightydanp** [jaredlll08/ModTweaker#366]
Tinkers setHarvestLevel has
[12:23:05] [Client thread/INFO]: [CHAT] ERROR: ?:1 > No such member: setHarvestLevel
[12:23:05] [Client thread/INFO]: [CHAT] ERROR: Error executing TinkersConstruct.zs: 1

mods.tconstruct.setHarvestLevel("Wood", 1);

**Comment by jaredlll08** [comment]
Use 
```
<material:wood>. Harvest level = 5;
```

**Comment by mightydanp** [comment]
Are there sepost to be spaces ?

**Comment by mightydanp** [comment]
Or any imports ?

**Comment by jaredlll08** [comment]
No spaces, no imports

**Comment by mightydanp** [comment]
Thank you for the help

**Comment by mightydanp** [comment]
Having a bit of trouble

INFO: [ModTweaker] Removing 1 Botania Mana Infusion Recipe(s) for <botania:manaResource>
INFO: [ModTweaker] Adding 1 Botania Mana Infusion Recipe(s) for <botania:manaResource>
INFO: [ModTweaker] Removing 1 Botania Mana Infusion Recipe(s) for <botania:storage>
INFO: [ModTweaker] Adding 1 Botania Mana Infusion Recipe(s) for <botania:storage>
INFO: Adding Livingwood to ore dictionary entry logWood
INFO: Adding Livingwood Planks to ore dictionary entry plankWood
INFO: Adding Livingwood Slab to ore dictionary entry slabWood
INFO: Adding Livingwood Plank Slab to ore dictionary entry slabWood
INFO: Adding Dreamwood to ore dictionary entry logWood
INFO: Adding Dreamwood Planks to ore dictionary entry plankWood
INFO: Adding Dreamwood Slab to ore dictionary entry slabWood
INFO: Adding Dreamwood Plank Slab to ore dictionary entry slabWood
INFO: Adding Shimmerwood Planks to ore dictionary entry plankWood
INFO: Adding Shimmerwood Plank Slab to ore dictionary entry slabWood
INFO: Removing 1 recipes
INFO: Adding recipe for Livingwood Slab
INFO: Removing 1 recipes
INFO: Adding recipe for Flügel Tiara
INFO: Removing 1 recipes
INFO: Adding recipe for Low Voltage Solar Array
ERROR: ?:2 > No such member: gregtech
ERROR: ?:2 > Not a valid type
INFO: Removing 4 furnace recipes
INFO: Removing Silicon from ore dictionary entry itemSilicon
INFO: Removing 1 recipes
INFO: Adding recipe for Insulated Redstone Conduit
INFO: Removing 0 recipes
INFO: Adding recipe for Insulated Redstone Conduit
INFO: Removing 1 recipes
INFO: Adding recipe for Network Conduit (OC)
INFO: Removing 1 recipes
INFO: Adding recipe for Basic Gear
INFO: Removing 1 recipes
INFO: Adding recipe for Machine Chassis
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 2 recipes
INFO: Removing 2 recipes
INFO: Removing 1 recipes
INFO: Removing 2 recipes
INFO: Removing 2 recipes
INFO: Removing 1 recipes
INFO: Removing 0 recipes
INFO: Adding recipe for Red Alloy Ingot
INFO: Adding furnace recipe for <extrautils2:DecorativeSolid:2>
INFO: Removing 8 recipes
INFO: Removing 4 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 12 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 0 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 5 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Adding recipe for Iron Drum
INFO: Removing 1 recipes
INFO: Adding recipe for Reinforced Large Drum
INFO: Removing 1 recipes
INFO: Adding recipe for Drum_65536
INFO: Removing 1 recipes
INFO: Adding recipe for Magical Planks
INFO: Removing 1 recipes
INFO: Adding recipe for Magical Wood
INFO: Adding recipe for Magical Wood
INFO: Removing 2 recipes
INFO: Adding recipe for Magical Wood
INFO: Adding recipe for Magical Wood
INFO: Removing 2 recipes
INFO: Adding recipe for Magical Wood
INFO: Adding recipe for Magical Wood
INFO: Removing 2 recipes
INFO: Adding recipe for Magical Wood
INFO: Adding recipe for Magical Wood
INFO: Removing 2 recipes
INFO: Adding recipe for Magical Wood
INFO: Adding recipe for Magical Wood
INFO: Removing 1 recipes
INFO: Adding recipe for Golden Lasso
INFO: Removing 3 furnace recipes
INFO: Removing 2 recipes
INFO: Turbine Housing Core
INFO: Removing 1 recipes
INFO: Adding recipe for Turbine Housing Core (Legacy)
INFO: Turbine Housing
INFO: Removing 1 recipes
INFO: Adding recipe for Turbine Housing (Legacy)
INFO: Turbine Glass
INFO: Removing 1 recipes
INFO: Adding recipe for Turbine Glass (Legacy)
INFO: Reactor Housing Core
INFO: Removing 1 recipes
INFO: Adding recipe for Reactor Casing Core (Legacy)
INFO: Reactor Housing
INFO: Removing 1 recipes
INFO: Adding recipe for Reactor Casing (Legacy)
INFO: Reactor Glass
INFO: Removing 1 recipes
INFO: Adding recipe for Reactor Glass (Legacy)
INFO: Fuel Rod
INFO: Removing 1 recipes
INFO: Adding recipe for Reactor Fuel Rod (Legacy)
INFO: Turbine Rotor Shaft
INFO: Removing 1 recipes
INFO: Adding recipe for Turbine Rotor Shaft (Legacy)
INFO: Turbine Rotor Blade
INFO: Removing 1 recipes
INFO: Adding recipe for Turbine Rotor Blade (Legacy)
INFO: Extreme Wrench
INFO: Removing 1 recipes
INFO: Adding recipe for Extreme Wrench
INFO: Removing 1 recipes
INFO: Adding recipe for Bronze Gear
INFO: Removing 1 recipes
INFO: Adding recipe for Copper Gear
INFO: Removing 1 recipes
INFO: Adding recipe for Tin Gear
INFO: Removing 1 recipes
INFO: Adding recipe for Sturdy Casing
INFO: Adding recipe for Red Colored Honey Drop
INFO: Adding recipe for invalid.name
INFO: Removing 1 recipes
INFO: Adding recipe for Upgrade Frame
INFO: Removing 1 recipes
INFO: Adding recipe for Power Module
INFO: Removing 1 recipes
INFO: Adding recipe for Mutagen Tank
INFO: Removing 1 recipes
INFO: Adding recipe for Bee Receptacle
INFO: Removing 1 recipes
INFO: Adding recipe for Mutagen Producer
INFO: Removing 1 recipes
INFO: Adding recipe for Industrial Apiary
INFO: Removing 1 recipes
INFO: Adding recipe for Genetic Imprinter
INFO: Removing 1 recipes
INFO: Adding recipe for Protein Liquifier
INFO: Removing 1 recipes
INFO: Adding recipe for DNA Extractor
INFO: Removing 1 recipes
INFO: Adding recipe for Genetic Transposer
INFO: Removing 1 recipes
INFO: Adding recipe for Genetic Replicator
INFO: Removing 1 recipes
INFO: Adding recipe for Mutatron
INFO: Removing 1 recipes
INFO: Adding recipe for Canister
INFO: Removing 1 recipes
INFO: Adding recipe for Tank Wall
INFO: Removing 1 recipes
INFO: Adding recipe for Fluid Interface
INFO: Removing 1 recipes
INFO: Adding recipe for Tank Block
INFO: Removing 2 recipes
INFO: Adding recipe for Powered Tank Fluid Outlet
INFO: Removing 2 recipes
INFO: Adding recipe for Tank Fluid Intake
INFO: Removing 2 recipes
INFO: Adding recipe for Tank Fluid Outlet
INFO: Removing 2 recipes
INFO: Adding recipe for Tank Pressure Intake
INFO: Removing 2 recipes
INFO: Adding recipe for Tank Pressure Outlet
INFO: Removing 1 recipes
INFO: Adding recipe for Tank Interface
INFO: Removing 1 recipes
INFO: Adding recipe for High Pressure Pipe
INFO: Removing 1 recipes
INFO: Adding recipe for High Pressure Pump
INFO: Removing 1 recipes
INFO: Adding recipe for High Pressure Output
INFO: Removing 1 recipes
INFO: Adding recipe for High Pressure Input
INFO: Removing 1 recipes
INFO: Adding recipe for Fluid Drain
INFO: Removing 1 recipes
INFO: Adding recipe for Tank Fluid Filter
INFO: Removing 1 recipes
INFO: Adding recipe for Infinite Water Source
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material was null
ERROR: TinkersConstruct.zs:6: Could not resolve <material : end>
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material was null
ERROR: TinkersConstruct.zs:15: Could not resolve <material : slimevine>
INFO: Material was null
ERROR: TinkersConstruct.zs:16: Could not resolve <material : vines>
INFO: Material was null
ERROR: TinkersConstruct.zs:17: Could not resolve <material : blazerod>
INFO: Material was null
ERROR: TinkersConstruct.zs:18: Could not resolve <material : reeds>
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material was null
ERROR: TinkersConstruct.zs:22: Could not resolve <material : slimeLeaf>
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material was null
ERROR: TinkersConstruct.zs:27: Could not resolve <material : pigIron>
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
INFO: Material wasn't null
ERROR: ?:1 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: ?:1 > not a valid lvalue
ERROR: TinkersConstruct.zs:2 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:2 > not a valid lvalue
ERROR: TinkersConstruct.zs:3 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:3 > not a valid lvalue
ERROR: TinkersConstruct.zs:4 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:4 > not a valid lvalue
ERROR: TinkersConstruct.zs:5 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:5 > not a valid lvalue
ERROR: TinkersConstruct.zs:6 > not a valid lvalue
ERROR: TinkersConstruct.zs:7 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:7 > not a valid lvalue
ERROR: TinkersConstruct.zs:8 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:8 > not a valid lvalue
ERROR: TinkersConstruct.zs:9 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:9 > not a valid lvalue
ERROR: TinkersConstruct.zs:10 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:10 > not a valid lvalue
ERROR: TinkersConstruct.zs:11 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:11 > not a valid lvalue
ERROR: TinkersConstruct.zs:12 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:12 > not a valid lvalue
ERROR: TinkersConstruct.zs:13 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:13 > not a valid lvalue
ERROR: TinkersConstruct.zs:14 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:14 > not a valid lvalue
ERROR: TinkersConstruct.zs:15 > not a valid lvalue
ERROR: TinkersConstruct.zs:16 > not a valid lvalue
ERROR: TinkersConstruct.zs:17 > not a valid lvalue
ERROR: TinkersConstruct.zs:18 > not a valid lvalue
ERROR: TinkersConstruct.zs:19 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:19 > not a valid lvalue
ERROR: TinkersConstruct.zs:20 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:20 > not a valid lvalue
ERROR: TinkersConstruct.zs:21 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:21 > not a valid lvalue
ERROR: TinkersConstruct.zs:22 > not a valid lvalue
ERROR: TinkersConstruct.zs:23 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:23 > not a valid lvalue
ERROR: TinkersConstruct.zs:24 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:24 > not a valid lvalue
ERROR: TinkersConstruct.zs:25 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:25 > not a valid lvalue
ERROR: TinkersConstruct.zs:26 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:26 > not a valid lvalue
ERROR: TinkersConstruct.zs:27 > not a valid lvalue
ERROR: TinkersConstruct.zs:28 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:28 > not a valid lvalue
ERROR: TinkersConstruct.zs:29 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:29 > not a valid lvalue
ERROR: TinkersConstruct.zs:30 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:30 > not a valid lvalue
ERROR: TinkersConstruct.zs:31 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:31 > not a valid lvalue
ERROR: TinkersConstruct.zs:32 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:32 > not a valid lvalue
ERROR: TinkersConstruct.zs:33 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:33 > not a valid lvalue
ERROR: TinkersConstruct.zs:34 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:34 > not a valid lvalue
ERROR: TinkersConstruct.zs:35 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:35 > not a valid lvalue
ERROR: TinkersConstruct.zs:36 > No such member in modtweaker.materials.IMaterial: harvestLevel
ERROR: TinkersConstruct.zs:36 > not a valid lvalue
WARNING: 8 modifications were stuck

<material:stone>.harvestLevel=0;
<material:flint>.harvestLevel=0;
<material:cactus>.harvestLevel=0;
<material:bone>.harvestLevel=0;
<material:prismarine>.harvestLevel=0;
<material:end>.harvestLevel=0;
<material:paper>.harvestLevel=0;
<material:sponge>.harvestLevel=0;
<material:firewood>.harvestLevel=0;
<material:slime>.harvestLevel=0;
<material:blueslime>.harvestLevel=0;
<material:magmaslime>.harvestLevel=0;
<material:netherrack>.harvestLevel=0;
<material:string>.harvestLevel=0;
<material:slimevine>.harvestLevel=0;
<material:vines>.harvestLevel=0;
<material:blazerod>.harvestLevel=0;
<material:reeds>.harvestLevel=0;
<material:ice>.harvestLevel=0;
<material:endrod>.harvestLevel=0;
<material:feather>.harvestLevel=0;
<material:slimeLeaf>.harvestLevel=0;
<material:leaf>.harvestLevel=0;
<material:copper>.harvestLevel=1;
<material:bronze>.harvestLevel=2;
<material:iron>.harvestLevel=2;
<material:pigIron>.harvestLevel=2;
<material:lead>.harvestLevel=2;
<material:silver>.harvestLevel=2;
<material:electrum>.harvestLevel=2;
<material:steel>.harvestLevel=3;
<material:obsidian>.harvestLevel=3;
<material:knightslime>.harvestLevel=4;
<material:ardite>.harvestLevel=5;
<material:cobalt>.harvestLevel=6;
<material:manyullyn>.harvestLevel=7;

**Comment by mightydanp** [comment]
Update: 
i got it to work for a small bit of it butt some of them dont work

http://pastebin.com/Wf1nD4Wn

http://pastebin.com/5msvGPgm

**Comment by oxoroxyoxo** [comment]
this sounds like a very big problem here. joda might bite ur head off if u dont fix it soon.

**Comment by jaredlll08** [comment]
use
```
/mt materials
```
to print out valid materials, since you seem to have some invalid ones, and trying to set harvestLevels for materials that can't actually be used to mine.

**Comment by mightydanp** [comment]
this is what i get for my materials http://pastebin.com/TBf1ueHV
when i put them all together and take out the non picaxe materials http://pastebin.com/qpUzD00g
i get these errors in minetweaker http://pastebin.com/RM9Nzqnk

**Comment by jaredlll08** [comment]
ok, don't use any capitals, but use those names

**Comment by mightydanp** [comment]
im having a problem with end it dont work even if i capitallize it or lower case it

**Comment by Alan19** [comment]
Try replacing harvestlevel with harvestLevelHead
