### ISSUE TITLE
Asterisk Bug

### ISSUE THREAD

**Issue by WenXin20** [jaredlll08/ModTweaker#368]
Forge 2092
ModTweaker 2.0.3
CraftTweaker 3.0.11

Using the asterisk to define all variants of a block, at least with the chisel mod, doesn't work. It only seems to work with the first block. I tried it with hardened clay from the example wiki, but only the white stained clay showed up instead of all the colors.

**Comment by jaredlll08** [comment]
I believe this is a chisel bug, as we simply pass the blocks on
