### ISSUE TITLE
[Suggestion] Crossroads support

### ISSUE THREAD

**Issue by Da-Technomancer** [jaredlll08/ModTweaker#369]
I was wondering if you could add support for my mod Crossroads (source here: https://github.com/Da-Technomancer/Crossroads)? All of the machine recipes are stored in public variables in this class: https://github.com/Da-Technomancer/Crossroads/blob/master/src/main/java/com/Da_Technomancer/crossroads/items/crafting/RecipeHolder.java

If there is anything I need to do in order to make adding support easier, just let me know. I understand that you might not have enough time to add support for a relatively minor mod like mine, but I would appreciate it.

**Comment by Da-Technomancer** [comment]
Never mind, it seems that in the day since I posted this someone else wrote integration.

**Comment by Magi1053** [comment]
Link or documentation to this integration?
