### ISSUE TITLE
Method for adding TCon melting recipes?

### ISSUE THREAD

**Issue by WolfieWaffle** [jaredlll08/ModTweaker#374]
The melting recipe on the ModTweaker wiki does not seem to work, saying a method exists but not with these parameters, even when I directly copy the example line of code.

Can somebody provide me with the correct method or update the wiki?

**Comment by Yulife** [comment]
working on it

**Comment by Yulife** [comment]
There you go! http://minetweaker3.powerofbytes.com/wiki/ModTweaker:TConstruct_Support_1.10.2

**Comment by WolfieWaffle** [comment]
Thanks!
