### ISSUE TITLE
tconstruct Smeltery error

### ISSUE THREAD

**Issue by Siigari** [jaredlll08/ModTweaker#375]
tconstruct.zs: http://pastebin.com/vxnMgdg2 (from the tutorial/wiki)

minetweaker.log: http://pastebin.com/1KP4xmCM

**Comment by jaredlll08** [comment]
your liquid names are wrong, if it says "could not resolve" it means you have the wrong name

**Comment by Siigari** [comment]
Interesting. That was straight out of the tutorial here:

http://minetweaker3.powerofbytes.com/wiki/ModTweaker:TConstruct_Support

What should they be? So I can test it.

**Comment by jaredlll08** [comment]
The names most likely changed between versions

**Comment by Siigari** [comment]
Yeah, I am getting good stuff now messing around with it. Okay, my apologies there.
