### ISSUE TITLE
Botania Page/Script Weirdness

### ISSUE THREAD

**Issue by ElvenChaos** [jaredlll08/ModTweaker#377]
While porting some of my old scripts from 1.7.10 to the new version of modtweaker for 1.10.2 (MT v. 2.0.4) I noticed some oddities in the Botania Elven Trade and Page supports. I'm not sure if this is caused by changes in ModTweaker or by Botania's API.

Vars for following examples:
val record = <ore:record>;
val Bot1 = <botania:recordGaia1>;  _(This is a botania music disc)_
val Bot2 = <botania:recordGaia2>;  _(This is another botania music disc)_

1. When adding an ElvenTrade recipe, the output variable must now be an array instead of possibly being a single item. This is minor, though I'm noting it because it did catch me off guard at first.
**Old script:** mods.botania.ElvenTrade.addRecipe(Bot1,[record]);
**New script:** mods.botania.ElvenTrade.addRecipe([Bot1],[record]);

2. When adding a Text Page, page text is no longer loaded onto an localization but directly onto a page.
**Old Script:**
mods.botania.Lexicon.addTextPage("botania.page.recordText","botania.entry.elfResources",11);
game.setLocalization("en_US", "botania.page.recordText", "_TEXT SNIP_");
**New Script:**
mods.botania.Lexicon.addTextPage("_TEXT SNIP_","botania.entry.elfResources",11);

3. When adding an Elven Trade Page, output results no longer cycle with input results, and instead inputs will cycle while outputs will display all possible outputs all the time. Also, in both the old and new scripts, you can not define an oredict entry as an input to receive a single output.
Image of new weirdness: https://postimg.org/image/8xqgho9pn/
**Old Script:**
mods.botania.Lexicon.addElvenPage("botania.page.recordElven","botania.entry.elfResources",12,[Bot1,Bot1,Bot1,Bot1,Bot1,Bot1,Bot1,Bot1,Bot1,Bot1,Bot1,Bot1],[_SNIP LIST OF EACH RECORD_]);
**New Script:**
mods.botania.Lexicon.addElvenPage("_SNIP TEXT2_","botania.entry.elfResources",12,[Bot1,Bot1,Bot1,Bot1,Bot1,Bot1,Bot1,Bot1,Bot1,Bot1,Bot1,Bot1],[_SNIP LIST OF EACH RECORD_]);

**_EDIT:_** I can --put-- _cheat_ an ordict entry as an input in this script, but it does not cycle between members of the oredict entry.
**Example:**
mods.botania.Lexicon.addElvenPage("_TEXT SNIP_","botania.entry.elfResources",12,[Bot1],[[record]]);

Old Recipe Script (from 1.7.10): http://pastebin.com/2WfB26X3
New Recipe Script (ported and edited previous script to 1.10.2): http://pastebin.com/RfVSh0uU
ModTweaker 2.0.4
CraftTweaker 3.0.12
Forge 2105
MC 1.10.2

**Comment by jaredlll08** [comment]
ok so, 1 and 2 are known about, and are not bugs, just new script syntax, however, 3 is a bug on Botania's side, I would suggest reporting it to their issue tracker.
