### ISSUE TITLE
Pure Daisy recipes using item damage as conversion time

### ISSUE THREAD

**Issue by goosezilla** [jaredlll08/ModTweaker#378]
Hi im trying to change the block that is used as the input for the pure daisy from botania.

The problem ive come across is that the conversion is instant rather than following the default botania time.

This is my script:

//Botania - Livingrock
val stone = <botania:livingrock>;
val damagedStone = stone.withDamage(150);

mods.botania.PureDaisy.removeRecipe(<botania:livingrock>);
mods.botania.PureDaisy.addRecipe(<roots:runeStone>, stone);

 which is throwing the error WARNING: subitems don't have damaged states and the damage value is not setting the time taken to convert.

**Comment by jaredlll08** [comment]
it is because of the "val" stuff, just do

```
val damagedStone = <botania:livingrock:50>
```
