### ISSUE TITLE
Elven Trade handler seems to be broken

### ISSUE THREAD

**Issue by 666lumberjack** [jaredlll08/ModTweaker#381]
Trying to add a recipe using this handler throws a "no such method" error. Using Modtweaker2-2.0.5 on Minecraft 1.10.2 with Forge 2107 (but I have also had the issue on an older version of Forge and MT). My script:

import mods.botania.ElvenTrade;
ElvenTrade.addRecipe(<botania:manaResource:15>, [<botania:manaBottle>]);

**Comment by jaredlll08** [comment]
Please update crafttweaker, because if you did, you would see that this is a script error.

Anyway, the new syntax is 
```
ElvenTrade.addRecipe(IItemStack[] outputs, IIngredient[] input);
so
ElvenTrade.addRecipe([<botania:manaResource:15>], [<botania:manaBottle>]);
```
