### ISSUE TITLE
Modtweaker not playing nice with JEI with Botania

### ISSUE THREAD

**Issue by utoc** [jaredlll08/ModTweaker#382]
MT Log: https://gist.github.com/utoc/ca188a32e60f1af29f3abf1c71ce0f4b
MT Script: https://gist.github.com/utoc/b3cdb2c938db6f552984a00ca9c05bd7

(full scripts here: https://github.com/utoc/bbqscripts)

JEI doesn't know how to make the item; I'd post a screenshot but there isn't really much to post there.  I consulted @mezz and he asked that I send the issue this way.

Running: FML 2099, jei_1.10.2-3.12.8.325, CraftTweaker-1.10.2-3.0.12,  ModTweaker2-1.10.2-2.0.4

**Comment by jaredlll08** [comment]
update crafttweaker and modtweaker.

**Comment by utoc** [comment]
Issue still exists with CraftTweaker-1.10.2-3.0.13, ModTweaker2-2.0.5

**Comment by jaredlll08** [comment]
Please ca you provide me with a game log of when you tested with the updated versions

**Comment by utoc** [comment]
MT Log: https://gist.github.com/utoc/b64748ab04776e0f2573dd0f1c24b2b8
MC Log: https://gist.github.com/utoc/5319b9737fb8ac1e0a78944bddff71e5

**Comment by jaredlll08** [comment]
Referring to this line of the botania source code:
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/client/integration/jei/manapool/ManaPoolRecipeHandler.java#L45
your mana requirement is too high, decrease it or go complain to them.

**Comment by utoc** [comment]
Bingo,  Thank you Jared.

**Comment by jaredlll08** [comment]
Update crafttweaker and Modtweaker.
