### ISSUE TITLE
Botania Apothecary recipes 

### ISSUE THREAD

**Issue by goosezilla** [jaredlll08/ModTweaker#384]
removing 1 recipe removes all

mods.botania.Apothecary.removeRecipe("endoflame");

will remove all "special flower" recipes, tried with NBT too

**Comment by jaredlll08** [comment]
post all the scripts you have tried please.

**Comment by goosezilla** [comment]
tried the above and also

mods.botania.Apothecary.removeRecipe(<botania:specialFlower>.withTag({type: "endoflame"});

both remove all apothecary recipes

**Comment by jaredlll08** [comment]
try using
```
onlyWithTag
```

**Comment by goosezilla** [comment]
mods.botania.Apothecary.removeRecipe(botania:specialFlower.onlyWithTag({type: "endoflame"}));

thats giving me an error saying it expected ")"

**Comment by goosezilla** [comment]
val flower = <botania:specialFlower>;
val endoflame = flower.onlyWithTag({type:"endoflame"});

mods.botania.Apothecary.removeRecipe(endoflame);

seems to work

Thanks jared
