### ISSUE TITLE
Actually Additions Error

### ISSUE THREAD

**Issue by WenXin20** [jaredlll08/ModTweaker#387]
The log says it is missing an ")" when there already is one.
Minetweaker.log: 
INFO: MineTweaker: Building registry
INFO: MineTweaker: Sucessfully built item registry
INFO: Adding command minetweaker
INFO: Adding minetweaker command tooltips
INFO: 
INFO: Adding minetweaker command randomthings
INFO: Adding minetweaker command materials
INFO: Adding minetweaker command modifiers
INFO: Adding minetweaker command tconstruct
INFO: Adding minetweaker command chiselGroups
INFO: Adding minetweaker command chiselVariations
ERROR: Error parsing Actually Additions.zs:1 -- ) expected

Script: 
mods.actuallyadditions.Coffee.addRecipe(minecraft:reed, 3, ["night_vision", "poison"], [30,15]);

//mods.actuallyadditions.Coffee.remove(minecraft:sugar);

mods.actuallyadditions.Crusher.addRecipe(minecraft:bone),(minecraft:iron_ingot);

mods.actuallyadditions.Crusher.addRecipe(minecraft:reed,minecraft:sugar,minecraft:string,20);

//mods.actuallyadditions.Crusher.removeRecipe(minecraft:gold_ingot);

mods.actuallyadditions.Empowerer.addRecipe(minecraft:bone,minecraft:iron_ingot,minecraft:stone,minecraft:stone:1,minecraft:sugar,minecraft:coal, 100, 200, 255, 5, 5);

//mods.actuallyadditions.Empowerer.remove(minecraft:bone,minecraft:iron_ingot);

mods.actuallyadditions.AtomicReconstructor.addRecipe(minecraft:coal:1, minecraft:coal:0, 500);

mods.actuallyadditions.AtomicReconstructor.addRecipe(minecraft:log, minecraft:coal:1, 500);

//mods.actuallyadditions.AtomicReconstructor.remove(minecraft:coal);

mods.actuallyadditions.Compost.addRecipe(minecraft:dirt,minecraft:dirt:3);

mods.actuallyadditions.Compost.addRecipe(minecraft:stick,minecraft:planks:0, minecraft:dirt, minecraft:dirt);

//mods.actuallyadditions.Compost.remove(minecraft:dirt);

**Comment by jaredlll08** [comment]
NEVER post scripts like that, gist or pastebin them, preferably gist since I can show line numbers, anyway...
```
mods.actuallyadditions.Crusher.addRecipe(minecraft:bone),(minecraft:iron_ingot);
```
should be
```
mods.actuallyadditions.Crusher.addRecipe(minecraft:bone, minecraft:iron_ingot);
```

**Comment by WenXin20** [comment]
Ok, thanks, I got the script from the example, so that's why I didn't know why it wasn't working.
