### ISSUE TITLE
[1.10.2 - 2.0.6] Chisel integration broken

### ISSUE THREAD

**Issue by JasonMcRay** [jaredlll08/ModTweaker#390]
When adding new blocks into chisel groups it first the first time but when reloaded again it does not.

Reproduce steps:
1) Add a block to existing chisel group - mods.chisel.Groups.addVariation("marble", someBlock);
2) Reload the script with "/mt reload"
3) Check the chiseling, marble can be chiseled into the new someBlock
4) Reload the script again
5) Message in chat pops out that chisel group marble does not exist and all the chiselings from marble group dissapear  until game reboot.

I understand that /mt reload can break stuff, but this was not an issue in 1.7.10 and as you can imagine it is bit annoying to always restart minecraft when working with scripts in big modpacks.

**Comment by jaredlll08** [comment]
Don't forget that chisel changed dramatically in 1.10.2...

**Comment by jaredlll08** [comment]
1.7 is no longer supported. 1.7.10 is 2 years / 4 versions old now, it is time to move on. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately
