### ISSUE TITLE
Recipes that use NBT tags not showing correctly in JEI/NEI

### ISSUE THREAD

**Issue by goosezilla** [jaredlll08/ModTweaker#394]
Ive been trying to make a recipe that uses specific Reliquary potions but cant seem to get the recipes to match.

Recipe: http://hastebin.com/ehahetofap.xml

Recipe shown in JEI/NEI: http://i.imgur.com/kg0m0KN.png (not showing potion with NBT tag)

Recipe not working in crafting table: http://i.imgur.com/97SnAsa.png

Recipe working in crafting table: http://i.imgur.com/L3Q6Ed1.png (works only with the correct NBT)

**Comment by jaredlll08** [comment]
You need to use "withTag" for inputs, "withOnlyTag" is for outputs.

**Comment by goosezilla** [comment]
withTag allows any potion which isnt what I need

**Comment by jaredlll08** [comment]
ok so using withOnlyTag does things correctly, it just isn't shown in JEI correctly?

**Comment by goosezilla** [comment]
yes basically not shown in JEI

**Comment by jaredlll08** [comment]
then that is a JEI problem, if the recipe works, then nothing I can do from there.

**Comment by goosezilla** [comment]
https://github.com/mezz/JustEnoughItems/issues/415

Im 99% sure this is the same issue.

**Comment by goosezilla** [comment]
Same NBT issue?

Script: http://hastebin.com/acasuzizoh.xml
Works with an output that isnt NBT tagged. (tried with onlyWithTag and withTag)

Recipe showing in JEI: http://i.imgur.com/DxdeQ6m.png

Apothecary not accepting custom recipe items: http://i.imgur.com/QdZysAq.png

**Comment by cookta2012** [comment]
@jaredlll08 is there a way you can use a generic type so that "withTag" for inputs, "withOnlyTag" is not necessary if not i will take a shot at doing it

**Comment by jaredlll08** [comment]
@cookta2012 nope, because of how things are handled, outputs are always IItemStack and inputs can be nearly anything, so the way the NBT data is dealt with is different.
@goosezilla if you can see that it is a JEI issue. Why are you still posting about it here?

**Comment by goosezilla** [comment]
Because as with the petal apothecary issue im not actually convinced it is an issue with JEI.

**Comment by jaredlll08** [comment]
you don't seem to get this do you.
From what you have told me.
The recipe works when crafted.
The recipe does NOT display correctly in JEI.
Honestly, put 2 and 2 together and you can see it is a JEI issue not displaying the correct nbt.

**Comment by mezz** [comment]
Sorry @jaredlll08 this is not a JEI issue. 
See my replies here that show an example recipe working as intended: 
https://github.com/mezz/JustEnoughItems/issues/653#issuecomment-266241463
