### ISSUE TITLE
Can't Remove/Change Extra Utilities 2 Generators

### ISSUE THREAD

**Issue by royalcw** [jaredlll08/ModTweaker#395]
I'm using the command:  recipes.removeShaped(<extrautils2:Machine>);
In craftTweaker, all the generators have the same name with no extra defining number for each one.  Is there a way to remove or change specific generator recipes?

Since I'm building a progression pack and RF/EU power doesn't take effect until the 3rd age (Industrial Age), I need to either make a recipe adjustment to prevent people from making these until that time or remove these generators all together.

**Comment by jaredlll08** [comment]
Use /mt hand on them.

**Comment by royalcw** [comment]
You are amazing Jared.  Provides <extrautils2:Machine>.withTag([Type: "extrautils2:generator"])
This is the details I needed.  Very similiar to the method of using Tinker's Construct it seems.
