### ISSUE TITLE
[suggestion] Add Ars Magica 2 support

### ISSUE THREAD

**Issue by johnfg12** [jaredlll08/ModTweaker#398]
Since ars magica 2 seems to still be getting updated frequently and the api seems to have more features would we be able to get support for ars Magicas mechanics  https://github.com/Growlith1223/ArsMagica2/tree/1.10.2 
thanks for your time, johnfg12

**Comment by Saereth** [comment]
even just getting support for the essence refiner would open up a ridiculous amount of customization for am2, would be great to see.

**Comment by jaredlll08** [comment]
Ars magica doesn't support 1.12.2 or anything above 1.10.2 for that matter
