### ISSUE TITLE
ExtraUtils Crusher

### ISSUE THREAD

**Issue by Chemiefreak2006** [jaredlll08/ModTweaker#400]
Hello

I tried adding some recipes for ExtraUtils2 and the Resonator is working fine, but I can't add some for the Crusher. I assume the crusher isn't addet yet or ist there a way to implement these as well? 

Greetings from Berlin

Maurice

**Comment by jaredlll08** [comment]
Crusher is not added.

**Comment by Chemiefreak2006** [comment]
Thank you

Any Chance for adding it anytime soon?

**Comment by jaredlll08** [comment]
Just looked into it, the crusher can't be added, due to how it is coded.
