### ISSUE TITLE
Tinkers Construct support does not make use of the new API

### ISSUE THREAD

**Issue by KnightMiner** [jaredlll08/ModTweaker#402]
Other than casting recipes, it seems the Tinkers Construct support is still acting based on the old API, thus a few unneeded things still exist:

* Display item can be anything now, it does not have to be a block. Since the parameter does absolutly nothing in the code right now, there is no need to error and skip the recipe there
* Temperature can either be provided or inferred from the liquid amount and temperature. As it is right now, it is inferring it, while the temp parameter does nothing (should be made @Optional instead)
* Inputs support oredictionary natively. This is true for both the smeltery and the drying rack

ModTweaker version 2.0.7 for 1.10.2 if it helps, though any 1.10.2 version is affected.

**Comment by jaredlll08** [comment]
Which TiC version has the new api?

**Comment by KnightMiner** [comment]
All of TiC 2, so 1.8+. You are calling the new API, but still acting as though you are using the old one (so you have the unused display block parameter and never pass along the temperature, along with handling oredictionary inputs yourself instead of passing them along)

**Comment by Flabort** [comment]
Could this issue be why my script won't work?

http://pastebin.com/eJE3xDAi

Minimum requirements for script:
TAIGA 1.2.6
Whichever Tinkers and Mantle are compatible
Ex Nihilo Adscendio 0.1.11
You will also need this as /config/exnihiloadscendio/oreregistry.JSON : 
http://pastebin.com/RqnjPP9H which in turn means you need more mods to run the script:
Simple Ores 1.8.6.8
Simple Tcon 1.1
Fun  Ores 1.3.3-79
Base Metals 2.4.0.11

Loading the script produces no errors, but no recipe for the melting of the items. I have no idea if I just misspelled something and it's my fault, or if the API is wrong.

**Comment by jaredlll08** [comment]
@Flabort make your own issue. and follow the template please
