### ISSUE TITLE
Thaumcraft Infusion 1.7.10

### ISSUE THREAD

**Issue by Gammelkebab** [jaredlll08/ModTweaker#403]
I don't know if you still do 1.7.10 updates. But here is my issue:
Thaumcraft infusions using buckets of whatever leaving the bucket - I couldn't find an option to define that on the modtweaker wiki. Is it implemented? I'm trying to use primordial pearls and leave powerless pearls from witching gadgets.

**Comment by jaredlll08** [comment]
1.7.10 is no longer supported
