### ISSUE TITLE
Cannot add Carpenter recipes

### ISSUE THREAD

**Issue by JasonMcRay** [jaredlll08/ModTweaker#405]
I am unable to add any carpenter recipes. I used parameters as they are suggested on wiki: http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Forestry_Support but it gives me error
`a method available but none matches the parameters (minetweaker.item.IItemStack, minetweaker.item.IIngredient[][], minetweaker.liquid.ILiquidStack, int, minetweaker.item.IItemStack)
This is usually an error in your script, not in the mod`

The recipe I am adding:
`Carpenter.addRecipe(thermionicFabricator, [[steelScrew, null, steelScrew],
                                           [icCoil, sturdyCasing, icCoil],
                                           [steelScrew, electricMotorLV, steelScrew]], moltenRedstone * 1008, 300, worktable);`

I assume the wiki is outdated. What is the correct way of adding carpenter recipes?

Using 2.0.8 version of ModTweaker

**Comment by JasonMcRay** [comment]
Also to add. I took a look at the code: https://github.com/jaredlll08/ModTweaker/blob/master/src/main/java/modtweaker/mods/forestry/handlers/Carpenter.java#L39

So I swapped the Time and Liquid.
that gives me Error executing forestry.zs: null
(`ERROR: Error executing forestry.zs: null
java.lang.ArrayIndexOutOfBoundsException` from the minetweaker.log file)

**Comment by jaredlll08** [comment]
could I get the log file from when it gave the AIOBE please

**Comment by JasonMcRay** [comment]
Here you go 
[minetweaker.txt](https://github.com/jaredlll08/ModTweaker/files/673210/minetweaker.txt)

**Comment by davqvist** [comment]
I just tested the update as well and also get exactly the same error message.

**Comment by jaredlll08** [comment]
found and fixed this issue, I just need to test it, then I'll get a build out

**Comment by JasonMcRay** [comment]
Awesome thanks

**Comment by davqvist** [comment]
Installed 2.0.9, I don't get any error messages anymore, but it's still not working.
Both removing a recipe and adding a recipe just does nothing.

For example:
`mods.forestry.Carpenter.removeRecipe(<forestry:chipsets>, <liquid:water>);`
The log outputs:
`INFO: Removing 1 Forestry Carpenter Recipe(s) for <forestry:chipsets>.withTag({T: 0 as short})`
But JEI still shows the recipe and it still works. Same is with adding a recipe, it simply does nothing.
`mods.forestry.Carpenter.addRecipe(<enderio:itemMachinePart>, [[<minecraft:iron_bars>, <minecraft:iron_bars>, <minecraft:iron_bars>], [<actuallyadditions:blockMisc:9>, <enderio:itemBasicCapacitor>, <forestry:sturdyMachine>], [<minecraft:iron_bars>, <minecraft:iron_bars>, <minecraft:iron_bars>]], 20, <liquid:seed.oil> * 1000);`
Log:
`INFO: Adding 1 Forestry Carpenter Recipe(s) for <enderio:itemMachinePart>`

If you need more info, let me know.
