### ISSUE TITLE
using a for loop to add recipes in a oredict entry works... kind of 

### ISSUE THREAD

**Issue by JavaBeanJohnny** [jaredlll08/ModTweaker#408]
so I am trying to add fluid transposer extract recipes in a couple of the oredict categories, with this code 

`for item in <ore:logWood>.items {`

`mods.thermalexpansion.Transposer.addExtractRecipe(200,`
`item, <minecraft:planks>, xpjuice * 60,  100);`

`}`

`for item in <ore:treeLeaves>.items {`

`mods.thermalexpansion.Transposer.addExtractRecipe(200, `
`item, <minecraft:stick>, xpjuice * 90,  100);`

`}`

`for item in <ore:treeSapling>.items {`

`mods.thermalexpansion.Transposer.addExtractRecipe(200, `
`item, <minecraft:stick>, xpjuice * 300,  100);`

`}`

and as far as making the recipes, it works perfectly. I can see all of them in NEI. but the fluid transposer wont accept any of the items that are supposed to be valid

**Comment by jaredlll08** [comment]
TE bug.
1.7.10 is no longer supported.

**Comment by JavaBeanJohnny** [comment]
is there a way to fix it? can i just go to a earlier version of TE?

**Comment by jaredlll08** [comment]
I don't know, TE is not my mod.

**Comment by JavaBeanJohnny** [comment]
when did it stop being supported?

**Comment by jaredlll08** [comment]
When 1.10 started becoming big. Months now. 1.7.10 is 4 Mc versions old,
I'm not supporting it.
