### ISSUE TITLE
Removed Recipes Still Visible in JEI

### ISSUE THREAD

**Issue by Boolyman** [jaredlll08/ModTweaker#409]
#### Issue Description:
Using commands like the one below, the removed recipes are still visible.  I have also tried using the 4 digit item id # in place of the item name.

recipes.remove(<ic2:jetpack_electric>);

#### What happens:

After adding a new recipe, the new recipe appears below the deleted one in JEI.  This can cause obvious confusion to those who are looking up a recipe.   Yes, I am aware that the "removed" recipe is uncraftable... but it should not be showing up at ALL in JEI.  How can we fix this?

#### What you expected to happen:
When a recipe is removed, and a new one added... only the new recipe should show up in JEI

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

recipes.remove(<ic2:jetpack_electric>);

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2202
- Crafttweaker: 1.10.2-3.0.17
- ModTweaker: 2-2.0.8

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
Mt lib version?

**Comment by Boolyman** [comment]
MTLib-1.0.1.jar

**Comment by jaredlll08** [comment]
What JEI version?

**Comment by Boolyman** [comment]
1.10.2-0.5.8.98

**Comment by jaredlll08** [comment]
You are away that you are EXTREMELY out of date?
3.14.2.401 is the latest for 1.10 and Crafttweaker NEEDS 3.14.2.398 to work

**Comment by Boolyman** [comment]
I mistakenly gave you the version number for Just Enough Resources, instead of Just Enough Items... My JEI is 3.14.25.401.

**Comment by jaredlll08** [comment]
Give me a gamelog please
