### ISSUE TITLE
Thermionic Fabricator Recipes still broken

### ISSUE THREAD

**Issue by davqvist** [jaredlll08/ModTweaker#410]
#### Issue Description:
Adding Thermionic Fabricator Recipes doesn't work
see Issue #393 which is closed and doesn't get reopened even though the error still persists.

#### What happens:
Adding a Recipe to the Thermionic Fabricator doesn't work and outputs an error

#### What you expected to happen:
That adding a Recipe to the Thermionic Fabricator works

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
http://pastebin.com/uXZr66nh

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
http://pastebin.com/QT4LUptx

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Crafttweaker: 3.0.17
- ModTweaker: 2.0.9

#### Your most recent log file where the issue was present: 

I aleady posted the minetweaker.log above

**Comment by al132** [comment]
I was just about to post this, as i've been experiencing the same problem.
