### ISSUE TITLE
Adding Centrifuge Recipe doesn't work

### ISSUE THREAD

**Issue by davqvist** [jaredlll08/ModTweaker#411]
#### Issue Description:
Adding a Centrifuge Recipe has apparently no effect even though the log says it successfully added it.

#### What happens:
When I add a Centrifuge Recipe it doesn't work.
What's confusing to me is that the same recipe worked a few weeks ago. So I made a new instance with only the mods needed:
CraftTweaker
EnderIO
EnderCore
Forestry
IndustrialCraft
JEI
ModTweaker
MTLib

I reverted CraftTweaker and ModTweaker step by step a version back at a time and restarted the pack everytime until I was at a date where I was sure that it still worked and it even doesn't work in old versions even though it worked a month back, I'm certain. I even reverted Forestry to an older version and it didn't work, so I have no clue what's going on.

#### What you expected to happen:
That adding a Centrifuge recipe works.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
http://pastebin.com/E4H3vjwh

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
http://pastebin.com/q5NRg4qB

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2202
- Crafttweaker: 3.0.17
- ModTweaker: 2.0.9

#### Your most recent log file where the issue was present: 

see above

**Comment by jaredlll08** [comment]
Are you looking at the recipe in JEI or trying to craft it?

**Comment by davqvist** [comment]
I tried to craft it, didn't work, although I didn't try in all CraftTweaker/Modtweaker versions

**Comment by jaredlll08** [comment]
hhm mind passing the gamelog along?

**Comment by davqvist** [comment]
https://gist.github.com/davqvist/c8fa785d1051805d242fe8a578dde3c1

**Comment by jaredlll08** [comment]
Try with the latest modtweaker please

**Comment by davqvist** [comment]
Not sure what you mean. The log I sent you was from the latest version of Modtweaker as described in the original post (2.0.9) and I can't find any newer version on Curse.

**Comment by jaredlll08** [comment]
Fixed by PR
