### ISSUE TITLE
Botania Help

### ISSUE THREAD

**Issue by RobertLSnead** [jaredlll08/ModTweaker#414]
The following code does not seem to work and nothing happens.

//Elven Trade
//OutputStack, InputArray
mods.botania.ElvenTrade.addRecipe(<botania:manaResource:5>, [<botania:manaResource:4>]);

MC 1.10.2
Forge 12.18.2.2185
CraftTweaker 3.0.17
ModTweaker 2.0.9

Minetweaker Log:
ERROR: Minetweaker.zs:145 > a method available but none matches the parameters (minetweaker.item.IItemStack, minetweaker.item.IIngredient[])
This is usually an error in your script, not in the mod
addRecipe(ZenTypeArrayBasic, ZenTypeArrayBasic )

**Comment by jaredlll08** [comment]
We have an issue template for a reason.

**Comment by RobertLSnead** [comment]
My apologies, I'm use to the lax of other mod authors.  I will have it filled out later today.

**Comment by RobertLSnead** [comment]
I have posted the issue under #416
[#416](https://github.com/jaredlll08/ModTweaker/issues/416)
