### ISSUE TITLE
botania infusion altar not working

### ISSUE THREAD

**Issue by redgoblin88** [jaredlll08/ModTweaker#415]
#### Issue Description:
on my friends modpack, i am in charge of all the scripts, he has given me the challenge of making the golden notch apple craftable in the botania infusion altar.

he said it should be a gold and diamond block, night vision potion with max length, a rune of earth and fire, a golden apple and 2 more things aswell as the cost being half a manapool and here is what i came up with:

mods.botania.RuneAltar.addRecipe(<minecraft:golden_apple:1>,[<botania:rune:1>,<botania:rune:2>,<botania:rune:11>,<minecraft:golden_apple>,<minecraft:diamond_block>,<minecraft:gold_block>,<minecraft:potion>.withTag({Potion: "minecraft:long_night_vision"})],50000);

#### What happens:
upon completing the script and issuing the "/mt reload" command, the chat output sats "reload comple" which indicates no issue which is backed up by the consol log.
However when i go too look at the (should be) new recipe it did not come up in JEI, so thinking that i got things mixed around i checked if the crafting ingredients had a new use in the altar which they did not.

#### What you expected to happen:

as i said in the "description" i expected the notch apple to have a new recipe in the botania infusion altar, but nothing new was added

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

http://pastebin.com/U30ce4QV

please note that this has additional scripts. these all work, it is only the last line with the botania altar which does not.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

http://pastebin.com/VLFNvRtt

there are other scripts but they all work fine.
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.10.2
- Forge:12.18.3.2185
- Crafttweaker: 3.0.17
- ModTweaker:2.0.8

note: i am aware there is an updated modtweaker (2.0.9) but the changelog nor github show any updates with botania, particularly the infuson altar

#### Your most recent log file where the issue was present: 
[pastebin/gist/etc link here]

https://gist.github.com/redgoblin88/51402182800a8bced7e192179e5f6ec6

**Comment by jaredlll08** [comment]
Mt lib version?

**Comment by redgoblin88** [comment]
im using MTLib 1.0.0

**Comment by jaredlll08** [comment]
Update it.

**Comment by redgoblin88** [comment]
ah yes that has fixed it, thank you for your help, i was not aware modtweaker used that mod
