### ISSUE TITLE
Botania Elven Trade Recipe Issue

### ISSUE THREAD

**Issue by RobertLSnead** [jaredlll08/ModTweaker#416]
#### Issue Description:
I added the Botania Elven Trade Recipe from the ModTweaker Recipe from the ModTweaker wiki.  The site states Botania being supported.  However there was no supported code mentioned for the MC1.10.2 and I used the MC1.7.10 known recipe.

Wiki Links:
[Currently_Supported_Mods_1.10.2](http://minetweaker3.powerofbytes.com/wiki/ModTweaker#Currently_Supported_Mods_1.10.2)
[ModTweaker:Botania_Support_1.10.2](http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Botania_Support_1.10.2)
[ModTweaker:Botania_Support](http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Botania_Support)

#### What happens:
I get an error message in the minetweaker log and the recipe does not work.
See Link below.

#### What you expected to happen:
Expected Elven trade recipe to work and no errors in the minetweaker.log file.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
[Script](http://pastebin.com/y8wXTAhB)

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
[Log](http://pastebin.com/aK7Areyi)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.2.2185
- Crafttweaker: 3.0.17
- ModTweaker: 2.0.9

#### Your most recent log file where the issue was present: 

See Above Links.

**Comment by jaredlll08** [comment]
The synntax has changed, the output is now an array. It says so in your minetweaker.log.

**Comment by RobertLSnead** [comment]
You have an example?

**Comment by jaredlll08** [comment]
```
mods.botania.ElvenTrade.addRecipe(<botania:manaResource:5>, [<botania:manaResource:4>]);
```

**Comment by RobertLSnead** [comment]
You my friend are awesome :D

Seriously Thank You!

**Comment by RobertLSnead** [comment]
I see it now just did not understand the error message.
