### ISSUE TITLE
Chisel 2 issue

### ISSUE THREAD

**Issue by Krysinski** [jaredlll08/ModTweaker#417]
#### Issue Description:
ModT not working with chise2! I try to remove Geologica cobblestone blocks from group "cobblestone".
refer with: https://github.com/Chisel-Team/Chisel/issues/329
refer with: https://github.com/lawremi/PerFabricaAdAstra/issues/58

#### What happens:
Script run without errors and nothing been changed for group "cobblestone".
Also, i found that `/mt chiselVariations` wont get me full list of group "cobblestone", only one geologica block was in list. And i try to remove only this one block wich was in group.

#### What you expected to happen:
Script must remove one block from group "cobblestone".

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):https://gist.github.com/Krysinski/e32fa6df4fcc235eb745ca5101122a5a
There is a last part of log file, after i use `/mt chiselVariations` in console to get list of variations. No any errors in log. 

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.7.10 (server: Thermos-1.7.10-1614-56)
- Forge: 1614
- Crafttweaker: none
- ModTweaker: 2.3.10.37

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by tterrag1098** [comment]
That's not how that command works. I explained this to you on your original issue.

**Comment by Krysinski** [comment]
If i cant manage crossconvertable blocks inside "group" (group - like i see blocks in chisel gui) with ModT, then.... hm I think this part of ModT are useless. People just wast those time with this.

**Comment by tterrag1098** [comment]
No, you are fundamentally misunderstanding the problem. Geologica blocks are NOT inside the group. The group has an oredict "tag" associated with it.

**Comment by Krysinski** [comment]
Noo)) WTF are one block in a group???
<PFAAGeologica:strongCobble:3> cobblestone

**Comment by jaredlll08** [comment]
uh I have no idea what is going on here, but I don't think it is actually a MoT issue, correct me if I'm wrong
