### ISSUE TITLE
Bug Report: JEI recipes not loading up with ModTweaker Scripts

### ISSUE THREAD

**Issue by EmoKiba** [jaredlll08/ModTweaker#418]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker or ModTweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:
JEI recipes arent showing up for my custom modtweaker (version 2.0.9) recipes. However when reverting back one version down (3.0.1.6) shows the recipes back when on version(1.0.0) of MTlib but then the Extra Util 2 version (1.1.2) recipes dont show up in JEI. Noted though the recipes from latest version do work on EXU2 except for the ones that involve XP to craft ie (lasso, magical wood)

#### What you expected to happen:
For the ModTweaker Recipes to Show up in JEI and for the EXU2 recipes to show up as well.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
http://pastebin.com/d0vmqykc

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge:12.18.3.2185
- Crafttweaker: : 3.0.17
- ModTweaker: 2.0.9

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
SERIOUSLY?! I REPLIED TO THIS ISSUE ON THE CRAFTTWEAKER REPO. CHOOSE A REPO AND STICK TO IT!
