### ISSUE TITLE
[Mod Support] Advanced Rocketry

### ISSUE THREAD

**Issue by xSparky911x** [jaredlll08/ModTweaker#419]
Was hoping to get support added for Advanced Rocketry. They also use a dependency libVulpes

**Comment by MechWarrior99** [comment]
It adds it's own way of adding/removing recipes in the form of an XML file system. [Here](http://65.78.115.159:8000/AdvancedRocketry/config/RecipeConfiguration.php) is the info on it.

**Comment by xSparky911x** [comment]
Hey awesome thank you very much
