### ISSUE TITLE
Refined Storage Solderer info

### ISSUE THREAD

**Issue by DrDarkfire** [jaredlll08/ModTweaker#420]
#### Issue Description:
No literature about how to use the Refined Storage solderer with modtweaker

#### What happens:
Can't find information on how to use the solderer despite the code existing on GitHub for it

#### What you expected to happen:
Find information somewhere on how to use it

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

NA since I can't find anything on it

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:
- Forge:
- Crafttweaker: 
- ModTweaker:
- MTLib:

#### Your most recent log file where the issue was present: 
NA
[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Refined_Storage_Support_1.10.2
