### ISSUE TITLE
Can't get Smeltery.addMelting to add melting recipes that show up in JEI

### ISSUE THREAD

**Issue by Flabort** [jaredlll08/ModTweaker#421]
#### Issue Description:
Smeltery melting recipes do not work for me. 
Edit: They work, but do not show up in JEI.

#### What happens:

Loading the script produces no errors, but no recipe for the melting of the items. I have no idea if I just misspelled something and it's my fault, or if the API is wrong.

Edit: The items do melt into the appropriate liquids, but the recipe does not show in JEI.

#### What you expected to happen:

That the items used in the script would be able to be melted down into the respective fluids just like the ores that the items resemble.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

http://pastebin.com/eJE3xDAi

Unrelated scripts that I also wrote, but which work and are probably referenced in the minetweaker.log file:
http://pastebin.com/iHTyEs8q
http://pastebin.com/YX84fvBc

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

http://pastebin.com/JFeux2cD
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Crafttweaker: 3.0.17
- ModTweaker: 2.0.9
- MTLib: 1.0.1
Additional resources needed to reproduce:
- Tinkers Construct 2.6.2
- Mantle 1.1.4
- TAIGA 1.2.6
- Ex Nihilo Adscendio 0.1.11
-  /config/exnihiloadscendio/oreregistry.JSON : http://pastebin.com/RqnjPP9H 
- Simple Ores 1.8.6.8
- Simple Tcon 1.1
- Fun Ores 1.3.3-79
- Base Metals 2.4.0.11

#### Your most recent log file where the issue was present: 

http://pastebin.com/JFeux2cD

**Comment by jaredlll08** [comment]
Are you trying to craft it or looking in JEI?

**Comment by Flabort** [comment]
JEI. I'll try to use one of the melting recipes that I'm adding to see if it's just not showing up in JEI.

**Comment by Flabort** [comment]
Tests show it works, despite the new recipes not being in JEI. Thanks. I'll change the title.
