### ISSUE TITLE
Pure Daisy Recipes Complete Instantly

### ISSUE THREAD

**Issue by abculatter2** [jaredlll08/ModTweaker#425]
#### Issue Description:
Pure Daisy recipes from Modtweaker seem to complete instantly, and there doesn't seem to be a way to control how long it takes in the recipe, so I assume this is a bug.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
Literally any recipe seems to cause this.
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10
- Forge: 12.18.3.2221
- Crafttweaker: 3.0.20
- ModTweaker: 2.0.9
- MTLib: 1.0.1

**Comment by al132** [comment]
We aren't running the current version because of some outstanding bugs, but on All The Mods expert we use something like this successfully, but I assume it would work with the current version as well.

> //=====Livingrock=====
> //
> val stone = <botania:livingrock>;
> val damagedStone = <botania:livingrock:150>;
> 
> mods.botania.PureDaisy.removeRecipe(<botania:livingrock>);
> mods.botania.PureDaisy.addRecipe(<roots:runeStone>, damagedStone);

**Comment by jaredlll08** [comment]
Fixed in dev.

You can now do:
mods.botania.PureDaisy.addRecipe(<minecraft:emerald_block>, <minecraft:diamond_block>, 20);
with the 20 being a time (in ticks)
