### ISSUE TITLE
TConstruct recipes does not integrate with JEI

### ISSUE THREAD

**Issue by eoistana** [jaredlll08/ModTweaker#426]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker or ModTweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:
When adding a recipe to the casting table, the recipe is not visible in JEI. 
The recipe works.
Looking at the code, it seems like the JEI integration is not added for TConstruct.

#### What you expected to happen:
Able to see the new recipe.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
`mods.tconstruct.Casting.addTableRecipe(<extrautils2:ingredients>, <liquid:redstonealloy> * 576, <extrautils2:endershard>, true, 128);`

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

Logfile does not show any errors.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2221
- Crafttweaker: 1.10.2-3.0.20
- ModTweaker: 2.0.9
- MTLib: 1.0.1

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by Saereth** [comment]
Having a similar issue same version of MTlib/MT/CT and forge. When I remove a recipe it still shows in JEI although the recipe stops working as expected in the smeltery.

**Comment by JasonMcRay** [comment]
I can confirm this happens not only with Tinkers, but most of other processing recipes. Like if I add a recipe to IC2 compressor. The recipe works but is not shown in JEI.

**Comment by Arakhor** [comment]
The latest version was supposed to fix this issue. However, not only the issue still presists, but now it also happens for drying recipes (in the previous version only casting was broken).

**Comment by jaredlll08** [comment]
O_o that is weird, I was referencing this issue when I fixed it:
https://github.com/jaredlll08/ModTweaker/issues/421
