### ISSUE TITLE
Storage Drawers

### ISSUE THREAD

**Issue by xSparky911x** [jaredlll08/ModTweaker#428]
#### What happens:
While Storage Drawers says they have an API with MineTweaker support, using their example...

> mods.storagedrawers.Compaction.add(<itemUpper>, <itemLower>, conversion);

I get an error executing...

>No such member: Compaction 

#### What you expected to happen:
The ability to add Storage Drawers recipes as per their documentation...
https://github.com/jaquadro/StorageDrawers/wiki/MineTweaker-API
Unless there is a different method that Minetweaker uses and I am just doing it wrong.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

The script is a 1 liner so here it is...

> mods.storagedrawers.Compaction.add(<actuallyadditions:blockMisc:2>, <actuallyadditions:itemMisc:5>, 4);

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

The log: http://pastebin.com/W2cgykUd

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 2221
- Crafttweaker: 3.0.20
- ModTweaker: 2.0.9
- MTLib: 1.0.1

**Comment by jaredlll08** [comment]
Report to storage draws. I have nothing to do with the support.
