### ISSUE TITLE
Cant remove elven trade recipes

### ISSUE THREAD

**Issue by Saereth** [jaredlll08/ModTweaker#430]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker or ModTweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

Perhaps a synax issue but
mods.botania.ElvenTrade.removeRecipe([<botania:dreamwood>]);
and
mods.botania.ElvenTrade.removeRecipe(<botania:dreamwood>);

neither removes the recipe, errors thrown are

#### What happens:

Error is thrown, recipe remains
https://hastebin.com/egesahoxot.pl

#### What you expected to happen:

Recipe to be removed

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

tried both
mods.botania.ElvenTrade.removeRecipe([<botania:dreamwood>]);
mods.botania.ElvenTrade.removeRecipe(<botania:dreamwood>);

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

ERROR: botania.zs:51 > a method available but none matches the parameters (any[])
This is usually an error in your script, not in the mod
removeRecipe(ZenTypeNative )

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Crafttweaker: 1.10.2-3.0.20
- ModTweaker: 2.0.9
- MTLib: 1.0.1

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryRichard** [comment]
It should be "<botania:dreamwood>", not "botania:dreamwood"

**Comment by Saereth** [comment]
mods.botania.ElvenTrade.removeRecipe(<botania:dreamwood>); is throwing the same error
http://imgur.com/a/Qdbiu

**Comment by jaredlll08** [comment]
The Syntax changed, the first parameter is now an array

**Comment by jaredlll08** [comment]
Here is an example of the correct syntax
mods.botania.ElvenTrade.addRecipe([<botania:flower:4>], [<minecraft:redstone>]);

**Comment by Saereth** [comment]
This issue issue still present, adding is not a problem and it works fine, removing the recipe is erroring. 

`mods.botania.ElvenTrade.removeRecipe(<botania:dreamwood>);`
is my exactly syntax also tried:
 `mods.botania.ElvenTrade.removeRecipe([<botania:dreamwood>]);`

neither work, updated to the latest forge version since this post, no difference.
