### ISSUE TITLE
1.7.10 lexiconEntries command missing

### ISSUE THREAD

**Issue by Alrena** [jaredlll08/ModTweaker#431]
#### Issue Description:
When attempting to pull entries for the Botania Lexicon I discovered that the '/mt lexiconEntries' command is invalid. According to the minetweaker log only the lexiconCategories and lexiconPages commands for the lexicon are loading. The loss of the entries command makes it nearly impossible to edit any part of the lexicon.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
http://pastebin.com/9ZG0am9J

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.7.10
- Forge: 10.13.4.1614
- Crafttweaker: N/A
- ModTweaker: 0.9.6
- MTLib:
- Botania: r1.8-249

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
The command never existed
1.7.10 is not supported

**Comment by Alrena** [comment]
The command must have existed. The wiki page explicitly states it's for the 1.7.10 version and was last updated August 18th of 2015. The final version of Botania for 1.7.10 was Fed 25th of 2016, nearly half a year after. Botania had no version for 1.8 or above prior to that date. Additionally the commands to remove pages from the Botania Lexicon requires knowledge of the entry it is inside of, specifically the entry key, which is unknowable outside of random guessing or looking such information up. It is impossible to locate that information in the current version unless I'm doing something wrong or having the most recent version of both mods somehow breaks that functionality.

I understand that you no longer support 1.7.10 but as it stands there is literally no point to being able to remove pages or entries, as listed in the wiki, because it is nearly impossible to locate them. All I'm looking for is a list of the entry keys or a way to locate them, nothing more. I would greatly appreciate it if you can help guide me in the right direction.
