### ISSUE TITLE
[1.10.2] Unable to add Custom Chisel Groups

### ISSUE THREAD

**Issue by JasonMcRay** [jaredlll08/ModTweaker#434]
#### Issue Description:
Unable to add custom chisel groups and variations to them

#### What happens:
When i try to add chisel group and then variations to that group i still cannot chisel the blocks.

#### What you expected to happen:
Being able to chisel into blocks

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
http://pastebin.com/UPi1A3Br

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
http://pastebin.com/V5GGCQDg

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Crafttweaker: 3.0.22
- ModTweaker: 2.0.9
- MTLib: 1.0.1
- Chisel: 0.0.8.12

#### Your most recent log file where the issue was present: 

http://pastebin.com/UkrMdJNv

**Comment by jaredlll08** [comment]
I can't reproduce this at all, using your exact script, with the same chisel, I can still chisel stuff.
The one change I made was replacing the IE blocks with clay and sand.
http://i.blamejared.com/u1ngf.gif

**Comment by JasonMcRay** [comment]
Did one extra test. It seems to fail when metadata is involved. Right now I tested it with this:

```
Groups.addGroup("lightConcrete");
Groups.addVariation("lightConcrete", <minecraft:dirt>);
Groups.addVariation("lightConcrete", <minecraft:sand>);
Groups.addVariation("lightConcrete", <minecraft:dirt:1>);
```

It succesfully added Dirt and Sand. But totally ignored the Dirt (meta 1) which is vanilla Coarse Dirt
