### ISSUE TITLE
JEI Shows custom recipes duplicated after every reloading the scripts files.

### ISSUE THREAD

**Issue by SOL3675** [jaredlll08/ModTweaker#437]
#### Issue Description:
I added the recipes of thermionic fabricator and reloaded the scripts, JEI shows that recipe. However, the I reload two times after added the recipe, it shows two of same recipe, three times, it shows three.

http://i.imgur.com/tJrQFlp.png

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
http://pastebin.com/zi9v9H3B

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
http://pastebin.com/EYv2H8BJ
no duplicated recipes in log file.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.10.2
- Forge:12.18.3.2234
- Crafttweaker: 3.0.23
- ModTweaker: latest build on Jenkins(2.0.9 not on Curse)
- MTLib:1.0.1

**Comment by jaredlll08** [comment]
Try with 2.0.10 please

**Comment by davqvist** [comment]
I just tested with 2.0.10 and can confirm this. Also even more and other mods are affected. I assume it's a similar bug/reason. So far I have found this:

Forestry: Removing recipes still shows in JEI, adding recipes get duplicated when reloading
IC2: Adding recipes aren't shown in JEI at all, I have no scripts in my pack that remove recipes, but that may be broken as well.
Tinkers: Removing recipes still shows in JEI, adding recipes don't show in JEI

Of course adding and removing recipes work, just JEI doesn't reflect the changes. Here's an example script to test all of that: http://pastebin.com/HcXnLBM8

Minecraft 1.10.2
Forge 12.18.3.2254
Modtweaker 2.0.10
Crafttweaker 3.0.24
MTLib 1.0.1

**Comment by SOL3675** [comment]
I updated the versions above, still have same issue, and customed TiC recipes are not shown in JEI.

IC2 support is not MoT side. CraftTweaker is.

**Comment by jaredlll08** [comment]
Ok wait, don't list all the mods that have problems in the same issue, it just causes problems when Im fixing it. 

So Forestry, is it just the fabricator? Or other machines as well?

**Comment by davqvist** [comment]
Sorry, I thought that this is a similar issue, but of course if you want I can create separate issues. And it didn't even come to my mind that IC2 would be Crafttweaker, seemed obvious to me that this is Modtweaker.

To answer the question: I tested Thermionic Fabricator, Carpenter and Centrifuge (Centrifuge only adding though, not sure if removing is bugged as well), same issue with all of the machines.

**Comment by davqvist** [comment]
So, I was about to report the other 2 mods issues, but saw that the other 2 mods bugs are already reported:
https://github.com/jaredlll08/ModTweaker/issues/426
https://github.com/jaredlll08/CraftTweaker/issues/157

**Comment by SOL3675** [comment]
I added the recipe of hellfire forge from blood magic, and duplicated.
http://i.imgur.com/JPFJw6k.png

**Comment by LokyLive** [comment]
Same Problem with some Mekanism Recipe

**Comment by jaredlll08** [comment]
Can anyone reproduce this without calling /mt reload?

**Comment by LokyLive** [comment]
Same problem when i restart modpack

**Comment by wizard1399** [comment]
Possible work around: try removing jei from the pack and restart the mc instance and login to your world where testing. After that, close out and readd jei. This should cause jei to remap all recipes.

**Comment by jaredlll08** [comment]
1.10.2 isn't supported anymore / Issue has been fixed in 1.12
