### ISSUE TITLE
Custom fuels not melting anything in Tinkers

### ISSUE THREAD

**Issue by Saereth** [jaredlll08/ModTweaker#439]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker or ModTweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

Custom fuels not working correctly

#### What happens:
I added a custom fuel (Pyrotheum from TE) it shows 4000C in the smeltery window but it wont melt iron because it says its too cold. Lava melts the iron fine.
http://imgur.com/a/Lduu3

#### What you expected to happen:
Expected the iron ore to be melted by the 4000C pyrotheum

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

Used a Single line script for testing
mods.tconstruct.Smeltery.addFuel(<liquid:pyrotheum>);

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://hastebin.com/witozunonu.md
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge:  12.18.3.2254
- Crafttweaker: 3.0.24
- ModTweaker: 2.0.10
- MTLib: 1.0.1

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
No error in the logs, seems to have added successfully

**Comment by jaredlll08** [comment]
Tic issue, if ths smeltery didn't accept it in the first place, then it would be us, but since it accepts it and says the heat, it is TiC

**Comment by bookerthegeek** [comment]
Dont you need to specify a heat value?

**Comment by jaredlll08** [comment]
Nope, iirc in 1.10 it uses the liquid heat (Forge thing) as the temp

**Comment by bookerthegeek** [comment]
Odd, but good to know.

**Comment by KnightMiner** [comment]
The smeltery accepts any fluid in the furl area, it's just only valid ones actually heat it. Your methods for adding fuels makes no sense, as you are simply adding to a copy of a copy of the key values for fluids instead of the actual list.

**Comment by jaredlll08** [comment]
@KnightMiner honestly not sure what I was thinking when I did that code, anyway I updated it to what it should be (from what I can tell anyway), and while the code works, and the recipe gets added, I think the temp stuff is being a bit iffy, like this for example
http://i.blamejared.com/oJEu9.png
I have 
```
mods.tconstruct.Smeltery.addFuel(<liquid:iron>, 2000);
```
But the temp is wrong according to the smeltery, so is this something in my code or just a new way that TiC works?

**Comment by KnightMiner** [comment]
Hmm, seems the display value is just the fluids temperature rather than the registry one, which might be the same case for which value we use for the temperature. I'll add that to the list of fix.

**Comment by WesCook** [comment]
Oh cool.  So will the ability to specify temperatures be coming back in ModTweaker, or will it continue to be set by the fluid registry?

I was just looking into ways of setting Molten Hellfire as a powerful fuel source (Better with Mods), but that doesn't seem possible just yet.

**Comment by Ben64** [comment]
@jaredlll08 I've been doing some digging today and it seems like fuels are not being added or removed properly. I can't get Lava to stop working, and also cannot get any other liquid to start working in the smeltery. By default, the smeltery accepts any liquid into the tank, but doesn't accept it as fuel unless the amount drops below what you put in (usually 1000mb -- 1 bucket)

From the picture you posted above, it looks like the molten iron is working, although that must be a different version, as the newer ones no longer let you specify a number after the liquid.

**Comment by jaredlll08** [comment]
@Ben64 that is a new version I'm working on, I'm waiting for TiC to fix the number issue first, then I'll release it
