### ISSUE TITLE
Still can't remove Elven Trade recipes

### ISSUE THREAD

**Issue by Saereth** [jaredlll08/ModTweaker#442]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker or ModTweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

This issue is re-opened as the responses given in the original issue (https://github.com/jaredlll08/ModTweaker/issues/430) related to syntax changes with adding. I never had an issue adding after looking through the code for the syntax change, it's removing that doesn't work. 

```
mods.botania.ElvenTrade.removeRecipe([<botania:dreamwood>]);
and
mods.botania.ElvenTrade.removeRecipe(<botania:dreamwood>);

```
neither removes the recipe, both error

#### What happens:

Error is thrown, recipe remains
https://hastebin.com/egesahoxot.pl

#### What you expected to happen:

Recipe to be removed

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

tried both
```
mods.botania.ElvenTrade.removeRecipe([<botania:dreamwood>]);
mods.botania.ElvenTrade.removeRecipe(<botania:dreamwood>);
```

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

ERROR: botania.zs:51 > a method available but none matches the parameters (any[])
This is usually an error in your script, not in the mod
removeRecipe(ZenTypeNative )

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Crafttweaker: 1.10.2-3.0.20
- ModTweaker: 2.0.9
- MTLib: 1.0.1

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by yepidoodles** [comment]
I'm also having this issue

`mods.botania.ElvenTrade.removeRecipe([<botania:manaResource:7>]);`

Same error as above

```
[CHAT] ERROR: Botania.zs:35 > a method available but none matches the parameters (any[])
This is usually an error in your script, not in the mod
removeRecipe(ZenTypeNative )
```

Minecraft: 1.10.2
Forge: 12.18.3.2422
CraftTweaker: 3.0.26
ModTweaker: 2.0.13
MTLib: 1.0.3
