### ISSUE TITLE
TConstruct

### ISSUE THREAD

**Issue by MrByryndyk** [jaredlll08/ModTweaker#445]
#### What happens:
Used in the code <ore: logWood> - the script gives an error.
With standard recipes crafting it works.

#### What you expected to happen:
Must be used all types of logs.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
http://pastebin.com/82Nb6eHp

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Crafttweaker: 2-3.0.24
- ModTweaker: 2.0.10 (Compiled from source)
- MTLib: 1.0.1

**Comment by jaredlll08** [comment]
Log?

**Comment by MrByryndyk** [comment]
Log -http://pastebin.com/nrLpdtU5

**Comment by jaredlll08** [comment]
TConstruct doesn't support oredict, sorry.
