### ISSUE TITLE
Tinkers construct scripts stopped working.

### ISSUE THREAD

**Issue by bluefutureMC** [jaredlll08/ModTweaker#446]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker or ModTweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): http://pastebin.com/cA90uPur

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Crafttweaker: 3.0.24
- ModTweaker: 2.0.11
- MTLib: 1.0.2

#### Your most recent log file where the issue was present: 
https://gist.github.com/bluefutureMC/cc46b3779ef1d2ad0ee85ec2aeac4ea7
[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
The last param was removed, it never worked (atleast for me), so remove: ```<thermalfoundation:storage:4>```
