### ISSUE TITLE
[Suggestion] Change the minimum time to transform via the Pure Daisy

### ISSUE THREAD

**Issue by belathus** [jaredlll08/ModTweaker#447]
#### Issue Description:
Recipes added to the pure daisy should have a default time. The default via Botania's API is 150 (ticks, I assume), but it looks like ModTweaker's default is zero, as the conversion is instant.

#### What happens:
Recipes added to the Pure Daisy happen instantly.

#### What you expected to happen:
Default time of conversion: 150.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://github.com/belathus/Wanderlust-Renewed/blob/master/scripts/botania.zs#L56-L65

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
N/A

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2239
- Crafttweaker: 1.10.2-3.0.24
- ModTweaker: 2.0.10
- MTLib: 1.0.1

#### Your most recent log file where the issue was present: 

N/A

**Comment by jaredlll08** [comment]
So the problem with this is, if someone sets the time to 0, it would default to 150, so it is either add a default time, or make it impossible to have instant conversions.

**Comment by mrlamb** [comment]
Could you have an overload that doesn't take a time parameter? When one is set, keep it, when one isn't set, default it?

**Comment by mahldcat** [comment]
If it would be possible to overload to add a tick count for the time to convert, it would be useful

Here is the use case:

Recipe 1: Cobblestone ->Smooth Stone  (50 ticks)
Recipe 2: Smooth Stone -> (Astral Sorcery) Marble  (300 ticks)
Recipe 3: (Astral Sorcery) Marble -> Living Rock  (500 ticks)

The general scenario would be a skyblock, where I would like a cheap means to produce smooth stone along with astral sorcery marble
