### ISSUE TITLE
Drying Rack Recipes do not show up in JEI

### ISSUE THREAD

**Issue by RiverC** [jaredlll08/ModTweaker#448]
#### Issue Description:
When adding drying recipes, although they work, JEI is not updated to show them.

#### What happens:
Say I add this recipe

`mods.tconstruct.Drying.addRecipe(<biomesoplenty:plant_0:0>, <quark:thatch>, 250);
`
Placing short grass on the drying rack does turn it into thatch, but a player who didn't know this can't check the recipe to find out. 

#### What you expected to happen:

I expect when I press ('u') in JEI while hovering over BoP short grass, I should see a drying recipe for turning short grass into thatch. Note that original drying recipes still work (i.e. drying rotten flesh into monster jerky.)

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

`mods.tconstruct.Drying.addRecipe(<biomesoplenty:plant_0:0>, <quark:thatch>, 250);`

Here is what the log file says to this:

`[SERVER_ABOUT_TO_START][SERVER][INFO] Adding 1 TConstruct Drying Rack Recipe(s) for <quark:thatch>`

This issue is rather simple and has affected multiple versions of modtweaker. I suspect something changed with JEI that may have affected things. Here is the relevant information re: versions:

```
Minecraft 1.10.2
Forge 12.18.3.2185
JEI 3.14.7
modtweaker 2.0.10
crafttweakerjei 1.0.1
```

It may be as simple as changing my JEI version or updating forge. However, it would be nice to have this resolved as soon as is convenient for you. Thanks!

Note, my log (latest.log) is rather long and I didn't find any specific references to modtweaker (such as stack traces or warnings.) If you'd like I can post it, but I think it won't be of much help.

Thanks!

**Comment by jaredlll08** [comment]
MTLib and Crafttweaker versions?

**Comment by RiverC** [comment]
Crafttweaker 3.0.23 (for 1.10.2)
MTLib 1.0.0

**Comment by jaredlll08** [comment]
Update mtlib

**Comment by RiverC** [comment]
I'm now at the latest (1.0.2) and it's still happening.

**Comment by jaredlll08** [comment]
Update to 
https://minecraft.curseforge.com/projects/modtweaker/files/2396271
I thought you were on the latest.

Please update your mods before making an issue.

**Comment by RiverC** [comment]
Thanks! It looks like your last update fixed the issue.
