### ISSUE TITLE
RefinedStorage 'Solderer' recipes not shown in JEI

### ISSUE THREAD

**Issue by PCSpinner** [jaredlll08/ModTweaker#449]
#### Issue Description:
Recipe changes for the Solderer, whether adding new ones or removing old ones, don't register in JEI. The recipe still works as intended (or is removed as intended), players just can't see what the recipe is.
(Same problem as the recent issues with Tinker's Construct)

#### What happens:
recipes aren't shown in JEI

#### What you expected to happen:
recipes to be shown in JEI

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://gist.github.com/PCSpinner/ecb918713ea35fac34f3f614832845ab

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/PCSpinner/5ab5d5ad476c4d83f5062b8065f08aca

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Crafttweaker: 3.0.24
- ModTweaker: 2.0.11
- MTLib: 1.0.2
- Refined Storage: 1.2.24

#### Your most recent log file where the issue was present: 
n/a

**Comment by Claycorp** [comment]
Any progress on this issue? The recipes updating is kinda needed if you are changing them.

**Comment by jaredlll08** [comment]
Well 1.10.2 isn't supported anymore, all my time is now spent on 1.12 and the rare fix for 1.11.2 stuff

**Comment by Claycorp** [comment]
You might want to close all the other 1.10 issues also then. Thanks for the info.
