### ISSUE TITLE
withTag

### ISSUE THREAD

**Issue by MrByryndyk** [jaredlll08/ModTweaker#451]
#### What happens:
I use in the recipes items from different mods indicating their parameters in the tag. The recipe either does not work at all, or the object base without tag parameters is used.
But JEI displays correctly.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/iw5QfK0e - When using vial with any soul, only liquidmobessencezombie is obtained. But JEI displays correctly.
https://pastebin.com/drj6WWS6 - The recipe does not work at all, but it is displayed correctly in JEI
https://pastebin.com/3KRvFrAS - The recipe works correctly. Although the same parameters are used in the tag.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/r9mHdC0E

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Crafttweaker: 3.0.24
- ModTweaker: 2.0.11
- MTLib: 1.0.2

**Comment by jaredlll08** [comment]
read the wiki
http://minetweaker3.powerofbytes.com/wiki/Tutorial:Advanced_Recipes
withtag is for outputs.

**Comment by MrByryndyk** [comment]
Ok. Now I'll try, thanks :)

**Comment by MrByryndyk** [comment]
Could you tell me? How to make that from vial with zombie's soul one liquid was made, and from vial with pig's soul another liquid was made? Whatever I do, I always get only one fluid from different vials.

**Comment by jaredlll08** [comment]
are you running /mt hand on the item that you want? if you are, and are 100% the inputs are correct, then I have no idea

**Comment by MrByryndyk** [comment]
mt hand
 Zombie Soul - <enderio:itemSoulVessel:1>.withTag({isStub: 1 as byte, isVariant: 0 as short, entityId: "Zombie"})
Pig Soul - <enderio:itemSoulVessel:1>.withTag({isStub: 1 as byte, entityId: "Pig"})
Script
`mods.tconstruct.Smeltery.addMelting(<liquid:liquidmobessencezombie> * 200, <enderio:itemSoulVessel:1>.onlyWithTag({isStub: 1 as byte, isVariant: 0 as short, entityId: "Zombie"}), 1000);
mods.tconstruct.Smeltery.addMelting(<liquid:liquidessencepig> * 200, <enderio:itemSoulVessel:1>.onlyWithTag({isStub: 1 as byte, entityId: "Pig"}), 1000);
`
But from any vial I get <liquid: liquidmobessencezombie>

**Comment by jaredlll08** [comment]
Oh, I thought this was in a crafting table, yea AFAIK, the smeltery doesn't
handle nbt items

**Comment by MrByryndyk** [comment]
Clear. With the usual craft I understood how to do it - it works. It is a pity that this does not work for Smeltery. I'll think of something else...
This will not be added in the next version of the mod?

**Comment by jaredlll08** [comment]
Well it is on TIC's side, so nothing I can do, sorry
