### ISSUE TITLE
removeTableRecipe errors on server

### ISSUE THREAD

**Issue by davqvist** [jaredlll08/ModTweaker#453]
#### Issue Description:
Just released my modpack, works on SP without problems, but TC gives an error for removeTableRecipe on a server. The problem was not happening before the latest Modtweaker update and the log shows code from https://github.com/jaredlll08/ModTweaker/commit/8288a2c0948a9d0c613a82d286418e2eb10173ec causes it.

#### What happens:
When trying to remove a Table Recipe, ModTweaker does error out and the script stops

#### What you expected to happen:
That removing a Table Recipe works without errors

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/4VieT9TJ (just the TConstruct file)

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/QL2bdwD9 (line 1351)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 2254
- Crafttweaker: 3.0.24
- ModTweaker: 2.0.11
- MTLib: 1.0.2

#### Your most recent log file where the issue was present: 

see above

**Comment by jaredlll08** [comment]
Do you have JEI on the server?

**Comment by davqvist** [comment]
yes

**Comment by jaredlll08** [comment]
Also are you sure that all the recipes you are removing are valid recipes?

**Comment by davqvist** [comment]
JEI 3.14.7.416
Yes, valid recipes, worked fine before the update on client and server and now only on the client.

**Comment by jaredlll08** [comment]
It seems to be erroring on ```mods.tconstruct.Casting.removeTableRecipe(<ic2:plate:1>);``` can you remove that and try again?

**Comment by KaneHart** [comment]
If you comment them out then other ones break as well.

https://pastebin.com/tytqu4mr

Pretty much all the casting ones seem to error out no matter the mod?

**Comment by bookerthegeek** [comment]
Does the recipe on the server actually output an IC2 plate? That seems odd to me.

What is the table outputting on the server when you cast that metal to the cast?

**Comment by JasonMcRay** [comment]
I personally did couple tests right now and every time you reload the scripts using /mt reload on server the error moves to the next line (with removeTableRecipe) in the script.

Also it looks like even that it errors on one of the lines, that crafting is actually being removed.

For example, it errors on line 37, which is casting of Bronze Plate from IC2. But that casting is getting removed. However line 38, which is casting of Copper Plate from IC2 is not getting removed, because the script erorred on previous line and stopped moving forward.

Can also confirm that this is not issue with just IC2 plates, it also extends to other mods, like Immersive Engineering.

**Comment by bookerthegeek** [comment]
Can you dropbox your mod folder, config folder and script folder for me please.

Or a curse import file would also work.

**Comment by JasonMcRay** [comment]
Me and davqvist are using the same modpack called Age of Engineering available on curse (https://minecraft.curseforge.com/projects/age-of-engineering).

**Comment by bookerthegeek** [comment]
Did you add any custom scripts to the pack?

**Comment by JasonMcRay** [comment]
nope all default

**Comment by bookerthegeek** [comment]
Nevermind, it's your pack, lol.
