### ISSUE TITLE
Getting null when removing Blood Magic Alchemy recipe

### ISSUE THREAD

**Issue by elwooha6** [jaredlll08/ModTweaker#454]
#### Issue Description:
When removing a recipe from Blood Magics Alchemy Table I get an NPE in minetweaker log. No error occurs when adding a new recipe.

#### What happens:
I get an error in chat.

#### What you expected to happen:
Scripts to reload and recipe to be removed.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):  https://pastebin.com/4sR9Q14M

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Crafttweaker: 3.0.24
- ModTweaker: 2.0.11
- MTLib: 1.0.2

#### Your most recent log file where the issue was present: 

https://pastebin.com/dxmieEKY

**Comment by JolyGoodDay** [comment]
same issue, 

reload never works and seems to just add all recipes back and sometimes multiples of your new one if you add it.

Restarting the whole game will load all the changes you made correctly.

**Comment by JolyGoodDay** [comment]
Change to version 2.0.6

**Comment by jaredlll08** [comment]
Want, so does this work perfectly without reloading?

**Comment by JolyGoodDay** [comment]
Latest version as per yesterday has a null error occur when you run "/minetweaker reload". The recipes will load from start up correctly from what I could tell, its just after a reload that messes everything up.

Version 2.0.6 works fine, I tired  this version specifically after consulting a popular mod pack author. 

Please let me know if you need video with explanation, i can make one quickly after I get home. I did not do any extensive tests, and I used the curse launcher.

**Comment by jaredlll08** [comment]
I can help if you are reloading.

**Comment by JolyGoodDay** [comment]
What do you mean?

**Comment by bookerthegeek** [comment]
Can't help.

**Comment by JolyGoodDay** [comment]
ahh

**Comment by jaredlll08** [comment]
I mean, if the error cannot be replicated without running mt reload, then I
won't even try fix it.

**Comment by JolyGoodDay** [comment]
The thing is reload works just fine with older version of mod tweaker.

**Comment by jaredlll08** [comment]
Regardless. If it can't be reproduced without a reload, then I don't
support it.

**Comment by elwooha6** [comment]
How about an answer to the OP, this guy just came along and hijacked my issue.

**Comment by JolyGoodDay** [comment]
Changing from version 2.0.8 to 2.0.9 is where I find the issue to take place. Saying you don't support your own mod is silly. 


Script used:

recipes.remove(<bloodmagic:BlockAltar>);
recipes.addShaped(<bloodmagic:BlockAltar>,
[[<botania:quartzTypeDark:2>,null,<botania:quartzTypeDark:2>],
 [<botania:quartzTypeDark:1>,<botania:rune:1>,<botania:quartzTypeDark:1>],
 [<avaritiaadditions:endest_pearl>,<bloodmagic:ItemMonsterSoul>,<avaritiaadditions:endest_pearl>]]);

Picture after reload 

https://puu.sh/v7r7F/365c83e07f.png

**Comment by bookerthegeek** [comment]
@elwooha6 I'll try to reproduce tonight an see.

@JolyGoodDay Reload has NEVER been supported. IIRC it was added for minetweaker for vanilla recipies only. Even then the only official answer is "/mt reload is not supported for bugs or issues" Dont like it? Then dont use the mod or make your own.
