### ISSUE TITLE
Is this OK?

### ISSUE THREAD

**Issue by bookerthegeek** [jaredlll08/ModTweaker#455]
#### Issue Description:
GitHub Wiki Creation

#### What happens:
As of right now, nothing

#### What you would like to happen:
To be allowed to update the Github Wiki with the Correct formatting for mods:
 - Mods that ModTweaker / CraftTweaker provides integration for.
 - Mods with their own Support for ModTweaker / MineTweaker / CraftTweaker
 - Mods you support that have their own recipe tweaking (i.e. IC2)

Will first just copy straight up off the website, then update as the mod updates. Also this will allow for a single place to easily keep up to date script syntax and formatting.

#### Script used 
Example: https://github.com/jaredlll08/ModTweaker/wiki/Actually-Additions-Support-1.10.2

____
#### Affected Versions 

- Minecraft: 1.10.2

**Comment by yepidoodles** [comment]
Um?

http://minetweaker3.powerofbytes.com/wiki/ModTweaker

**Comment by bookerthegeek** [comment]
Forgot to Close this.
