### ISSUE TITLE
Magical Crops and Botania issue.

### ISSUE THREAD

**Issue by Solarkoid** [jaredlll08/ModTweaker#456]
So when I got into Modtweaker I really liked it :+1: 
But I had this issue with Magical Crops and Botania :(

So what happens is that when I create script with petal apothecary recipe (I have everything correctly done) containing 8 Minicio Essence to create Minicio seed I reload the script and Script Reloaded.
BUT when I try to throw minicio essence it doesnt go in Petal Apothecary ;-;
My friend did it, it worked for him but he said he didnt get the output... 

Script: https://pastebin.com/raw/5StmVLUw

- Minecraft: 1.7.10
- Forge: Forge for 1.7.10 version 1614
- Crafttweaker: latest one
- ModTweaker: latest one
- MTLib: latest one

Sorry if I did this wrongly but I am new on these add link url and stuff :/

**Comment by jaredlll08** [comment]
Please follow the issue template.
