### ISSUE TITLE
Magical Crops, Botania, Modtweaker not working properly

### ISSUE THREAD

**Issue by Solarkoid** [jaredlll08/ModTweaker#457]
Issue Description:
Something with Botania and Magical Crops with Modtweaker integration is not right or is this just a bug?

What happens:
So what happens is that when I create script with petal apothecary recipe (I have everything correctly done) containing 8 Minicio Essence to create Minicio seed I reload the script and Script Reloaded.
BUT when I try to throw minicio essence it doesn't go in Petal Apothecary ;-;
My friend did it, it worked for him but he said he didn't get the output...

What you expected to happen:
I was going to create my modpack little hardcore so this would help me but Minicio essences don't go in Apothecary

Script used:
https://pastebin.com/raw/5StmVLUw
This is what I am using, One with Runic Altar is working.

Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/raw/U2Bsr3mL
This is Minetweaker.log but I don't use old script anymore.
____
Affected Versions:

- Minecraft: 1.7.10
- Forge: 1614 for 1.7.10
- Crafttweaker: 3.0.13
- ModTweaker: 0.9.6
- MTLib: Not Installed

Your most recent log file where the issue was present: 

https://pastebin.com/raw/U2Bsr3mL

Now please tell me if this is ModTweaker/Minetweaker issue. If not I am going to report it to Botania and Magical Crops devs. Thanks.

Solarkoid.
![2017-03-31_00 18 36](https://cloud.githubusercontent.com/assets/26800995/24524471/b54ab996-15a7-11e7-8f9e-c05a40ad1bf2.png)
![2017-03-31_00 18 36](https://cloud.githubusercontent.com/assets/26800995/24524487/c7b0ff82-15a7-11e7-9275-550c5f8132d6.png)

**Comment by jaredlll08** [comment]
1.7.10 is no longer supported.
