### ISSUE TITLE
[1.10.2-2.0.11] Forestry support broken or incorrectly listed on wiki

### ISSUE THREAD

**Issue by SPMoo66** [jaredlll08/ModTweaker#458]
#### Issue Description:
Using the Forestry support listed on the wiki for 1.10.2, recipes do not appear without error, or cause errors within game.

The wiki page also includes capitalized letters for Forestry items, which do not work in scripts, like <Forestry:canWater> or <Forestry:oakStick>

#### What happens:
Nothing, or errors printed in log. Using the command provided in the [wiki](http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Forestry_Support_1.10.2) for adding a recipe to the Thermionic Fabricator (without the capital F for forestry), the following error occurs:
https://pastebin.com/wfPHLfG5

#### What you expected to happen:
Recipes to be added properly.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
`mods.forestry.ThermionicFabricator.addCast(<minecraft:beacon>, [[null, null, null], 
                                                                [null, <minecraft:nether_star>, null], 
                                                                [<minecraft:obsidian>, <minecraft:obsidian>, <minecraft:obsidian>]], 1000, <forestry:waxCast:*>);`

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://bpaste.net/show/49a0442533b8
Relevant lines start at 11377

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2254
- Crafttweaker: 3.0.24
- ModTweaker: 2.0.11
- MTLib: 1.0.1

#### Your most recent log file where the issue was present: 
https://pastebin.com/r20i6aBZ

**Comment by jaredlll08** [comment]
Update MTLib.

**Comment by SPMoo66** [comment]
Updating MTLib fixed the error with the Thermionic Fabricator recipes and now they work, but Carpenter recipes still don't seem to work. There are no errors when I try to register Carpenter recipes, including the one listed on the wiki.

`mods.forestry.Carpenter.addRecipe(<minecraft:diamond> * 2, [[null, <minecraft:planks>, null],[<minecraft:planks>, null, <minecraft:planks>], [null, <minecraft:planks>, null]], <liquid:seed.oil> * 100, 20, <minecraft:log>);`

I replaced the oakStick with a diamond just to make it a little easier to find.

After testing with the other Forestry machines:
Adding recipes for the Centrifuge, Thermionic Fabricator, Still, and Fermenter all seem to work.
Adding recipes for the Moistener, Squeezer, and Carpenter doesn't seem to work.

**Comment by bookerthegeek** [comment]
@SPMoo66 The [Wiki](http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Forestry_Support_1.10.2) has been updated. Their might still currently be an issue where the removed recipies still show up in JEI or the new ones not showing up. But they all do work.

@jaredlll08 Issue can be closed for the Wiki on this one. I'll start a new one about visibility of recipes.

**Comment by jaredlll08** [comment]
1.10.2 isn't supported anymore / Issue has been fixed in 1.12
