### ISSUE TITLE
Request for IMC abilities

### ISSUE THREAD

**Issue by bookerthegeek** [jaredlll08/ModTweaker#459]
#### Issue Description:
An inability to send Inter-Mod Communication (IMC) to other mods to change recipes or game aspects.

#### What happens:
Nothing, That is the issue.

#### What you ~~expected~~ would like to happen:
An ability to create a file using the existing ZenScript formating to send IMC to other mods
Maybe change the extension from `something.zs` to `something.imc`

#### Some Links
- https://github.com/Lunatrius/DynIMC
- http://teamcofh.com/docs/thermal-expansion/other/inter-mod-communication/

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2

**Comment by jaredlll08** [comment]
So this doesn't really fit into Crt well, since it would be running sooner than Crt and it wouldn't be using Zenscript. But I may put it in a separate mod

**Comment by bookerthegeek** [comment]
However it is done, as a lot of mods seem to support imc messages, would be fine.

**Comment by bookerthegeek** [comment]
Question, would it be possible to still format it as Zenscript, but then convert to IMC when passing to the other mods? This would cut down on the need for pack authors to larn a new way of formating recipes. Or would it be better (Easier I am sure) to just pass IMC?

I know it took me a while to wrap my head around IMC, many multiple of times longer than Zenscript. That being said I would rather have something than wait for better.

**Comment by bookerthegeek** [comment]
Another mod going the IMC route... [TinkersConstruct](https://github.com/SlimeKnights/TinkersConstruct/wiki/IMC)

**Comment by bookerthegeek** [comment]
Just in case anybody is looking for options for IMC: https://github.com/Lunatrius/DynIMC/issues/2
