### ISSUE TITLE
Scripts not working on server

### ISSUE THREAD

**Issue by checkium** [jaredlll08/ModTweaker#462]
#### Issue Description:
The script loads correctly but the craftings doesn't work. I already tried /root/scripts/ and /root/world/scripts/.

#### What happens:
Everything loads correctly but the craftings doesn't work

#### What you expected to happen:
That everything worked since all seems fine.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
macerator.zs: https://pastebin.com/XWqMjM3h
melting.zs: https://pastebin.com/tiAeWiZQ
oredict.zs: https://pastebin.com/3LC6kV8D
tiny.zs: https://pastebin.com/uxZ5F2iU

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/bL1ThfUG
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Crafttweaker: 3.0.24
- ModTweaker: 2.0.11
- MTLib: 1.0.2

#### Your most recent log file where the issue was present: 
https://gist.githubusercontent.com/checkium/e00da9142651499107cd35508525907b/raw/fb926b514a97849e9712f4d52911e6617712426c/gistfile1.txt
[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
Does the client have the scripts?

**Comment by checkium** [comment]
@jaredlll08 I'm not sure, I think yes but outdated. 

EDIT: I checked and not even craftings that the client also haves work.

**Comment by jaredlll08** [comment]
Make sure the client and server scripts are exactly the same.

**Comment by checkium** [comment]
@jaredlll08 Didn't work. Also, I should state that I'm trying with ic2 macerator (macerator.zs file)

**Comment by jaredlll08** [comment]
Wrong mod repo. 
IC2 doesn't have JEI support. Edit the recipes manually with ic2
