### ISSUE TITLE
[Suggestion] Add Draconic Evolution support

### ISSUE THREAD

**Issue by joserobjr** [jaredlll08/ModTweaker#463]
Draconic Evolution has a custom crafting method named fusion crafting.

Can you add support add or remove recipes?

It has an API and seems to be easy to use:
https://github.com/brandon3055/Draconic-Evolution/tree/master/src/main/java/com/brandon3055/draconicevolution/api/fusioncrafting

**Comment by jaredlll08** [comment]
No.

**Comment by bookerthegeek** [comment]
@joserobjr DE has there own built in eay to change recipies.

**Comment by darkhax** [comment]
Since Jared is being a butt face, I can make DraconicTweaker if you want ;p

**Comment by jaredlll08** [comment]
@darkhax I will break up with you.

**Comment by bookerthegeek** [comment]
:popcorn:

**Comment by darkhax** [comment]
That's a chance I am willing to take... https://github.com/Darkhax-Minecraft/DraconicTweaker

**Comment by jaredlll08** [comment]
http://i.blamejared.com/yvbKx.png

**Comment by darkhax** [comment]
Love you babe <3

**Comment by Eufranio** [comment]
wtf
