### ISSUE TITLE
Modtweaker tinker smeltery fuel section not working property

### ISSUE THREAD

**Issue by bigrice1018** [jaredlll08/ModTweaker#465]
#### Issue Description:
I am a modpack author and try to use modtweaker to add custom fuel for tconstruct
But the result is showing the error below (#### Minetweaker.log file)

#### What happens:
Modtweaker Tinker Construct smeltery add & remove fuel not working property
Can't remove fuel with no error.
Can't add fuel with error below. (#### Minetweaker.log file)

#### What you expected to happen:
mods.tconstruct.Smeltery.removeFuel(<liquid:lava>);
Successfully add and remove fuel 

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
mods.tconstruct.Smeltery.addFuel(<liquid:iron>,100,100); 

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
ERROR: test.zs:2 > a method available but §4none§r matches the parameters (minetweaker.liquid.ILiquidStack, int, int)\nThis is §ousually§r an error in your script, not in the mod\naddFuel(§rZenTypeNative )

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Crafttweaker: 3.0.24
- ModTweaker: 2.0.11
- MTLib: 1.0.2
- Tconstruct: 2.6.3

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
Removal of fuel is only the fuel, like
```
mods.tconstruct.Smeltery.removeFueld(<liquidhere>);
```

**Comment by bigrice1018** [comment]
adding fuel is not working property also...

**Comment by jaredlll08** [comment]
Well how was I meant to know that?
You didn't provide proper logs posted to pastebin, how am I meant to fix an error that I didn't even know existed?!

**Comment by bigrice1018** [comment]
First, i am really thankful that modtweaker is bring back by you
I give all the information in #What happen tab
In the logs section, i provide the only error show in the logs

Here is the full minetweaker log
https://pastebin.com/Bj0tvVDn
