### ISSUE TITLE
Blood Magic recipes removed from game but still appears in JEI

### ISSUE THREAD

**Issue by Lgk2** [jaredlll08/ModTweaker#467]
#### Issue Description:

https://github.com/jaredlll08/ModTweaker/issues/460
This is probably the same issue.

#### What happens:

The recipe is removed but still shows up in JEI. The new recipe works and you can see it in JEI.

#### What you expected to happen:

The recipe is removed and does not show up in JEI. The new recipe works and you can see it in JEI.

#### Script used
https://gist.github.com/Lgk2/435e657d92c0a169ec1f50dd279e5e05

#### Minetweaker.log file
https://gist.github.com/Lgk2/7fd71c5138ead181fd7cd4a4bdc2c99d

#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Crafttweaker: 1.10.2-3.0.24
- ModTweaker: 2-2.0.11
- BloodMagic: 1.10.2-2.1.9-78
- MTLib: 1.0.2

**Comment by jaredlll08** [comment]
MTLib version?

**Comment by Lgk2** [comment]
MTLib-1.0.2

**Comment by wizard1399** [comment]
Ran into a simailar issue with the alchemy table as well.

**Comment by Dilnu** [comment]
I'm also seeing this with the hellfire forge.
