### ISSUE TITLE
ProjectE integration

### ISSUE THREAD

**Issue by NicosaurusRex99** [jaredlll08/ModTweaker#469]
#### Issue Description:
Note: When changing scripts projecte doesnt automatically update EMC to support the new recipe
#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue): recipes.remove(stuffz);
recipes.addShapeless(stuffz, [bit more stuffz]);

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): https://pastebin.com/R1jGYTVK

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge:12.18.3.2272
- Crafttweaker: 1.10.2.3.0.24
- ModTweaker:2.0.11
- MTLib:1.0.2
- ProjectE:1.10.2PE1.2.0

#### Your most recent log file where the issue was present: 

http://cryptb.in/Me3q

**Comment by jaredlll08** [comment]
I don't add projectE support, go speak to them.

**Comment by NicosaurusRex99** [comment]
alright

**Comment by NicosaurusRex99** [comment]
https://github.com/sinkillerj/ProjectE/issues/1497
