### ISSUE TITLE
No Blast Furnace reciepe

### ISSUE THREAD

**Issue by Twonkk** [jaredlll08/ModTweaker#472]
#### Issue Description:
No other mod packs installed, just Railcraft, and there appears to be no blast furnace... can't find anything in the config files that would turn it on or off. no issues in log file.

#### What happens:
When using crafting table, putting Soul Sand, Netherbrick and Magma Cream in, there is no output.

#### What you expected to happen:
in all honesty, i expected the above to work?

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2281
- Crafttweaker: 
- ModTweaker:
- MTLib:

#### Your most recent log file where the issue was present: 

https://pastebin.com/RmRPBj76

**Comment by jaredlll08** [comment]
We do not add railcraft support in 1.10.2.
Also it would be pretty hard to JUST have Modtweaker and Railcraft considering that Modtweaker depends on MTLib and Crafttweaker

**Comment by bookerthegeek** [comment]
As of the last time i checked, railcraft had not implemented any machines in the 1.10 branch.
