### ISSUE TITLE
[1.10.2] Adding Chisel Variation to an existing group some how removes the group.

### ISSUE THREAD

**Issue by KaneHart** [jaredlll08/ModTweaker#474]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker or ModTweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:
Removes Chisel Group.

#### What you expected to happen:
It add the Block to the current Marble Chisel Group. 

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
```
mods.chisel.Groups.addVariation("basalt", <railcraft:generic:8>);
mods.chisel.Groups.addVariation("marble", <railcraft:generic:9>);
```

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
```
[SERVER_STARTED][SERVER][ERROR] Cannot find group basalt
[SERVER_STARTING][SERVER][ERROR] Cannot find group marble
```

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 2281
- Crafttweaker: 3.0.24
- ModTweaker: 2.0.11
- MTLib: 1.0.2

#### Your most recent log file where the issue was present: 

really have no logs outside what was shown.

**Comment by jaredlll08** [comment]
Explanation?

**Comment by KaneHart** [comment]
Not much to explain my 78 year old mother could explain it with more words but simple as adding material to chisel causes it to remove that group or at least to the log files.

**Comment by jaredlll08** [comment]
This is a chisel issue, I have told @tterrag1098 about it.
