### ISSUE TITLE
Tinkers' Construct addMelting not working

### ISSUE THREAD

**Issue by yepidoodles** [jaredlll08/ModTweaker#475]
#### Issue Description:

I'm trying to add armours to the smeltery to smelt back into their raw materials, but ModTweaker does not recognise the addMelting argument, despite the [wiki saying it is in this version](http://minetweaker3.powerofbytes.com/wiki/ModTweaker:TConstruct_Support_1.10.2) . When I do `/mt tconstruct Smeltery` it only lists Alloys, drying and casting.

#### Script used:

`mods.tconstruct.Smeltery.addMelting(<liquid:iron> * 1152, <minecraft:iron_chestplate>, 200, <minecraft:iron_block>);`

#### Minetweaker.log:

https://pastebin.com/uLiXaVSS

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Crafttweaker: 3.0.24
- ModTweaker: 2.0.11
- MTLib: 1.0.2

#### Your most recent log file where the issue was present: 

Relevant section:
https://pastebin.com/zJZeT6BY

Any help is appreciated, thank you

**Comment by jaredlll08** [comment]
Remove the last param(being the block) (Read the error, it tells you what it needs / what is missing)

**Comment by yepidoodles** [comment]
So you can't add a block to render at all?

**Comment by jaredlll08** [comment]
As of right now, no.

**Comment by yepidoodles** [comment]
You may want to remove it from the Wiki to avoid further confusion.
