### ISSUE TITLE
[Request] Railcraft support in 1.10.2

### ISSUE THREAD

**Issue by Skillotic0703** [jaredlll08/ModTweaker#478]
Can you add support for railcraft rolling machine/manual rolling machine in 1.10.2 please?

**Comment by CovertJaguar** [comment]
The only recipe api that changed between 1.7 and 1.10 is the rock crusher api.

**Comment by jaredlll08** [comment]
I'll take a look at it this weekend, will probably end up rewriting the
support anyway, thanks for the heads up though!

**Comment by jaredlll08** [comment]
1.10.2 isn't supported anymore / Issue has been fixed in 1.12

**Comment by Skillotic0703** [comment]
Does that mean that Railcraft will be supported in 1.12?

**Comment by jaredlll08** [comment]
what it means is that RailCraft isn't on 1.12, so when it is, ask again (closing old issues)
