### ISSUE TITLE
[Request/Question] transformDamage with Botania

### ISSUE THREAD

**Issue by Towsty** [jaredlll08/ModTweaker#479]
Is it possible to use/add the transformDamage() with something like the Botania runic altar?

i.e.
mods.botania.RuneAltar.addRecipe(essPrudentium, [essInferium, essInferium, essInferium, essInferium, **<mysticalagriculture:infusion_crystal>.transformDamage(2)**], 100);

1.10.2
Forge 12.18.3.2281
Modtweaker 2.0.11

**Comment by jaredlll08** [comment]
not possible.
