### ISSUE TITLE
[1.10.2] Changing harvest level of TiC doesn't work 

### ISSUE THREAD

**Issue by SirWindfield** [jaredlll08/ModTweaker#480]
#### What happens:
Tryint to change the `harvestLevelHead` for TConstruct throws an Error.

#### What you expected to happen:
It should change the harvest level.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/sr6ba9AT

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/Dqdy1g9g

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2281
- Crafttweaker: 3.0.24
- ModTweaker: 2.0.11
- MTLib: 1.0.2

**Comment by jaredlll08** [comment]
You're syntax is wrong, it needs to be
```
<material:materialName>.xyz
```
like
```
<material:stone>.harvestLevelHead = v_stone;
```

**Comment by SirWindfield** [comment]
Shouldn't it work with the ore dictionary too? Because I tried that one too. Sorry, I missed that D:
`<ore:ingotIron>.harvestLevelHead`?

**Comment by jaredlll08** [comment]
Nope. What I showed you is how it works.

**Comment by SirWindfield** [comment]
Thanks! Just throwing in the last question I had (don't want to open another issue for it). Is it possible to tweak the mining level of block? Something like `<ore:oreCopper>.harvestLevel = 5`?

**Comment by jaredlll08** [comment]
Nope, not possible

**Comment by SirWindfield** [comment]
Any plans on adding? Shouldn't be hard to implement, `MinecraftForge.setHardnessLevel` should work out I guess. Might aswell create a PR if you are interested in that feature.
