### ISSUE TITLE
Botania

### ISSUE THREAD

**Issue by LokyLive** [jaredlll08/ModTweaker#483]
Hey , 

I'm trying to add some recipe to Elven Trade from Botania so first thing i tryed the wiki exemple:

mods.botania.ElvenTrade.addRecipe(<botania:flower:4>, [<minecraft:yellow_flower>]);

and it doesn't work xD

Minecraft 1.10.2
Modtweaker  2-2.0.12
Botania r1.9-341

Did i made a mistake ( i've corrected caps in the exemple)  ?

**Comment by jaredlll08** [comment]
Follow the issue template.

**Comment by jaredlll08** [comment]
Follow the issue template.
