### ISSUE TITLE
Botania ElvenTrade

### ISSUE THREAD

**Issue by LokyLive** [jaredlll08/ModTweaker#484]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker or ModTweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:
Hey ,

I'm trying to add some recipe to Elven Trade from Botania so first thing i tryed the wiki exemple:

mods.botania.ElvenTrade.addRecipe(botania:flower:4, [minecraft:yellow_flower]);

and it doesn't work xD

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/JQz0VtF8

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

I can't pastebin all the file he is too bigger xD

https://pastebin.com/Qye9k43K

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.10.2
- Forge:12.18.3.2281
- Crafttweaker: 1.10.2-3.0.25
- ModTweaker:2-2.0.12
- MTLib:1.0.2

**Comment by jaredlll08** [comment]
the first argument is an array
```
mods.botania.ElvenTrade.addRecipe([<botania:flower:4>], [minecraft:yellow_flower]);
```
