### ISSUE TITLE
Huge problem with ModTweaker and Chisel (1.10)

### ISSUE THREAD

**Issue by Dakotaraptor** [jaredlll08/ModTweaker#486]
#### Issue Description:
So whenever I try to add tweaks related to Chisel I get a major problem. It happened both a couple of months ago with earlier versions of everything an entirely different modtweaker script, and now. I apologize if this is formatted improperly, this is my first time submitting a GitHub issue, and I'm doing my best.

#### What happens:

The first time you load a world it works great (proof: [](https://pasteboard.co/cnPGIJPWu.png) . However, after exiting a world and either reopening it or opening another, minecraft freezes on this screen [(](https://pasteboard.co/cnVdz9fQQ.png) . I've tried waiting for hours, it never gets past it, and the only way I've found to exit Minecraft when that happens is to close it through the task manager. No crashlog is created when this happens. I know its ModTweaker causing the crash because when I remove the script, the worlds load as normal.

#### What you expected to happen:
To not have to restart Minecraft anytime I want to switch to another save

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
[https://pastebin.com/Zpjf7SVE](url)

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
Unfortunately, a log file never even generates for this issue, or if it does I can't find it.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2239
- Crafttweaker: 1.10.2-3.0.24
- ModTweaker: 2-2.0.12
- MTLib: 1.0.2

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
I need the forge log or I can't help

**Comment by Dakotaraptor** [comment]
Do you mean the crash report? Because I replicated the crash, and no crash log has generated in the crash report folder again

**Comment by jaredlll08** [comment]
the forge log, not the crash log.
also the minetweaker.log please

**Comment by Dakotaraptor** [comment]
Are these what you are looking for? ([https://gist.github.com/Dakotaraptor/9c14c8c08962b33b20c6cdc9b9fe7cc2](url) ) Also, thanks for your paitence, I know my lack of knowledge must be frustrating

**Comment by jaredlll08** [comment]
This is a problem with chisel, I have made an issue about it already.
https://github.com/Chisel-Team/Chisel/issues/443
