### ISSUE TITLE
[Request] Add support for Orechid Ignem from Botania

### ISSUE THREAD

**Issue by Xavion3** [jaredlll08/ModTweaker#487]
The Orechid Ignem is a seperate version of the Orechid designed to provide nether ores instead, API wise it should function identically to current Orechid support only using the `addOreWeightNether` function instead of `addOreWeight`. Usage example in Botania API can be seen [here](https://github.com/Vazkii/Botania/blob/1.10-final/src/main/java/vazkii/botania/api/BotaniaAPI.java#L194).

**Comment by jaredlll08** [comment]
1.10.2 isn't supported anymore / Issue has been fixed in 1.12 (last I checked, botania isn't 1.12)
