### ISSUE TITLE
[Request] Expand ActuallyAdditions support.

### ISSUE THREAD

**Issue by tofof** [jaredlll08/ModTweaker#488]
#### Issue Description:
The [ActuallyAdditions API](https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/api/ActuallyAdditionsAPI.java) provides access to several features that Modtweaker doesn't currently support.

#### What happens:
Modtweaker supports AtomicReconstructor, Coffee, Compost, Crusher, Empowerer.

#### What you expected to happen:
Modtweaker also supports [Mining Lens](https://github.com/Ellpeck/ActuallyAdditions/blob/52e87f850903dc369cf9df9a8642f5c46afd1b57/src/main/java/de/ellpeck/actuallyadditions/api/ActuallyAdditionsAPI.java#L95-L115) and [Color Lens](https://github.com/Ellpeck/ActuallyAdditions/blob/52e87f850903dc369cf9df9a8642f5c46afd1b57/src/main/java/de/ellpeck/actuallyadditions/api/ActuallyAdditionsAPI.java#L210-L230) recipes, specifying [Oils](https://github.com/Ellpeck/ActuallyAdditions/blob/52e87f850903dc369cf9df9a8642f5c46afd1b57/src/main/java/de/ellpeck/actuallyadditions/api/ActuallyAdditionsAPI.java#L144-L152) for the generator (and changing the [four hardcoded oils](https://github.com/Ellpeck/ActuallyAdditions/blob/52e87f850903dc369cf9df9a8642f5c46afd1b57/src/main/java/de/ellpeck/actuallyadditions/mod/crafting/InitCrafting.java#L36-L39)), and adding/removing [Treasure/Hairball](https://github.com/Ellpeck/ActuallyAdditions/blob/52e87f850903dc369cf9df9a8642f5c46afd1b57/src/main/java/de/ellpeck/actuallyadditions/api/ActuallyAdditionsAPI.java#L166-L190) loot.
____
#### Affected Versions (Do *not* use "latest"):

- ModTweaker: 2.0.12
- ActuallyAdditions: 1.10.2-r105

**Comment by ElvenChaos** [comment]
In addition, it would be nice to be able to use Ore Dict inputs for recipes, though after a quick look at the API it may require some changes on AA's end.

**Comment by jaredlll08** [comment]
Color lens and coffee aren't possible due to how they are coded
