### ISSUE TITLE
[1.11.2] JEI Problems

### ISSUE THREAD

**Issue by EmosewaGamer** [jaredlll08/ModTweaker#491]
It seems that there is a problem with modded recipes being changed in JEI on the 1.11.2 version.

 Whenever I change a modded recipe (AA Atomic Reconstructor for example), the recipe changes, but it doesn't show up in JEI and gives the error:
minetweaker.api.compat.IJEIRecipeRegistry.addRecipe(Ljava/lang/Object;Ljava/lang/String;)V

**Comment by jaredlll08** [comment]
use the template.

**Comment by EmosewaGamer** [comment]
... I am. I even tried out only the one you had as an example on the wiki and it still happened. It doesn't show the error when I load up a world, but it still doesn't show the recipes in JEI. I get the error when I do /mt reload.

**Comment by jaredlll08** [comment]
I meant the github issue template -_-

**Comment by EmosewaGamer** [comment]
Oh, sorry.

**Comment by EmosewaGamer** [comment]
Ok, I updated it.

**Comment by jaredlll08** [comment]
that isn't the minetweaker.log.

**Comment by EmosewaGamer** [comment]
I always tend to shorten down logs, but this isn't a regular log, so I have no idea why I even did that. Now it's the full log

**Comment by jaredlll08** [comment]
full forge log please

**Comment by EmosewaGamer** [comment]
It's a huge mod pack, so that's why I said I usually shorten them.

**Comment by jaredlll08** [comment]
I need the full log, use gist.github.com if it is too big for pastebin.
Trust me, I have seen a bigger log.

**Comment by EmosewaGamer** [comment]
https://gist.github.com/EmosewaGamer/118ae0a6cce3f2c8f1e234b0dd7f2338
Are you sure?

**Comment by jaredlll08** [comment]
Can you take a screenshot of your mod folder and show it to me?

**Comment by EmosewaGamer** [comment]
Did I send the wrong log?

**Comment by jaredlll08** [comment]
The log didn't have the info I'm looking for,
So could I please get a screenshot of the mods folder?
Also is this SP or MP?

**Comment by EmosewaGamer** [comment]
Ok I have the correct one now: https://gist.github.com/EmosewaGamer/44278f8e428055bf9df75a3424e241a1The copying cut off, so that's why it starts there.

![image](https://user-images.githubusercontent.com/25333164/27082435-feafbdfc-5044-11e7-93a9-e2f204f04ef1.png)

It's singleplayer.

**Comment by jaredlll08** [comment]
ok, last thing, can you upload your Crafttweaker jar file, MTLib jar file and modtweaker jar file somewhere for me to download.

This is a very weird issue, the only explanation I can think of is a corrupt jar...

**Comment by EmosewaGamer** [comment]
Should I try reinstalling them?

**Comment by jaredlll08** [comment]
You can try, but the jar from curse may be messed, which reinstalling wouldn't fix

**Comment by EmosewaGamer** [comment]
Oh, that's another problem. I believe I have an idea to how to send it.

**Comment by EmosewaGamer** [comment]
https://cdn.discordapp.com/attachments/305377312747159554/324167529729753089/CraftTweaker-1.11.2-3.0.25.jar
https://cdn.discordapp.com/attachments/305377312747159554/324167528056356865/modtweaker-3.0.1.jar
https://cdn.discordapp.com/attachments/305377312747159554/324167512805867521/MTLib-2.0.3.jar

**Comment by jaredlll08** [comment]
Mind trying this version?
http://i.blamejared.com/CraftTweaker-1.11.2-3.0.26.jar

**Comment by EmosewaGamer** [comment]
It works! ^^
Will this be officially released soon?

**Comment by jaredlll08** [comment]
yip, next hour
