### ISSUE TITLE
[1.10.2]Petal Apothecary does not accept custom input items.

### ISSUE THREAD

**Issue by SOL3675** [jaredlll08/ModTweaker#494]
#### Issue Description:
I added custom petal apothecary recipes, but it doesn't accept custom input item. It accept only default recipes' input.

#### What happens:
No error with Minetweaker.log and JEI correctly shows those recipes.
http://i.imgur.com/FnzAJcY.png
http://i.imgur.com/XxhSO10.png

#### What you expected to happen:
Petal Apothecary accept the custom input items.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/uZLECyXe

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/1YxatCGV
Whole Log
https://pastebin.com/ysw9CESt

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2297
- Crafttweaker: 3.0.26
- ModTweaker: 2.0.12
- MTLib: 1.0.3

#### Your most recent log file where the issue was present: 

https://pastebin.com/010i4Q1k

**Comment by jaredlll08** [comment]
As the name implies... The petal apothecary only accepts petals, nothing I can do to change that sorry

**Comment by SOL3675** [comment]
Ahh... Okay. So, Botania code is slightly changed from version 1.7.10.
Unfortunately, the wiki description is wrong.
http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Botania_Support_1.10.2
`//Petal Apothecary - Everything is a valid input item except seeds that complete the crafting process`
I'm not familiar with editing the wiki, but if I can, I should fix the description.
