### ISSUE TITLE
Trouble with removeMelting

### ISSUE THREAD

**Issue by 3DLudi** [jaredlll08/ModTweaker#495]
#### Issue Description:
Personal mod pack and I am OCD about similar ores from different mods.  Currently I am trying to consolidate Immersive Engineering and COFH metals in the Tinkers Smeltery.  Both mods contain ingots/ nuggets/ etc for copper, aluminum, silver, lead, and nickel.  It seems removeMelting does not do anything but I am having trouble figuring out why.  No error.  Just does not work.

#### What happens:
Script:
mods.tconstruct.Smeltery.removeMelting( <<immersiveengineering:storage:0>> );

Note: <immersiveengineering:storage:0> = Immersive Engineering copper block

1> Right click Thermal Foundation copper block for uses in JEI.
2> Switch tab to Tinkers Smelting
This tab shows the Immersive Engineering copper block melting in the smeltery for 1296mb liquid copper @ 542 deg.

#### What you expected to happen:
To have the Immersive Engineering copper block removed from the smeltery

#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2316
- Crafttweaker: 3.0.26
- ModTweaker: 2.0.11, 2.0.12, 2.0.13 (did not test lower than 2.0.11)
- MTLib: 1.0.3
- COFH Core: 4.1.8.12
- CodeChickenLib - 2.5.9.267
- ImmersiveEngineering: 0.10-61
- JEI: 3.14.7.419
- Mantle: 1.1.5
- TConstruct: 2.6.5
- ThermalFoundation: 2.1.3.5

If some combination of Crafttweaker/ ModTweaker/ MTLib works as expected I would be happy to switch.

**Comment by bookerthegeek** [comment]
Minetweaker Log, and a picture of the Copper Block in question heating up to melt in the smeltery please.

**Comment by 3DLudi** [comment]
Log
https://pastebin.com/kPkFxCrQ

Image
https://imagebin.ca/v/3RX9S2CHE0yE

**Comment by 3DLudi** [comment]
Argh!  Sigh...
You can close this issue if you like.  It is becoming apparent that attempting to consolidate all of the ores from IE and COFH is simply too time consuming.  I have more than one whole page of script just for copper!  So I have decided that IE has got to go :(

**Comment by bookerthegeek** [comment]
Have you tried UniDict? There is another one also of the similar name, it is under ic2 addons on curse, but not dependant on IC2.

**Comment by bookerthegeek** [comment]
Also, a copy of the script please.

**Comment by 3DLudi** [comment]
Script (it is in the original post also)
https://pastebin.com/VtrcLx7c

I have not yet tried UniDict no.  I am assuming it would be too complicate to automate with a mod.  Just as an example copper ingots (all kinds) work in IE Arc Reactor but it makes IE copper dust.  I am doubtful UniDict would change it to make TE copper dust instead.  Could be wrong.  Will look at it... Thanks

**Comment by jaredlll08** [comment]
Are you sure you're smelting the correct block? Lats I checked, copper wasn't blue...

**Comment by 3DLudi** [comment]
LOL...
I couldn't agree more.  Blame Immersive Engineering.
https://imagebin.ca/v/3RZ21G2fVB4a

**Comment by jaredlll08** [comment]
Can you give me the /mt hand output of the block please

**Comment by 3DLudi** [comment]
<<immersiveengineering:storage>>
Is in <<ore:blockCopper>>

**Comment by 3DLudi** [comment]
UniDict is a beast !
Still needs some cleaning up in JEI (and a few machine recipes) but this is a much better starting point than scratch.  Just to note: It looks like UniDict cleaned up the original issue also.  JEI only shows TE copper block for smeltery and it looks like IE copper block does not work anymore.

**Comment by bookerthegeek** [comment]
Yeah, i am doing the same thing in my pack, and that mod has taken my unification script from i er 4k lines down to under 1k.

**Comment by 3DLudi** [comment]
Just finished copper @ 50 lines =)

JEI looks great without all the oredict entries for the ores/ingots etc that you cant get -- because I disabled them hah.  Only glitchyness now is with the Thermal machines.  I am guessing they look at the oredict and then save it internally (dang you mr lemming!).

Any chance we could get a reload() command for COFH that would have them rescan the oredict? =)

**Comment by bookerthegeek** [comment]
Sadly right now no. COFH uses imc which at the moment unless you can make your own mod to send them you are out of luck.

I got around that issue by just serting everything to the COFH output myself.

**Comment by 3DLudi** [comment]
>> I got around that issue by just serting everything to the COFH output myself.

Umm huh? (LOL).  I guess I do not know what that is or how to do it.  Got a tut or something I could look at?  If I would need to make my own mod then NM; not a coder... =)

**Comment by bookerthegeek** [comment]
Easy. Set your scripts aside, and launch the game. See what the output for each ore is in the thermal foundation machines is, and make it so all other mods output the same.

**Comment by bookerthegeek** [comment]
Look in the unidict configs about leaving one type

**Comment by 3DLudi** [comment]
Found it =) and it worked woo.
That cut down my config file by about a quarter.  And it worked better.
One ingot to rule them all (muahah).  Thanks so much for the tips!  Its perfect now.  Every machine I have tested only has the material I want -- and only one entry.  Makes me all emo inside.

**Comment by bookerthegeek** [comment]
Male sure you either modify the loot tables to remove other ingots, or add a shapless recipe to convert them, or a way to grind them into dust.

And ypur welcome.

**Comment by jaredlll08** [comment]
1.10.2 isn't supported anymore / Issue has been fixed in 1.12
