### ISSUE TITLE
Please add Lumbermill support for wood from other mods

### ISSUE THREAD

**Issue by lex1975** [jaredlll08/ModTweaker#496]
https://github.com/ForestryMC/Binnie/issues/62
https://github.com/jaredlll08/CraftTweaker/issues/239

**Comment by jaredlll08** [comment]
Calm down.

**Comment by jaredlll08** [comment]
I don't even know what mod you are talking about.

If you want the support. make a proper issue.

**Comment by lex1975** [comment]
Please add Lumbermill support for wood from other mods - that is Crafttweaker (Modtweaker) support.
Lumbermill - is a wood processor from the Binnie mod (sub-mod Forestry https://github.com/ForestryMC/Binnie). Uses RF energy and water for work. I want to be able to configure the device's input and output manually using a script, like other mechanisms, Forestry mod.

**Comment by bookerthegeek** [comment]
@lex1975

I believe you are asking for Binnies mod (extra trees) machine support to be added, is this right? If so...

- Have you contacted Binnie and asked him to add support?
- Does the mod already have a way to do this natively?
- What minecraft version are you wanting this for?
