### ISSUE TITLE
Chisel Variation Changes don't show up in JEI.

### ISSUE THREAD

**Issue by Dilnu** [jaredlll08/ModTweaker#497]
#### Issue Description:
Chisel Variation Changes don't show up in JEI.

#### Script used:
mods.chisel.Groups.addVariation("stonebrick", <extrautils2:decorativesolid:2>);

#### Logs and script files:
https://gist.github.com/Dilnu/72714f410158ba2fb34b0c82fa411646
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2297
- Crafttweaker: 3.0.26
- ModTweaker: 2.0.13
- MTLib: 1.0.3
- Chisel: 0.0.11.26
- ConnectedTexturesMod: 0.1.1.16
- JEI: 3.14.7.420
- Extra Utilities: 1.4.4

**Comment by jaredlll08** [comment]
Nothing I can do, chisel is weird with their JEI integration
