### ISSUE TITLE
Forestry machine recipes not updating for JEI

### ISSUE THREAD

**Issue by Towsty** [jaredlll08/ModTweaker#498]
#### Issue Description:
Forestry changes do not show up in JEI. I know this has been reported in some way in the past but it looked like most of those issues have been fixed in other versions. However, the issue seems to either be different or persist.

#### What happens:
Clicking on or using 'R' on blocks in JEI with recipes added to forestry machines show no recipe with forestry machines or no recipe at all if the initial crafting recipe has been removed.

#### What you expected to happen:
Adding a recipe such as:
```
Carpenter.addRecipe(<refinedstorage:controller>, [[<mekanism:reinforcedalloy>, <storagenetwork:request>, <mekanism:reinforcedalloy>], [<ore:itemSilicon>, <refinedstorage:machine_casing>, <ore:itemSilicon>], [<ore:dropRoyalJelly>, <ore:itemSilicon>, <ore:dropRoyalJelly>]], 2400, <liquid:sulfuricacid> * 4000);
```
...works fine however JEI does not reflect the changes.
Carpenter GUI (showing changes worked):
![image](https://user-images.githubusercontent.com/5897643/27806052-f544b542-5ffd-11e7-9b65-9f451f8ffd25.png)

Clicking on item in JEI or using R for recipe (keybind is set) does not find a recipe for the block at all. 

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://hastebin.com/xehemamape.xml

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://gist.github.com/Towsty/5753a7e434cdcfe9dd1e403f402f1064 **or** 
[minetweaker.txt](https://github.com/jaredlll08/ModTweaker/files/1120438/minetweaker.txt)
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: 13.20.1.2388
- Crafttweaker: 3.0.26
- ModTweaker: 3.0.1
- MTLib: 2.0.3

#### Your most recent log file where the issue was present: 

[fml-client-latest.txt](https://github.com/jaredlll08/ModTweaker/files/1120444/fml-client-latest.txt)

**Comment by jaredlll08** [comment]
1.11.2 isn't supported anymore / Issue has been fixed in 1.12
