### ISSUE TITLE
[Request][1.10.2] Add Immersive Engineering, Futurepack, Earthworks support

### ISSUE THREAD

**Issue by dragonshardz** [jaredlll08/ModTweaker#501]
Exactly what it says on the tin. I play on a private server with these mods installed, and we need to write some scripts to make IE better able to process FP's ores. We also have a mod (Missing Pieces) which has a recipe that's the same as a recipe in Earthworks, and we'd like to be able to change the Earthworks recipe so we can actually use the entire mod.

**Comment by jaredlll08** [comment]
Immersive Engineering adds their own support.
No idea on the others
1.10.2 is discontinued.

**Comment by dragonshardz** [comment]
If IE adds their own support, then why doesn't it work? Everything I try to do with it results in a NullPointerException

And 1.10.2 is discontinued? Seriously? What a convenient excuse to not support your own work. This is the second mod we've had who won't touch 1.10.2 anymore because ~~reasons~~

**Comment by darkhax** [comment]
Wow, the second mod who wont work on 1.10.2? It's almost like the community has moved on from that version, and the devs feel it would be a better use of their time to work on newer things. Couldn't be that though.

**Comment by jaredlll08** [comment]
"If IE adds their own support, then why doesn't it work?"
I don't know, ask them, I don't dev IE.

Now since you want to be cocky about my decision of what versions to support....

1) 1.10.2 is 2 versions old now. 
2) I'm working on 1.12
3) I'm a university student and don't have time to maintain 3 versions of one (that's right, just one of my mods, I have about 20 others)
4) Modtweaker requires me to stay upto date with at least 5 mods, in terms of their versions and maintain support for that.
5) Adding onto 4 and 3, if I did maintain 3 versions of the mod, that would be about 15 mods total that I will need to keep tabs on, make sure they all work etc.
6) The port from 1.10.2 is trivial. Anyone telling you differently is lazy.
7) Instead of asking 20+ authors to keep supporting 1.10.2, why not talk to the 1 author who is keeping you on 1.10.2 asking them to update.
8) I would just like to remind you that this is my mod. My work. That I do in my free time. I can do with it what I want.

**Comment by dragonshardz** [comment]
I'm frustrated at stuff on the server not working and all of my best efforts having no payoff. It's irritating. It's not an excuse for coming off as an asshole, but I hope it explains that.

1. Your wiki doesn't document any support for 1.12 mods and only documents support for a total of *four* 1.11.2 mods. Since 1.7.10 is functionally dead, did you expect to not get support requests for 1.10.2? Maybe if you're no longer supporting a version of the mod, it would be a good idea to notate that somewhere, like in your Readme.md or on the curseforge page.
2. I'm not expecting you to drop everything to fulfill a request for an older version. I wasn't expecting you completely shut me down, either.
3. 4. 5. I understand having time constraints and having to prioritize your workload.
6 & 7. The request doesn't stem from another modder(s) refusing to update to 1.10.2, it stems from me trying to be a helpful player on my server and find tools to fix problems we run across. I didn't put together the set of mods we're using and don't know which, if any, are keeping us from using 1.11.2 at least.
8. That's great. I'm glad you have a strong sense of your obligations, or lack thereof.

**Comment by jaredlll08** [comment]
Well Crafttweaker 1.12 is still being worked on, I need to get that working perfectly before I can do anything else.
The wiki is old and outdated, it is being replaced by: http://crafttweaker.readthedocs.io/en/latest/

You should look at what mods can be updated before asking mod authors to support an older version. Like I said, 1.10.2 -> 1.11.2 is a trivial update. McJty for instance, supported both versions, by using a bridge mod, it was that easy (no the bridge mod cannot help me).

1.11.2 support came late, that is why there are so few mods, people weren't really using it, so I put the port off, and no one asked for it, and I spoke to a lot of pack authors. When I eventually got around to doing it, 1.12 was released a week or 2 later... so I'm sorry for that, but the latest version always has priority.

And finally, after actually loading both mods into the game, and looking at the conflicting recipes, such as this one:

![](http://i.blamejared.com/imPcP.png)


Notice how, at the top, it says "Crafting"?
That means it is a vanilla crafting table recipe. Which can be removed via Crafttweaker without the mod needing support, you claim to have scoured the wiki for mod support, but you must have missed the [Lesson 2: Basic Recipes](url) page...

**Comment by dragonshardz** [comment]
If the wiki is outdated and being replaced, you may want to update the links to it. I understand the latest version having priority, and I hope you understand how frustrating it can be to take on the job of fixing interoperability problems and having your tools not work! :)

As for the second part - no, I didn't miss that page, but the way it is written plus my own experiences attempting to change/create vanilla crafting recipes added by mods led me to believe that mod support is required to change recipes added by mods or create crafting recipes using modded items. I was also referring specifically to the wiki for *this* mod, not the MineTweaker wiki.

I'll get in touch with the IE guys and pick their brains about their own CraftTweaker/ModTweaker compatibility work, since it seems that the documentation I *can* find about doing stuff like adding recipes to the IE Crusher is wrong and/or unclear.

**Comment by jaredlll08** [comment]
Which wiki are you talking about? The modtweaker wiki and crafttweaker wiki
are one in the same...

**Comment by dragonshardz** [comment]
...so they are.

Sometimes braining is hard.
