### ISSUE TITLE
thermal expansion 1.10.2 support

### ISSUE THREAD

**Issue by Trinsdar** [jaredlll08/ModTweaker#504]
Could you add support for Thermal Expansion?

**Comment by bookerthegeek** [comment]
Duplicate, and no as they have there own method of modifying recipies. Check their wiki.

**Comment by Trinsdar** [comment]
well I didn't see anything about that on their wiki.

**Comment by bookerthegeek** [comment]
Nope, you need to go [HERE](http://teamcofh.com/docs/thermal-expansion/other/inter-mod-communication/)

**Comment by Trinsdar** [comment]
Well never mind then. I do not know how to mod

**Comment by jaredlll08** [comment]
1.10.2 is no longer supported

**Comment by idnthvn** [comment]
Sad to see this closed :(
