### ISSUE TITLE
[1.12] Better With Mods

### ISSUE THREAD

**Issue by Joxxs** [jaredlll08/ModTweaker#508]
Mill recipe removal is not working.

**Comment by jaredlll08** [comment]
Use the issue template

**Comment by Joxxs** [comment]
Wow what a little shit.
You copy pasted code from cauldron and it broke the Mill.

Good shit retarded fuck act like a human being.

**Comment by bookerthegeek** [comment]
@Joxxs just wow...

you use software written for free, by somebody in their free time, and then you can't even have the decency to be properly ashamed of the oxygen you breath. Good Job.

Go be an Anti-Hero and find your final solution.

**Comment by jaredlll08** [comment]
https://github.com/jaredlll08/ModTweaker/pull/505
What is that you may ask? That is a PR, made by @primetoxinz, the author of BetterWithMods, he wrote the original code, not me, but that doesn't mean that you should shout at him about it, you could have just filled in the issue template (you know, the text that was in this issue before, the text that you deleted...) then I would have gladly helped you, but right now, I can't. I don't know what versions you used, I need to know all the versions (Minecraft, Crafttweaker, ModTweaker, MTLib and JEI) I can't help you without those.

Then you didn't supply the log so I don't know what the issue actually is, beside
>Mill recipe removal is not working.

 there are many ways that something may not be working, I don't know which one you are talking about.

You need to understand that I cannot help, at all, without a proper filled issue template, it isn't to make my life easier, it is to make it that I actually know what I'm looking for to fix.

>If you ever need to be knocked down to size in person or intellectually let me know

 Yo, I need to be knocked down intellectually, why don't you do it by making a PR fixing the issue.

**Comment by Joxxs** [comment]
> you use software written for free, by somebody in their free time, and then you can't even have the decency to be properly ashamed of the oxygen you breath. Good Job.
> 
Does not mean I have to put up with a kid not even half my age trying to talk down to me.

>  it is to make it that I actually know what I'm looking for to fix.
> 
Your coding skills apparently to actually test
Than there is this skill called debugging.

Here is the log from crafttweaker
> 

> 
Yup no bugs nothing there you go just loading.
**Above I explained what you did wrong already**
Geez if I have to fix the code might as well give me the label maintainer/owner.

> Yo, I need to be knocked down intellectually, why don't you do it by making a PR fixing the issue.
> 
Long ago I suggested to Tough as Nails team to fix their infinite water for bottles and much like you had ego so much larger than his IQ refusing to properly learn ray trace or implement properly refusing even pr.

Never understood the ego that is in minecraft community.

Now I have to maintain my own copy of tan cause "player.world.rayTraceBlocks" too complicated.
https://github.com/Glitchfiend/ToughAsNails/blob/TAN-1.12.x-3.x.x/src/main/java/toughasnails/handler/thirst/FillBottleHandler.java
`
   @SubscribeEvent
    public void onPlayerRightClickWater(PlayerInteractEvent.RightClickItem event) throws Exception
    {
	   EntityPlayer player = event.getEntityPlayer();
	   ItemStack stack = player.getHeldItem(event.getHand());
	   World world = player.world;
	   int stackCount = stack.getCount();

        if (stack.getItem().equals(Items.GLASS_BOTTLE) && SyncedConfig.getBooleanValue(GameplayOption.ENABLE_THIRST))
        {		
		RayTraceResult target = RayTrace(player);
		if(!(target == null) && world.isBlockModifiable(player, target.getBlockPos())){
			BlockPos targetPOS = target.getBlockPos();
			IBlockState targetState = world.getBlockState(targetPOS);
			Material targetMaterial = targetState.getMaterial();

			if(targetMaterial == Material.WATER && ((Integer) targetState.getValue(BlockLiquid.LEVEL)).intValue() == 0){
				world.setBlockToAir(targetPOS);
				stackCount--;

				stack.setCount(stackCount);
				if (!player.inventory.addItemStackToInventory(new ItemStack(TANItems.water_bottle))){
					player.dropItem(new ItemStack(TANItems.water_bottle),false);
				}
				event.setCanceled(true);
			}
		}
	}
   }
`

**Comment by Restioson** [comment]
@Joxxs The [Markdown Cheatsheet] (https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) might help you there.

**Comment by MJRLegends** [comment]
@Joxxs try having some respect and not be rude, if you can do better make your own mods

**Comment by shadowfacts** [comment]
> Does not mean I have to put up with a kid not even half my age trying to talk down to me.

Age doesn't matter, you're the one who's being ridiculously impolite.

> refusing to properly learn ray trace or implement properly refusing even pr.

I don't see any attempt on the ToughAsNails issue tracker to report or PR a fix for the issue, and I suspect, that if you treated the TAN issue with the same callousness and rudeness, that the team would have been perfectly warranted in ignoring you.

> LOL Look how shitty github is... can't even have working embedded codes.

It does, perfectly well, you just don't know how to use it:

```java
public static void main(String[] args) {
    // code
}
```

> Geez guess I am just still real coder using svn

If you were a "real coder", you would understand that the tools you use don't dictate whether or not you're a "real coder".

**Comment by gegy1000** [comment]
`Does not mean I have to put up with a kid not even half my age trying to talk down to me.`
If you don't want to put up with him, don't use his mods or report issues to them. He is not talking down to you, he asked you to simply use the issue template, and has explained his reasons in detail.

`Your coding skills apparently to actually test
Than there is this skill called debugging.`
Extensive testing takes time, there's a lot of functionality linking together and testing everything would be impractical. Jared does this for free, in his own time. He can choose what he wants to spend time on.
For issues that maintainers miss, mod users may find them and report them here to be fixed as you have done here, and most people will be happy to assist the mod developer reproduce and fix the bug in a friendly manner.

`Above I explained what you did wrong already`
It would be helpful to Jared if you would've given more details in the original post, and if you were unaware, you could easily open a new issue with the details and I'm sure Jared would be happy to look into it.

`LOL Look how shitty github is... can't even have working embedded codes.`
That's your fault.

**Comment by jaredlll08** [comment]
Yip, as @gegy1000 said, If I had the information I needed... I would gladly help as I have done in nearly all of my issues, even the ones where I do exactly this, close it saying I need the issue template, when I get the template filled out, I help them

**Comment by Joxxs** [comment]
> Age doesn't matter, you're the one who's being ridiculously impolite.
Sure it does ignorant shit.

>If you were a "real coder", you would understand that the tools you use don't dictate whether or not
> you're a "real coder".
Cause real programmers use notepad huh

> He is not talking down to you
Sure he was ignorant fuck just like my ball sack banging your mommies clit son
See you 10 year old raging virgins attacking me sucking your boys cock is also talking down to me.

> That's your fault.
Ya its my fault it can not even read characters with space.
Guess that is why Linus the inventor of git doesn't even use github cause it is such garbage

**Comment by RazzleberryFox** [comment]
Best thing you can do when you get a user like this is tell them to sod off and block them. Don't even bother helping his rude ass.

**Comment by Gkoliver** [comment]
>Does not mean I have to put up with a kid not even half my age trying to talk down to me.

Even if he is a kid half your age, you have not put in countless hours to make a mod, yet here you are complaining about this piece of art (yes, modding/coding is an art) that another person makes? At least this "kid" is decent enough to try and create something for a community to entertain said community.

**Comment by Joxxs** [comment]
> Best thing you can do when you get a user like this is tell them to sod off and block them. Don't even
> bother helping his rude ass.
Hey razzle still can't get real job yet?

**Comment by Restioson** [comment]
Why is that all quote @Joxxs? What I mean was that you should be using code tags, demarcated by three sets of backticks (`). The GitHub desktop browser UI has a code tag symbol in the top middle-to-right, which are a pair of angle brackets. To enable syntax highlighting, simply put the language right after the first set of backticks, with no spaces.

**Comment by MJRLegends** [comment]
@Joxxs go back to school kid playtime is over

**Comment by p455w0rd** [comment]
@jaredlll08 stop feeding the troll and lock convo?

**Comment by jaredlll08** [comment]
Ok yea... this is getting out of hand. Locked.
