### ISSUE TITLE
[1.10.2][2.0.13] Custom Chisel groups cause game to stall

### ISSUE THREAD

**Issue by Compegen** [jaredlll08/ModTweaker#511]
#### Issue Description:
Adding custom chisel groups then trying to reload in-game causes minetweaker commands to stop working, and on world leave and rejoin the game will stall

#### Script used
[Script used](https://pastebin.com/mWcA0Phu)

#### Minetweaker.log file
[Minetweaker log](https://pastebin.com/9q9PU5TG)

____
#### Affected Versions (Do *not* use "latest"):

- Chisel: 2-0.0.13.29
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2316
- Crafttweaker: 3.0.26
- ModTweaker: 2.0.13
- MTLib: 1.0.3

#### Your most recent log file where the issue was present: 
[Log](https://pastebin.com/yaQQkguN)

**Comment by jaredlll08** [comment]
Chisel issue.

1.10.2 is no longer supported
