### ISSUE TITLE
Pulverizer recipes are not removing

### ISSUE THREAD

**Issue by tgstyle** [jaredlll08/ModTweaker#512]
#### Issue Description:
The script is set to remove gem ore recipes from the Pulverizer.

#### What happens:
The recipes are not removed. I have tried the input and output.

#### What you expected to happen:
The recipes should be gone, however checking in JEI as well as putting ore in the pulverizer it still processed to dust.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://gist.github.com/tgstyle/aff56983f3d45946e2b290c8a1e0ac54

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/tgstyle/958697b439370e275d9421a466b6840b

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12
- Forge: 2443
- Crafttweaker: 4.0.2
- ModTweaker: 4.0.1
- MTLib: 3.0.0

**Comment by jaredlll08** [comment]
Thermal Expansion uses the input to remove items (nothing I can do, it is how they do it), from the looks of it you are trying to remove an output

**Comment by tgstyle** [comment]
I found out it removes the recipe fine (ore is the input) and adds them back. However it now seems TechReborn is overriding the recipe, or is making sure to load recipes after crafttweaker ?

**Comment by jaredlll08** [comment]
Seriously... If tech reborn does that, they are doing something seriously
wrong -_-

**Comment by tgstyle** [comment]
It seems to make sure there is a crushed ruby, peridot, and sapphire recipe in the pulverizer no matter what I do.

**Comment by tgstyle** [comment]
![2017-08-17_19 31 00](https://user-images.githubusercontent.com/5832709/29440505-b5234502-8382-11e7-8f07-fea9d06b5dc4.png)
