### ISSUE TITLE
Casting Recipes for Unstable Induced Tool Parts Show in NEI but don't cast.

### ISSUE THREAD

**Issue by ghost** [jaredlll08/ModTweaker#513]
#### Issue Description:
I've read online that due to an Extra Utilities bug, the recipes for unstable induced tool parts don't work, so I added them in with ModTweaker. 

#### What happens:
First I added in an ingot recipe. That worked. Then I got onto the pickaxe head. That's where I encountered a problem. The recipe shows in NEI, but just didn't want to cast. I Tried with another tool part, it didn't work,

#### What you expected to happen:
I expected everything would work out fine and I would be able to add recipes for every tool part and then keep configuring my modpack.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): https://pastebin.com/gua9XfTQ

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.7.10
- Forge: Forge10.13.4.1614
- Crafttweaker: 3.0.13
- ModTweaker: 0.9.6
- MTLib: Not used

#### Your most recent log file where the issue was present: 

https://pastebin.com/13Wfrss7

**Comment by jaredlll08** [comment]
Not enough information

Judging by the use of "NEI" I'm going to assume this is not 1.12, in which case it is not supported.

**Comment by ZTWarz** [comment]
I pressed enter while typing so it posted before i finished... I'm dumb.
