### ISSUE TITLE
How is the 1.10.2 version suppose to work?

### ISSUE THREAD

**Issue by ShmooSmith** [jaredlll08/ModTweaker#520]
Why is there a 1.10.2 version for this mod when it requires MineTweakers3? MineTweakers3 doesn't seem to have a 1.10.2 version or above so how does this work? I tried running it with the latest version of MineTweakers3 and forge said it couldn't load the outdated mod.

**Comment by Alan19** [comment]
Crafttweaker is the 1.10 port of Minetweaker
