### ISSUE TITLE
1.11.2 Botania

### ISSUE THREAD

**Issue by darkshadow543** [jaredlll08/ModTweaker#521]
#### Issue Description:
I put in the values to change a Botania recipe.

#### What happens:
Gives me an error saying botania is not a member, ignoring the nbt tag error for now

#### What you expected to happen:
Add a custom apothecary recipe for the pure daisy.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
One line, so Ill paste it.  If it were longer than this, I would use pastebin.
mods.botania.Apothecary.addRecipe("puredaisy", [<ore:petalWhite>*4, <roots:petal_dust>.onlyWithTag({spell:spell_sunflower})]);

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
Went through and found the one line you need
 ERROR: Botania.zs:1 > No such member: botania
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge:13.20.1.2454
- Crafttweaker: 3.0.26
- ModTweaker: 3.02
- MTLib: 2.03

#### Your most recent log file where the issue was present: 
https://pastebin.com/2vLERxZP

**Comment by jaredlll08** [comment]
1.11.2 isn't supported anymore.
