### ISSUE TITLE
[1.12.1] Start up Crash

### ISSUE THREAD

**Issue by YOYOK9** [jaredlll08/ModTweaker#524]
Starting my server and client up and it crashes on initialization of the mod. Tested with and without scripts in the scripts folder.

Crash:
https://pastebin.com/6vZ24jjJ

Mc: 1.12.1
CraftTweaker: CraftTweaker2-1.12-4.0.5
ModTweaker: modtweaker-4.0.1
Forge: 1.12.1-14.22.0.2474

**Comment by OscarXcore** [comment]
Just make sure you have the correct ModTweaker version. I found out that bug exists in 4.0.2 not 4.0.1.

**Comment by Hjaldar** [comment]
Can confirm same crash with **modtweaker-4.0.2**, not 4.0.1 as stated above. The crashlog shows this actually occurred with 4.0.2.

Log: https://pastebin.com/H9EN6jra

In both cases betterwithmods is not present but its API is being loaded by Quark.

**Comment by UnPure** [comment]
I have the same crash while using v4.0.2.
No problems on v4.0.1.
The difference is, unlike YOYOK9 and Hjaldar i'm not using Quark.

**Comment by jaredlll08** [comment]
Please try
http://ci.blamejared.com/job/Crafttweaker-1.12/256/artifact/build/libs/CraftTweaker2-1.12-4.0.5.256.jar

**Comment by jaredlll08** [comment]
ok so, the version does *work*... (https://github.com/jaredlll08/CraftTweaker/issues/316#issuecomment-328122649)
But I am unsure as to if support still gets loaded, could one of you guys test it out?

**Comment by UnPure** [comment]
I can confirm that v4.0.5.256 is working.
Are you talking about other mods support?
If yes, my scripts for Thermal Expansion (Pulverizer) are loaded and working according to JEI.

**Comment by jaredlll08** [comment]
Cool, fixed in Crafttweaker, new version later tonight
