### ISSUE TITLE
[REQUEST] Re-implement Embers support

### ISSUE THREAD

**Issue by Sunconure11** [jaredlll08/ModTweaker#525]
Embers, on previous versions had modtweaker support. Since both ModTweaker and Embers are on 1.12.1, would it be possible to re-implement support?

**Comment by jaredlll08** [comment]
Embers does not appear to be in active development at the moment. If the development picks up, I'll reevaluate adding support.

**Comment by Sunconure11** [comment]
Embers got an update recently, though the dev is going through some IRL crap. Would that be enough to add support for embers in modtweaker?

https://minecraft.curseforge.com/projects/embers/files/2495586

**Comment by jaredlll08** [comment]
this adds support:
https://github.com/DaedalusGame/Soot

**Comment by Sunconure11** [comment]
Fair point.
