### ISSUE TITLE
Better with mods: Anvil script not working

### ISSUE THREAD

**Issue by TadeasSvetlik** [jaredlll08/ModTweaker#526]
#### Issue Description:
Hello
Im trying to modifie recipes in Better with mods Soulforged Steel Anvil using scripts from CraftTweaker wiki and it doesnt load saying "No such member: Anvil". Other machines such as Saw works fine

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/tN6qvTYJ

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/nc3e865R
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: 1.11.2-13.20.1.2454
- Crafttweaker: 1.11.2-7.1.9
- ModTweaker: 3.0.2
- MTLib: 2.0.3

#### Your most recent log file where the issue was present: 

https://gist.github.com/Feltopi/a5751ae3aa3697466fcc41a0d113bca0

**Comment by jaredlll08** [comment]
1.11.2 isn't supported and we didn't add support for BWM in 1.11.2
