### ISSUE TITLE
[1.7.10] Clientside - Detect Gamemode of Modpack?

### ISSUE THREAD

**Issue by Hodel1** [jaredlll08/ModTweaker#529]
Hi,

i want to ask, how i add my .zs files for multiple Gamemodes on Clientside?

For example:
inf1 - Normalmode
inf2 - Expert mode

Now a Basic Script i add in /scripts - that works fine.
But additional Scripts for expert mode only. Where i have to add them or directing to use it only on expert mode? If i add this file in /modpack/expert/scripts i see them changes, when i connect to Inf2.

Is there a chance to resolv them?

I know, 1.7.10 is not longer supported but it is not a bug, it is a question ;)

Greets

**Comment by jaredlll08** [comment]
Wrong repo.
I got no idea what you are asking...

**Comment by Hodel1** [comment]
Oh, really? :D 

Is this Repo not for Minetweaker, which is included in FTB Infinity Evolved?
It includes /mod/ModTweaker2-0.9.6.jar

serverside works it fine, but don't sync the receipechanges. this is now only clientside

**Comment by jaredlll08** [comment]
Ok so
Minetweaker is not Modtweaker.
Modtweaker is not FTBTweaks.
FTBTweaks is not minetweaker
FTBTweaks is the mod you are looking for.

FTBTweaks doesn't sync recipes from the server to the client, scripts need to be the same on both. No that will not change

**Comment by Hodel1** [comment]
thank you for explain me.
i think, it was my fault. i corrected it client side.

have a good day :)
