### ISSUE TITLE
1.10.2 solderer and Jei desynch

### ISSUE THREAD

**Issue by wizard1399** [jaredlll08/ModTweaker#534]
#### Issue description:
The solderer from refined storage removes recipes but does not update the Jei. Removed recipes are still listed in JEI. I tried the recipe command and the uses on the solderer. When I try to place the items in the the solderer for a removed recipe, the items are not accepted so the recipe was removed successfully, but JEI was not updated.

#### What happens:
Solderer recipes get removed, but Jei is not updated to show the removal.

#### What you expected to happen:
The solderer recipe to be removed from Jei.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

N/a: same thing happens with all removals.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2422
- Crafttweaker: 3.0.25
- ModTweaker: 2.0.13
- MTLib: 1.0.3

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by wizard1399** [comment]
Sorry for the repeat. Smart phone was not as smart as I thoight.

**Comment by jaredlll08** [comment]
1.10.2 isn't supported anymore.
