### ISSUE TITLE
[1.11.2] Changed Forestry recipes doesnt show in JEI

### ISSUE THREAD

**Issue by TadeasSvetlik** [jaredlll08/ModTweaker#535]
Hello

first of all i would like to ask if u are willing do fix some minor things in 1.11.2 or its pointless to even report them.

Other than that i have changed and removed recipe in Forestry Carpenter which is working fine, but it doesnt show new recipe in JEI.

**Comment by jaredlll08** [comment]
Not worth reporting.

Also JEI recipes that don't show isn't exactly a small thing, I spent a good part of this year trying to get them working but still couldn't.
