### ISSUE TITLE
How to add TiC basin recipe to cast block ?

### ISSUE THREAD

**Issue by Thyriel** [jaredlll08/ModTweaker#539]
Following the turorial on
http://crafttweaker.readthedocs.io/en/latest/#Mods/Modtweaker/TConstruct/Casting/
i'm unable to find a working code to add a simple block casting recipe that does not require a cast item to be placed inside the basin.
If i don't define any item there's an error in the log, if i define minecraft:air - crash error. ( stack cannot be null), if i try <tconstruct:casting:1> it requires a basin inside the basin (same when i define the block itself there)

**Comment by Thyriel** [comment]
Ok found it after excessive trying:
Just an empty bracket <> works (Maybe add it to the tutorial code ?)

**Comment by Thyriel** [comment]
Sorry for spamming. Seems while it works, it still generates an error in the logfile and chat: (unable to resolve <>)
Code i use:
mods.tconstruct.Casting.addBasinRecipe(<botania:storage>, <>, <liquid:manasteel>, 1296);

**Comment by jaredlll08** [comment]
...
Have you tried putting `null`?
