### ISSUE TITLE
[1.12.2] Better With Mods Removal Scripts Do Not Work

### ISSUE THREAD

**Issue by Darkosto** [jaredlll08/ModTweaker#542]
#### Issue Description:
Okay! So, I already reported to the modpack dev. But, he's a bit incompetent. So, I am bringing this to U're attention.

#### What happens:
Well...

I made removal scripts for the BWM saw and they do't work. 

#### What you expected to happen:
I expected for it to work. 

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/EHeKyyfQ

^^ It's down on the bottom part there. At the end.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://gist.github.com/Darkosto/342243e6c4baf5dc7e8eb43d8b64d42d
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2512
- Crafttweaker: 4.0.8 
- ModTweaker: 4.0.3
- MTLib: 3.0.0

#### Your most recent log file where the issue was present: 

https://gist.github.com/Darkosto/f4640f69ddd232edefa2fc3bbf21fe4a

**Comment by jaredlll08** [comment]
Can this be reproduced with just the mods required?

**Comment by Darkosto** [comment]
^^ HOW DU U KNO I DID NOT DO THAT THING U SED?! I COULD HAVE!





THIS
GUY
CLOSES
MY
ISSUE
ON
SPECULATION!



I am outraged.
