### ISSUE TITLE
[1.12.2] Syntax given in documentation is not working for Actually Additions

### ISSUE THREAD

**Issue by tjsd** [jaredlll08/ModTweaker#543]
#### Issue Description:
Trying to remove the input from the crushed does not work, you have to remove the output. 

#### What happens:
If you use a code line to remove gold ore like in the documentation:
`mods.actuallyadditions.Crusher.removeRecipe(<minecraft:gold_ore>);`
You can still put gold ore in the crusher, and it does not work with ore:oreGold either

#### What you expected to happen:
That gold gets removed as being able to be processed in the crusher. 
You now have to remove output (the final product) and you have to specify every output, oredict does not work for that either.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.0.2503
- Crafttweaker: CraftTweaker2-1.12-4.0.8
- ModTweaker: modtweaker-4.0.3

**Comment by kindlich** [comment]
If you read the comment above the method you read this:
`//mods.actuallyadditions.Crusher.removeRecipe(IItemStack output);`

The line below normally doesn't refer to a recipe that exists, it only shows what it would look like :wink:

**Comment by jaredlll08** [comment]
As @kindlich said, we just show what a recipe line would look like.
