### ISSUE TITLE
[1.12.2]Removal bypassing priority with mod removal

### ISSUE THREAD

**Issue by Niuttuc** [jaredlll08/ModTweaker#544]
#### Issue Description:
First of all, I don't know if this issue should be here or on the CraftTweaker repo, the issue is more with both. Basically, if I remove recipes from mods in a script, the removal of vanilla recipes will be loaded at the end, AFTER adding the recipes, regardless of priority, stopping me from adding any classic crafting table recipe.

#### What happens:
When a modded recipe is removed, all of them are removed first and then the crafting table recipes won't be removed until all other operations are done, ignoring priority and functions.

#### What you expected to happen:
All recipes are removed and new ones are then added.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
So, I separated my files in multiple scripts for easier testing:
[ModRemove (priority 4)](https://pastebin.com/rDFggRJs)
[VanillaRemove (priority 3)](https://pastebin.com/DSRtGnCa)
[ModAdd (priority 1)](https://pastebin.com/mzpDXhea)
[VanillaAdd (priority 0)](https://pastebin.com/vwiCrkuu)

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
When all 4 are loaded, the error occurs:
[crafttweaker.log](https://pastebin.com/VfAmMFZf)

When only the Vanilla ones are loaded:
[vanillatweaker.log](https://pastebin.com/54M6Vqrx)
(rereading it no add there either, I've got it to function earlier, I'll ge back to this issue when I'll reproduce it, sorry.)

#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.0.2512
- Crafttweaker: 4.0.8

#### Your most recent log file where the issue was present: 

[Last Log](https://pastebin.com/0gdUzRgc)

**Comment by jaredlll08** [comment]
Wrong repo.

So all of my mods, being crafttweaker and Modtweaker use a double list approach to addition and removal, all of the removal actions are collected, and then ran, and then only after that are the addition actions ran, so it is impossible for that to happen. 

Speak to whatever other mod this is affecting, but for crafttweaker and Modtweaker, even having a removal script on the line after the addition script will result in the removal script being ran first.

**Comment by bookerthegeek** [comment]
@Niuttuc Can you post a mod list? Maybe we can see what is going wrong

**Comment by Niuttuc** [comment]
Thanks, [here it is](https://pastebin.com/u8Aw3gmE).

**Comment by Niuttuc** [comment]
After some more testing, the mod isn't the issue there...
After testing with ONLY vanillaAdd and then VanillaAdd and VanillaRemove, the two logs.

[VanillaAdd](https://pastebin.com/qQ7WDe4L)
[VanillaAdd+Remove](https://pastebin.com/gh9YZPsL)

The issue is not only with mods, but if any removal is done, there is no add.
Should I move the issue, or is it still not an issue?

**Comment by bookerthegeek** [comment]
Ill look I to it tonight.
