### ISSUE TITLE
[1.12.2] Alloy Removal Not Working

### ISSUE THREAD

**Issue by Darkosto** [jaredlll08/ModTweaker#545]
#### Issue Description:
This is not a modpack >.> It's only tinkers' and maybe JEI... and another mod... and maybe another... THATS IT THOUGH <.<

The syntax for removing alloying in a smeltery does not seem to be working correctly: 
mods.tconstruct.Alloy.removeRecipe(<liquid:constantan>);
![image](https://user-images.githubusercontent.com/10309699/32118912-7b7b7820-bb21-11e7-880b-b94ac0b54c5c.png)

#### What happens:
I make a script and alloying still shows up.

#### What you expected to happen:
To make a script and alloying to not show up.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
Up on top.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://gist.github.com/Darkosto/3bdb3bddf132b4dea04b4becf65f69d5
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2515
- Crafttweaker: Yes 
- ModTweaker: Yes
- MTLib: Yes

#### Your most recent log file where the issue was present: 

I just gave you one! HOW MANY LOGS DO YOU WANT?! 1 LOG?! 2 LOGS?! 8 LOGS?! 

WASTE
OF
MY
TIME

![image](https://user-images.githubusercontent.com/10309699/32119061-ff4a78fe-bb21-11e7-913e-9b9bed9ae002.png)

BYE FELECIA!

https://gist.github.com/Darkosto/fa57d418b34aaf85db87ed59e8cb9706

Thanks!
Darkosto

P.S. Please don't close this before reading all of it. I spent a lot of time on it. Thanks.

**Comment by jaredlll08** [comment]
Please use the issue template and read the template. It tells you to use pastebin / gist to host your scripts. It is needed to ensure that data does not get lost as has happened right here, with your script, ```< and >``` are considered formatting chars, so github removes them.
