### ISSUE TITLE
[1.12.2] Unable to add TiC Smeltery fuels

### ISSUE THREAD

**Issue by NielsPilgaard** [jaredlll08/ModTweaker#546]
#### Issue Description:
I made a script to add several liquids as smeltery fuels, but no matter the temperature I set, the smeltery says "Not enough heat to melt this item". I've tried about 15 different numbers between 300 and 240000.

#### What happens:

The smeltery doesn't smelt anything, when supplied with the newly added fluids.

#### What you expected to happen:

I expected the smeltery to smelt items, when supplied with Refined Fuel among others.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://gist.github.com/NillerMedDild/143b18260c96a51b53a25e07089d9d90

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://gist.github.com/NillerMedDild/dcb30a5c928cd5407cc6883d0086779e
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.0.2515
- Crafttweaker: CraftTweaker2-1.12-4.0.8
- ModTweaker: modtweaker-4.0.4
- MTLib: MTLib-3.0.1

#### Your most recent log file where the issue was present: 

https://gist.github.com/NillerMedDild/e26b7b1cd53ecac4ae8d163d04fdebb5

**Comment by Lanse505** [comment]
According to the log everything is being parsed correctly.
 Might be a change in their API since MoT zs implementation.

**Comment by kindlich** [comment]
https://github.com/jaredlll08/ModTweaker/blob/2f195bc2f71677ec840ae432b0cebb4365f871ea/src/main/java/com/blamejared/compat/tconstruct/Fuel.java#L35-L39

The provided temperature int is NOT for the actual smelting temperature but for the time a fluid stack lasts as fuel:

https://github.com/SlimeKnights/TinkersConstruct/blob/7e2199c58766b858ac2f3c6c6067e8a90da2ca7d/src/main/java/slimeknights/tconstruct/library/TinkerRegistry.java#L646-L665

EDIT: The temperature depends on the fluid registry temperature
EDIT2: Check the [ILiquidDefinition Crafttweaker wiki page](http://crafttweaker.readthedocs.io/en/latest/#Vanilla/Liquids/ILiquidDefinition/): Maybe that works?

**Comment by NielsPilgaard** [comment]
Thanks a lot for the clarification, I'll try changing the temperature.

**Comment by jaredlll08** [comment]
As @kindlich said, you don't set the temp with this command

**Comment by NielsPilgaard** [comment]
That did the trick, thanks :D

**Comment by NielsPilgaard** [comment]
Could you elaborate on what the temperature/duration sets? Amount of items smelted with 1mb?

**Comment by kindlich** [comment]
http://crafttwaeker-docu.readthedocs.io/en/latest/#Mods/Modtweaker/TConstruct/Fuel/


Okay, so here's how it works:
The fluid amount you added to your fluidStack object is how many millibuckets the smeltery will drain at once to fuel itself. 
The duration you used as second parameter determines for how many ticks these millibuckets will last.

Example:
`mods.tconstruct.Fuel.registerFuel(<liquid:water> * 2, 300);`
→ The smeltery will drain 2mB water whenever it needs to, never less.
→ Those 2mB of water will last for 300 ticks

So, in this case, every 300 ticks you'd need to have at least 2mB of water in the smeltery to keep it running constantly. At least that's what I think it's like :wink:

**Comment by NielsPilgaard** [comment]
Ah alright. Thanks for updating the documentation so fast :D
