### ISSUE TITLE
[1.12.2] Forestry Squeezer support still broken

### ISSUE THREAD

**Issue by SnowShock35** [jaredlll08/ModTweaker#550]
#### Issue Description:

Recipe removal doesn't work

#### What happens:

Recipe removal doesn't work

#### What you expected to happen:

For recipe removal to work

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

```
mods.forestry.Squeezer.removeRecipe(<liquid:water>, [<forestry:can:1>.withTag({Fluid: {FluidName: "water", Amount: 1000}})]);
```

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/6BWnyyGX

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14,23.0.2537
- Crafttweaker: 4.0.9
- ModTweaker: 4.0.5
- MTLib: 3.0.1

#### Your most recent log file where the issue was present: 

https://paste.ee/p/Q5eqZ

**Comment by jaredlll08** [comment]
So that is an example of a "container recipe", which is not an actual recipe that can be removed.

Try with other "normal" recipes please (A container recipe is just a fluid container that fills or empties the squeezer)

**Comment by SnowShock35** [comment]
Ah that really sucks :/ especially since it gives a tin ingot :(
