### ISSUE TITLE
[1.12.2] Question about IE Support

### ISSUE THREAD

**Issue by accessdenied0** [jaredlll08/ModTweaker#552]
I want to begin with apologise about this issue. I know people don't want to be questioned about progress and stuff, but I need to know if there is any Immersive Engineering Support planned (or implemented) for 1.12.2 because I would need it for a mod pack I planned to make.

I would specifically need the ARC-Furnace to add or remove recipes.

I would be thankful to get any kind of reply here towards to IE.

Thank you for your effort.

access_denied

**Comment by jaredlll08** [comment]
IE adds their own support, so go speak to them
