### ISSUE TITLE
[1.11.2] addMelting

### ISSUE THREAD

**Issue by Genqar** [jaredlll08/ModTweaker#557]
#### Issue Description:
Attempting to add recipe to TConstruct to the smeltery. Melting Astral Sorcery's starlight ore into liquid starlight. I don't get an error for incorrect code other than method available but _none_ matches. Ability to add a Smeltery cast recipe worked perfectly.

#### What happens:
Error: TConstruct.zs:34 > a method available but none matches the parameters (minetweaker.liquid.ILiquidStack)

Unable to Melt Astral Sorcery Ore into liquid starmetal

#### What you expected to happen:

Melt ore to liquid

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

mods.tconstruct.Smeltery.addMelting(<liquid:astralsorcery.liquidstarlight> * 288, <astralsorcery:blockcustomore:1>, 200, <astralsorcery:blockcustomore:1>);

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

see below
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: 13.20.1.2530
- Crafttweaker: 3.0.26
- ModTweaker: 3.0.2
- MTLib: 2.0.3

#### Your most recent log file where the issue was present: 

[https://pastebin.com/Eb0Pk6xy]

**Comment by jaredlll08** [comment]
1.11.2 isn't supported.

**Comment by Genqar** [comment]
Will there be support for 1.11.2, or am I just out of luck? 

And my bad for thinking 1.10 transferred to 1.11 in what it supported. Oops.
