### ISSUE TITLE
 Problems to add recipe to carpenter Forestry 1.7.10

### ISSUE THREAD

**Issue by AdrianCC** [jaredlll08/ModTweaker#559]
- Minecraft:1.7.10
- Forge:-1.7.10-1.2.0.345
- ModTweaker:3-1.7.10-3.0.9C

Good day
 I have a problem when trying to add a recipe in the carpenter

I add the Script + the error

https://pastebin.com/jrTkbZE9

Thanks in advance

**Comment by jaredlll08** [comment]
1.7.10 isn't supported anymore.
