### ISSUE TITLE
TE Redstone Furnace Issues

### ISSUE THREAD

**Issue by tgstyle** [jaredlll08/ModTweaker#560]
#### Issue Description:
You cannot remove clay to a brick.

Recipes do not remove from TE Redstone Furnace in the Pyrolytic conversion. When removing recipes it has no effect on the Pyrolytic conversion. I tried removing coal to see if it would impact the coal to coke recipe. It just says no recipe found.

#### What happens:
Nothing

#### What you expected to happen:
Clay balls to brick and coal to coal coke will be removed.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://gist.github.com/tgstyle/5874db7a630d3714fcbeeb8db2694522

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://gist.github.com/tgstyle/4d255a9a32908001f247aafc405fd966
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2559
- Crafttweaker: 4.0.10
- ModTweaker: 4.0.5
- MTLib: 3.0.1

#### Your most recent log file where the issue was present: 

https://gist.github.com/tgstyle/1efd71e713b8c89feb2afffc09a71124

**Comment by AcidKat** [comment]
I think this a broader issue, there's currently no support for augments at all (that I'm aware of) and certain recipes are unique to augments (others are automatically generated based on existing recipes, e.g. Flux Anodizers and Tectonic Initiator). The only solution to this would probably be to add new functions to modify augment recipes.

**Comment by tgstyle** [comment]
@AcidKat you are probably right for the coal to coke recipe. Other machines do have specific augment functions in MT. Clay balls however is not part of an augment (as far as I can tell), and may need further investigation.

**Comment by jaredlll08** [comment]
Was fixed via a PR
