### ISSUE TITLE
 Problem with pure daisy

### ISSUE THREAD

**Issue by AdrianCC** [jaredlll08/ModTweaker#563]
Minecraft:1.7.10
Forge:-1.7.10-1.2.0.345
ModTweaker:3-1.7.10-3.0.9C
Good day

I get this when I need to add a block with pure daisy

No such member:PureDaisy
recipes.addShaped(<Botany:ceramicBrick:16387>.withTag({meta: 19789}),
[[<ore:dyeRed>,<ore:dustAsh>,<ore:dyeYellow>],
[<ore:dyeBlue>,<ore:plankWood>,<ore:dyeBlue>],
[<ore:dyeYellow>,<ore:pulpWood>,<ore:dyeRed>]]);

mods.botania.PureDaisy.removeRecipe(<Botania:livingrock>);
mods.botania.PureDaisy.addRecipe(<Botany:ceramicBrick:16387>.withTag({meta: 19789}),<Botania:livingrock>, 20);

I have no problems with the altar and manapool

**Comment by bookerthegeek** [comment]
1.7.10 is EoL and no longer supported.

**Comment by AdrianCC** [comment]
I only have a problem with pure margarita recipes, when adding the other
botanical recipes they work normally

2017-12-12 2:28 GMT-05:00 BookerTheGeek <notifications@github.com>:

**Comment by AdrianCC** [comment]
I do not understand, so I forget version 1.7.10, this compatibility is according to the version of the mod, or the version of the tweaker mod that I'm using

**Comment by jaredlll08** [comment]
Well the latest version doesn't have botania support...

You didn't follow the template.

Read the wiki.

**Comment by AdrianCC** [comment]
I have the Botania r1.8-249, but it seems strange to me that all the other wiki statements for botania work perfectly. I only have a problem with the pure daisy
