### ISSUE TITLE
Cant remove recipe from Inscriber(AE2)

### ISSUE THREAD

**Issue by NickSpielt** [jaredlll08/ModTweaker#565]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker or ModTweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:

ERROR:No such static member in minetweaker.item.IIngredient: outputStack
ERROR: [ModTweaker2] Required parameters missing for Applied Energistics 2 Inscriber Recipe.

#### What you expected to happen:

All recipes from the inscriber get cleared.

#### Script used

`mods.appeng.Inscriber.removeRecipe(outputStack);`

#### Minetweaker.log file

[https://pastebin.com/Wbps7gmA](url)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.7.10
- Forge:forge-1.7.10-10.13.4.1558
- Crafttweaker:CraftTweaker-1.7.10-3.0.13 
- ModTweaker:ModTweaker2-0.9.6
- MTLib:/

#### Your most recent log file where the issue was present: 

[https://pastebin.com/Wbps7gmA](url)

**Comment by kindlich** [comment]
Okay, four things:

1) 1.7.10 is not supported anymore
2) You need to give `outputStack` a value! e.g. `mods.appeng.Inscriber.removeRecipe(<minecraft:grass>);`
3) You cannot simply remove all inscriber recipes (you could try `removeRecipe(<*>);` though)
4) Not sure about 1.7.10 but in later version AE adds all its recipes in several config files, you could override them
