### ISSUE TITLE
support at 1.7.10

### ISSUE THREAD

**Issue by AdrianCC** [jaredlll08/ModTweaker#566]
Minecraft:1.7.10
Forge:-1.7.10-1.2.0.345
MineTweaker3-1.7.10-3.0.9C
ModTweaker~2-0.8.3

I have several days trying to build a pack for 1.7.10, I discovered that some mods are not supported or are not compatible, someone would take the trouble to mention what version to which version there is no problem to add recipes of those mentioned in the the wiki.

Currently Supported Mods 1.7.10
Applied Energistics 2: Applied Energistics 2 Support
Aura Cascade: Aura Cascade Support
Botania: Botania Support
Chisel 2: Chisel 2 Support
Ex Nihilo: Ex Nihilo Support
Extended Crafting: Extended Crafting Support
Extra Utilities: Extra Utilities Support
Factorization: Factorization Support
Forestry: Forestry Support
Mariculture: Mariculture Support
Mekanism: Mekanism Support
Metallurgy 4: Metallurgy 4 Support
PneumaticCraft: PneumaticCraft Support
Railcraft: Railcraft Support
Thaumcraft 4: Thaumcraft 4 Support
Thermal Expansion: Thermal Expansion Support
Tinker's Construct: Tinker's Construct Support

thank you very much

**Comment by jaredlll08** [comment]
wat

**Comment by AdrianCC** [comment]
I was trying to modify some mods of those mentioned in the wiki that supports mod tweaker, to leave every time I try some mod I discover that it has a flaw or that the syntax given in the wiki does not work as it should be, so as to know if the version of the mod that I downloaded for 1.7.10 (has support with MineTweaker3-1.7.10-3.0.9C
ModTweaker ~ 2-0.8.3)

**Comment by jaredlll08** [comment]
1.7.10 is extremely old, I don't know what you want us to do, but we don't support it in any way.

**Comment by AdrianCC** [comment]
Of course I agree, I refer to what versions you worked on on 1.7.10 where the management of syntax is stable.
thanks for your compression
