### ISSUE TITLE
[1.12] Better With Mods Recipe Removal - Faulty

### ISSUE THREAD

**Issue by ghost** [jaredlll08/ModTweaker#568]
#### Issue Description:
Script recipe removal functions for _all_ Better With Mods machines do not work.

#### What happens:
Recipes that were supposedly removed with scripts do not actually get removed.

#### What you expected to happen:
Recipes that are written to be removed in scripts actually get removed.

#### Script used:
https://pastebin.com/fn5QAcrW

#### Minetweaker.log file:
https://pastebin.com/sCZbw2mi

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: build 2566
- Crafttweaker: 1.12-4.0.10
- ModTweaker: 4.0.5
- MTLib: 3.0.0

#### Your most recent log file where the issue was present: 

https://pastebin.com/7c3WgEQM

**Comment by jaredlll08** [comment]
update MTLib

**Comment by ghost** [comment]
I've updated MTLib to 3.0.1 (the highest version number available from CurseForge), and the issue persists.

**Comment by ghost** [comment]
Upon further testing, I've gotten the Mill removal to work at least (turns out continuously changing item id's make tweaking difficult to manage, who knew?).

**Comment by ghost** [comment]
After taking a look at the code, I think the crafttweaker website documentation for BWM is incorrect, and lacking some information.

Further testing seems to show that only the Turntable.remove, Anvil.removeShaped, and Anvil.removeShapeless functions are bugged. It would also be nice to get some add and remove functions for the Filtered Hopper, but that's a topic for another thread.

**Comment by ghost** [comment]
It's also worth noting that some crafting recipes which use any of the betterwithmods:material item (such as cut leather) cannot be removed.

**Comment by jaredlll08** [comment]
Your script is wrong


`<betterwithmods:material:34>` is actually Redstone Latch
`<betterwithmods:material:33>` is your Cut Leather (Scoured)

The Turntable and Anvil was messed, that will be fixed in the next version.
Everything else appears to be working, I'll take a look at the wiki.

**Comment by jaredlll08** [comment]
Can you possibly link me to the issue with the wiki? things look fine to me

**Comment by ghost** [comment]
Sorry, I don't recall what the problem with the wiki was 2 months on.
