### ISSUE TITLE
IC2 SemiFluidGenerator

### ISSUE THREAD

**Issue by MatthiasMann** [jaredlll08/ModTweaker#572]
I haven't found a way to modify the fuel list of the SemiFluidGenerator with IC2 config files.
So having support for that in ModTweaker would be really nice.

- Minecraft: 1.12.2
- Forge: 14.23.1.2559
- Crafttweaker: 1.12-4.0.10
- ModTweaker: 4.0.5
- MTLib: 3.0.1
- IC2: 2.8.16-ex112

**Comment by jaredlll08** [comment]
If the config can't change it, then we can't
