### ISSUE TITLE
[Request] Gendustry 1.10.2

### ISSUE THREAD

**Issue by Alroy1000** [jaredlll08/ModTweaker#574]
It would be wondderfull if you can add gendustry support for the 1.10.2 
Greetings 
And happy new year ☺

**Comment by jaredlll08** [comment]
1.10.2 isn't supported.

Gendustry is kinda set, like I don't think their api is open to just making changes, although they do have a Config to change stuff I think

**Comment by Lanse505** [comment]
They also have their own JSON system for adding and handling things.
