### ISSUE TITLE
[Suggestion] ExU2 Enchanter Support

### ISSUE THREAD

**Issue by TheLimePixel** [jaredlll08/ModTweaker#575]
As the Enchanter has gotten a big role in the progression of Extra Utilities 2, I suggest adding support for it.

**Comment by accessdenied0** [comment]
I would approve this so much, for a tweaking I need to make on my own private (maybe soon public) pack...

**Comment by jaredlll08** [comment]
So the issue with this is that @RWTema coded this machine differently from the rest, removing a recipe isn't possible with how it's setup :(
