### ISSUE TITLE
TE Support for Precipitator & Extruder

### ISSUE THREAD

**Issue by superfluke** [jaredlll08/ModTweaker#576]
TE has updated their API to allow for recipe additions/removals to the [Igneous Extruder](https://github.com/CoFH/ThermalExpansion/blob/1.12/src/main/java/cofh/thermalexpansion/util/managers/machine/ExtruderManager.java) and [Glacial Precipitator](https://github.com/CoFH/ThermalExpansion/blob/1.12/src/main/java/cofh/thermalexpansion/util/managers/machine/PrecipitatorManager.java). Would be nice to see some support for them, since craft tweakable machines that perform a similar function are pretty rare.

**Comment by jaredlll08** [comment]
Closed on accident

**Comment by jaredlll08** [comment]
Looking at it, while it is possible to add recipes, it is not possible to remove them.

@KingLemming I noticed you left the methods commented out, if implement them, mind giving me a ping? thanks!

**Comment by KingLemming** [comment]
Yeah, will do. I'm reworking a bit of functionality and am swamped with RL stuff so it won't be any time soon I'm afraid.

**Comment by Draskh** [comment]
Is the removal method now integrated?
