### ISSUE TITLE
Update TE compactor with new gear recipes

### ISSUE THREAD

**Issue by superfluke** [jaredlll08/ModTweaker#577]
Recent TE update has added a fourth compactor recipe type: [gears](https://github.com/CoFH/ThermalExpansion/blob/1.12/src/main/java/cofh/thermalexpansion/util/managers/machine/CompactorManager.java#L64). Seems like this support for this could be added pretty easily.

**Comment by jaredlll08** [comment]
closed by
https://github.com/jaredlll08/ModTweaker/commit/9bea43c80e64f83aa1fa4e2045051f68f5f0833a
