### ISSUE TITLE
Not removing recipes without an addition 

### ISSUE THREAD

**Issue by Y0ungSandwich** [jaredlll08/ModTweaker#578]
#### Issue Description:
It seems recipes, in any script, that are being removed with no added shaped or shapeless recipe do not
get removed at all on servers. Client is working fine. This works as intended on forge 14.23.1.2555 but doesn't appear to work on anything after that.

#### What happens:
Recipes being removed with no added shaped or shapeless recipe remain craftable on servers. 

#### What you expected to happen:
Intended removed recipes not craftable. 

#### Script used 
https://pastebin.com/3NVZGuKA

#### Minetweaker.log file 
https://pastebin.com/ZFeeD1Tq

____
#### Affected Versions 

- Minecraft:1.12.2
- Forge: 14.23.1.2556+
- Crafttweaker: CraftTweaker2-1.12-4.0.12
- ModTweaker :modtweaker-4.0.6
- MTLib:  MTLib-3.0.1

Also to note this is running Mech & Magic v.2.0.0 on the ATLauncher.
#### Your most recent log file where the issue was present: 
NOTE: This server is running sponge BUT the first thing I had done was test with and without sponge on both linux and windows with no change in the issue. 
https://pastebin.com/UeyqGV93

**Comment by jaredlll08** [comment]
Do the client and server have the exact same scripts?

**Comment by Y0ungSandwich** [comment]
No as the items being removed are for server stability. i.e. Chunkloaders, weather changers, claim griefing, etc

**Comment by jaredlll08** [comment]
Scripts are no longer sent to the client.
