### ISSUE TITLE
Integration for Pure Daisy - Items with Meta Data do not work

### ISSUE THREAD

**Issue by DJJBanx** [jaredlll08/ModTweaker#579]
#### Issue Description:
Mod Tweaker integration for Pure Daisy

Botania integration for Pure Daisy doesn't seem to work with meta data
Here is my script:
**mods.botania.PureDaisy.addRecipe(<xtones:zome:15>, <xtones:zome:12>, 1200);**
what displays in game is 
**mods.botania.PureDaisy.addRecipe(<xtones:zome>, <xtones:zome>, 1200);**
JEI shows the block xtones:zome with no meta data (or a meta data of 0) turning into the block with no meta data
And when **<xtones:zome:*>** is placed next to the pure daisy it only ever turns into **<xtones:zome:0>**
The block with any meta data turns into the block with no meta data.

Instead of ignoring meta data and creating the default block, it should apply meta data and give the block specified.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/gb7esLSX

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/Fp1V5cCX

#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.1.2583
- Crafttweaker: 4.0.10
- ModTweaker: 4.0.6
- MTLib: 3.0.1

#### Your most recent log file where the issue was present: 

https://gist.github.com/DJJBanx/7ba02d546e7e43021a6a1acb79a6425c

**Comment by DJJBanx** [comment]
Can confirm it is not XTones.
Same script does not work with <minecraft:log:1>

**Comment by jaredlll08** [comment]
complain on the botania issue tracker, they are only checking for the base block, regardless of metadata

**Comment by Zer0Lyfe** [comment]
@jaredlll08 https://github.com/Vazkii/Botania/issues/2501 it has been fixed but williewillus said modtweaker will need to update to pass an IBlockState, after the next Botania version has been released.
