### ISSUE TITLE
Petal Apothecary: Items Besides Petals

### ISSUE THREAD

**Issue by DJJBanx** [jaredlll08/ModTweaker#580]
#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

mods.botania.Apothecary.addRecipe(<minecraft:reeds>, [<minecraft:melon>, <minecraft:melon>,
  <minecraft:melon>, <minecraft:melon>]);

#### What happens:

Melons just drop on top of the petal apothecary.

#### What you expected to happen:

Melons should go into the petal apothecary to craft the sugar cane. (Similar to how petals go into the petal apothecary)

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/imtbCiyW

#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.1.2585
- Crafttweaker: 4.0.12
- ModTweaker: 4.0.6
- MTLib: 3.0.1

#### Your most recent log file where the issue was present: 

https://pastebin.com/7apZQh23

**Comment by jaredlll08** [comment]
The PETAL apothecary is hardcoded to only accept PETALS.
