### ISSUE TITLE
[Help/Request] Removing Modifiers from Tinker's updated to 1.12

### ISSUE THREAD

**Issue by ChaseRox** [jaredlll08/ModTweaker#581]
In older versions of ModTweaker we could remove Modifiers like Luck from Tinker's. I've tried the old scripts for removing them but don't seem to work so I don't know if the code has been updated or if this feature has not been updated 1.12.

**Comment by Zer0Lyfe** [comment]
I believe this mod: https://www.curseforge.com/minecraft/mc-mods/tinkersextras can do that.

**Comment by jaredlll08** [comment]
Tinker's uses ImmutableLists for this kind of stuff, I don't really want to go messing with them, and the other mod already exists.
