### ISSUE TITLE
[1.6.4] ModTweaker and Minetweaker

### ISSUE THREAD

**Issue by Pilad** [jaredlll08/ModTweaker#582]
ModTweaker-1.6.4-0.3 not work with latest MineTweaker3-1.6.4-3.0.9C.
In console : 2018-01-10 10:18:17 [SEVERE] [ForgeModLoader] The mod ModTweaker (ModTweaker) requires mods [MineTweaker] to be available
Please fix this.

**Comment by jaredlll08** [comment]
1.6.4 hasn't been supported for MANY years

**Comment by Pilad** [comment]
I understand it. But I hoped that they would correct this mistake. MineTweaker-1.6.4-2.3.1 is not very user-friendly in comparison with the latest version. Can still look at the code? You are good at java, and it will not be difficult for you to fix this. Thank you.

**Comment by jaredlll08** [comment]
No. I don't even have 1.6.4 code for modtweaker, and like I said, it's not
supported.
