### ISSUE TITLE
[Request] Tinker's Casting - additional argument to support casting times?

### ISSUE THREAD

**Issue by KAfable** [jaredlll08/ModTweaker#583]
#### Issue Description: 
Would it be possible to add an additional argument to the table and basin casting recipes that let's us specify cooldown times?

From what I understand so far is that the cool down time is mostly based on the temperature of the fluid. However in my pack I wanted there to be a progressive way of cooling down items, and wanted to increase the casting time if just using a plain old casting table. The only way to do that at the moment is to crease the temperature of the fluid, like molten iron. However this might have an unintended result such as causing Thermal Fluiducts to blowup even faster due to the high heat, or other side effects.

I was wondering if there was a way to directly insert an time argument into the recipe and have it use that instead. This can allow me to have different cooling times depending on the types of cast I use for example.

**Comment by DJJBanx** [comment]
To add on to this:

Tinkers Construct already has support for custom casting times, it would only take the addition of another Zen Method that has optional parameter time

```
public CastingRecipe(ItemStack output, RecipeMatch cast, Fluid fluid, int amount, int time) {
    this(output, cast, new FluidStack(fluid, amount), time, false, false);
  }
```

https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/library/smeltery/CastingRecipe.java
