### ISSUE TITLE
I know I am doing something wrong... but what?

### ISSUE THREAD

**Issue by beesyndicate** [jaredlll08/ModTweaker#585]
Hello everyone,
So I am attempting to remove Thermal expansion coins.
I created a mint.zs
it contains
mods.thermalexpansion.Compactor.removeMintRecipe(<thermalfoundation:coin:1>);
as far as I can tell this should remove the gold coin but in my single player testing world i can still craft gold coins in the compactor with the mint augment.
/ct syntax says that it has no errors.
I assume I am missing something.
any help would be appreciated.

Thanks,

Bee

**Comment by jaredlll08** [comment]
Use the issue template.
