### ISSUE TITLE
Carpenter fluids (SERVER)

### ISSUE THREAD

**Issue by Ueaj-Kerman** [jaredlll08/ModTweaker#587]
#### What happens: (ON SERVER!)
(Mod tweaker) I should post it there but I was wondering if anyone knew.
When I add a recipe that has a NON-whitlisted fluid for the carpenter in forestry I am unable to put that
fluid into the carpenter.
I know there is a way because the modpack creator or AoE did it with nutrient distillation.

#### What you expected to happen:
Auto-add the fluid as whitelist?

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/QGH7unhj

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
Its on my server.
And I'm not sure its needed?
I guess its not a bug? not sure.

**Comment by jaredlll08** [comment]
Use the template.

Right now I don't know what you have tried, what game version, what Crt version, what modtweaker version or anything like that.

Also have you tried asking the AOE dev?
