### ISSUE TITLE
Recipe addition mods.extrautils2.Crusher secondaryOutput does not seem to work, parsing error.

### ISSUE THREAD

**Issue by kingdadrules** [jaredlll08/ModTweaker#589]
#### Issue Description:
All additions to EU2 crusher using only the primary output work OK.
 I can't get it to work with any combination of optional secondary output / secondary chance.. craftweaker throws a parsing error.

For example, it does not work when using the example supplied EU2 crusher addition code from the Crafteaker wiki Modtweaker pages:

mods.extrautils2.Crusher.add(<minecraft:gold_ingot> * 9, <minecraft:gold_block>, <minecraft:iron_ingot>, 0.1f);

#### What happens:

Craftweaker throws a parsing error.

#### What you expected to happen:
Crusher recipe to be added to the EU2 crusher to convert 9 gold ingots into 1 gold block, with a one in ten chance of a bonus iron ingot.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/yXHq8CS9

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/afawtqQv

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.1.2555 
- Crafttweaker:  1.12-4.0.7
- ModTweaker: 1.12.2
- MTLib: 1.12.2

extrautils2: 1.12-1.7.2

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

I will attach logs if requested.

**Comment by jaredlll08** [comment]
Your Syntax is wrong, do
```0.1 as float```
