### ISSUE TITLE
Trying to import Tinker's Materials gives an error

### ISSUE THREAD

**Issue by Insane96** [jaredlll08/ModTweaker#592]
#### Issue Description:
Trying to import Tinker's Materials gives an error

#### What happens:
 When I try to import

`import modtweaker.materials.ITICMaterial;`
 it gives me an error
`[INITIALIZATION][CLIENT][ERROR] tinker.zs:1 > No such member: materials`

#### What you expected to happen:
No errors

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/VaD0FQ1A

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/WNX0bcT1

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.1.2608
- Crafttweaker: 4.1.0
- ModTweaker: 4.0.6
- MTLib: 3.0.1

**Comment by jaredlll08** [comment]
woops, that is a typo on the wiki, the correct import is:
```
modtweaker.tconstruct.ITICMaterial
```
thanks for pointing it out!

**Comment by Insane96** [comment]
Still a problem. After fixing the import now I get 
`[INITIALIZATION][CLIENT][ERROR] tinker.zs:3: Could not resolve <material : stone>`

**Comment by Insane96** [comment]
Managed to fix it.
Another typo is that is not `material:material_name` but `ticmat:material_name`
