### ISSUE TITLE
[Suggestion] Add a method to change mining levels name for TiC

### ISSUE THREAD

**Issue by Insane96** [jaredlll08/ModTweaker#594]
#### Issue Description:
I'm creating a modpack and I've changed the mining level of some tools, but they're tooltip's not right (like the flint pickaxe can only mine Copper, but the tooltip says Iron, or the Cobalt pickaxe has no name, it just says 6).
So a way to change the mining level name, if possible, would be really cool.

**Comment by KalaMiDeviL** [comment]
Oh yes! I second that!

**Comment by Insane96** [comment]
Not needed: https://github.com/SlimeKnights/TinkersConstruct/wiki/Overwriting-Harvest-Levels
