### ISSUE TITLE
Botania PureDaisy metaID ignored

### ISSUE THREAD

**Issue by Thyriel** [jaredlll08/ModTweaker#596]
#### Issue Description:
adding PureDaisy recipes with meta blocks does not work

#### What happens:
Recipe is added with meta 0

#### What you expected to happen:
recipe added with specified meta id

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/iX2LcS0j
That should convert coarse dirt to red sand, instead it adds dirt > sand recipe

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2611
- Crafttweaker: 4.1.2
- ModTweaker: 4.0.6
- MTLib: 3.0.1

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
Fixed in dev.
