### ISSUE TITLE
[Request] Act. Adds. Manual Editting

### ISSUE THREAD

**Issue by ElvenChaos** [jaredlll08/ModTweaker#597]
#### Issue Description:
When changing a basic recipe for an Actually Additions item, the recipe is successfully changed. However, the recipe is not reflected in the Act. Adds. manual. Would you be willing to implement a method(s) that allow the alteration of the Act. Adds. manual?

Issue from Act. Adds. Repository: https://github.com/Ellpeck/ActuallyAdditions/issues/1026

#### What happens:
Crafting recipe changes, not reflected in book.

#### What you expected to happen:
Crafting recipe changes, reflected in book.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://gist.github.com/ElvenChaos/e6862bb5e1f1bd8d1aa80ee4184e4860

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2611
- Crafttweaker: 4.1.2
- ModTweaker: 4.0.6
- MTLib: 3.0.1

**Comment by jaredlll08** [comment]
Manual editing is out of scope for Modtweaker right now, the only reason that that Botania lexicon editing is because it was grandfathered in.
