### ISSUE TITLE
Thermal Expansion Compactor Gear recipe not working..

### ISSUE THREAD

**Issue by Tedyhere** [jaredlll08/ModTweaker#599]
#### Issue Description:
Trying to add a recipe for making gears using custom items in the compactor but it doesn't work properly.

#### What happens:
ERROR: gears.zs:3 > No such static member in mods.thermalexpansion.Compactor: addGearRecipe

#### What you expected to happen:

a gear recipe to be added

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/wyzJFTvR

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.2.2613
- Crafttweaker: 1.12-4.1.2
- ModTweaker: 4.0.6
- MTLib: 3.0.1

#### Your most recent log file where the issue was present: 

https://pastebin.com/GagG6g6d

**Comment by jaredlll08** [comment]
The support is in, but it isn't released

**Comment by Tedyhere** [comment]
Well poop! I saw it on readthedocs Wiki so figured it was released :P
