### ISSUE TITLE
CT not removing recipes.

### ISSUE THREAD

**Issue by BigAl607** [jaredlll08/ModTweaker#600]
I'm trying to remove the solderer recipes for the crafting grid, pattern grid & fluid grid from refined storage. Using this code:

`mods.refinedstorage.Solderer.removeRecipe(<refinedstorage:grid:1>);
mods.refinedstorage.Solderer.removeRecipe(<refinedstorage:grid:2>);
mods.refinedstorage.Solderer.removeRecipe(<refinedstorage:grid:3>);`

Recipes aren't being removed, and in the crafttweaker.log file I get the following lines:

`[INITIALIZATION][CLIENT][INFO] Removing 0 Solderer Recipe(s) for Unknown item
[INITIALIZATION][CLIENT][INFO] Removing 0 Solderer Recipe(s) for Unknown item
[INITIALIZATION][CLIENT][INFO] Removing 0 Solderer Recipe(s) for Unknown item`

I also get this and the one solderer recipe I added:

`[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Solderer with name ct_shaped2005293010`

**Comment by jaredlll08** [comment]
Use the template. I need your versions and log files uploaded somewhere.

**Comment by BigAl607** [comment]
MC 1.12.2

CT version 4.1.3

crafttweaker.log: https://pastebin.com/0PyzZU9A

**Comment by jaredlll08** [comment]
It's fixed, wait for next release

**Comment by BigAl607** [comment]
Awesome. Thank you very much!
