### ISSUE TITLE
[Question] How to remove recipe from ThermalExpansion Induction Smelting by ore dict?

### ISSUE THREAD

**Issue by KorDum** [jaredlll08/ModTweaker#603]
#### Issue Description:
I have ImmersiveEngineering and ThermalExpansion (+Foundation of course) and 2 recipes for nickel ore:
![image](https://user-images.githubusercontent.com/1331559/36339609-a3585c98-13da-11e8-8891-7c4ac0f20c3c.png)
![image](https://user-images.githubusercontent.com/1331559/36339615-c4fa6378-13da-11e8-87c5-db1924c10dba.png)

How can I remove these recipes? I getting some errors:
![image](https://user-images.githubusercontent.com/1331559/36339676-023bf296-13dc-11e8-9057-424586b8038f.png)

#### Script used:
I tryed this https://gist.githubusercontent.com/KorDum/74a556c0c27eca5e495a2554555ea586/raw/2325dbb8fb12b662bfa20ded8513b0843b31f3d8/gistfile1.txt

____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.2.2611
- Crafttweaker: 4.1.3
- Modtweaker: 4.0.7

**Comment by jaredlll08** [comment]
I need your log.

**Comment by KorDum** [comment]
https://gist.github.com/KorDum/f6549d68537b5b9a85e920721b0d794e
Will this help you?

**Comment by jaredlll08** [comment]
no. The Crafttweaker log, that was asked for in the initial issue template...

**Comment by KorDum** [comment]
Oh sorry, my mistake.
https://gist.github.com/KorDum/ea9230f2b6882c2492cb7e67114661ff

**Comment by jaredlll08** [comment]
You are aware that the syntax is:
```
removeRecipe(IItemStack primaryINPUT, IItemStack secondaryINPUT);
```
right?
thermalfoundation:material:133 is the nickel ingot, which is the output.

As for removing via oredict, ThermalExpansion doesn't give us the option to do that.

**Comment by KorDum** [comment]
Thank you! And I break my head and think what I did wrong!
The first line of script is enough to implement the requested one.
