### ISSUE TITLE
[Request] Even more Thermal Expansion support

### ISSUE THREAD

**Issue by Skillotic0703** [jaredlll08/ModTweaker#606]
There are augments in Thermal Expansion that modify the recipes of a machine. For example the tectonic initiator changes the Pulverizer's recipes. It makes so that the Pulverizer consumes 100mB of tectonic petrotheum to process each ore but it produces more gems/dusts.
Here is the list of augments which need special support:

- [ ] Trivection Chamber (Redstone Furnace)
- [ ] Flux Anodizers (Redstone Furnace)
- [ ] Pyrolytic Conversion (Redstone Furnace)
- [ ] Tectonic Initiator (Pulverizer)
- [ ] Resin Funnel (Sawmill)
- [ ] Pyro-Concentrator (Induction Smelter)
- [ ] Sapling Infuser (Phytogenic Insolator)
- [ ] Numismatic Press (Compactor)
- [x] Gearworking Die (Compactor)
- [ ] Enstabulation Apparatus (Centrifugal Separator)

**Comment by jaredlll08** [comment]
After looking into it, none of those are really easily changeable, especially not the ones that do predefined things such as "increase ore output".

**Comment by arm32x** [comment]
I need to change a Pyrolytic Conversion recipe for my modpack, and the only other options is to completely remove the Pyrolytic Conversion augment.

Support, but maybe not for unchangeable ones like the Tectonic Initiator.

**Comment by arm32x** [comment]
I need to change a Pyrolytic Conversion recipe for my modpack, and the only other options is to completely remove the Pyrolytic Conversion augment.

Support, but not for unchangeable ones like the Tectonic Initiator.

**Comment by jaredlll08** [comment]
None of them are changeable, the ones that were, I marked as such -_-
