### ISSUE TITLE
BWM, unable to remove stoked crucible recipe based on input

### ISSUE THREAD

**Issue by stohun01** [jaredlll08/ModTweaker#608]
#### Issue Description:
Ineffective ZenSetter

#### What happens:
no effect

#### What you expected to happen:
the 6 powered rails to 6 gold ingots recipe to be removed based on the input item

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/V58GRyvs

line 325:
`mods.betterwithmods.StokedCauldron.remove(<minecraft:gold_ingot>*6, [<minecraft:golden_rail>*6]);`

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.2.2619
- Crafttweaker: 4.1.5
- ModTweaker: 4.0.7
- MTLib: 3.0.2

**Comment by jaredlll08** [comment]
1) You didn't give us the log.
2) I can't find that recipe in game, so I can't test, are you sure that it exists?
3) does using `mods.betterwithmods.StokedCauldron.remove(<minecraft:gold_ingot>);` work?

**Comment by stohun01** [comment]
Sorry, I confused Stoked Crucible with Stoked Cauldron. Even so it's still causing an error
[Log](https://pastebin.com/KfvdbLe9)
[Script](https://pastebin.com/eTCCZCji) line 333

This line will successfully remove all stoked crucible recipes that output a gold ingot
`mods.betterwithmods.StokedCrucible.remove(<minecraft:gold_ingot>);`

But when replaced with this it causes an error
`mods.betterwithmods.StokedCrucible.remove(<minecraft:gold_ingot>,[<minecraft:golden_rail>]);`
