### ISSUE TITLE
[1.12.2] Can't remove recipe from mods.thermalexpansion.Transposer

### ISSUE THREAD

**Issue by KorDum** [jaredlll08/ModTweaker#611]
#### What happens:
Errors while load script.
https://gist.github.com/KorDum/d34fa2aea2c48c1545f4556df081a0a6

#### Script used
https://gist.github.com/KorDum/f70d4a25a3d4d4d7e2b149806a344a11

#### Minetweaker.log file
https://gist.github.com/KorDum/9cfbbf8cc253b07c4827676d4ffc2161

____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.2.2611
- Crafttweaker: 4.1.5
- ModTweaker: 4.0.8
- MTLib: 3.0.3

**Comment by jaredlll08** [comment]
Don't give us the relevant lines. Give us the full script.

**Comment by KorDum** [comment]
Full script.
https://gist.github.com/KorDum/c0fbc741378fa479bbf93fb1f1a4e310

**Comment by jaredlll08** [comment]
The issue is that you are calling a method that doesn't exist. Read the docs.

**Comment by KorDum** [comment]
```
//mods.thermalexpansion.Transposer.removeExtractRecipe(IItemStack input);
mods.thermalexpansion.Transposer.removeRecipe(<minecraft:gold_ore>);

//mods.thermalexpansion.Transposer.removeFillRecipe(IItemStack input, ILiquidStack fluid);
mods.thermalexpansion.Transposer.removeRecipe(<minecraft:bucket>, <liquid:water>);
```
https://crafttweaker.readthedocs.io/en/latest/#Mods/Modtweaker/ThermalExpansion/Fluid_Transposer/
Please fix error in doc example.
