### ISSUE TITLE
Forestry support carpenter issue

### ISSUE THREAD

**Issue by gdarai** [jaredlll08/ModTweaker#612]
#### Issue Description:
Forestry hook works wrongly:
When trying to add nonstandart fluid to carpenter, only newly placed carpenter accepts the fluid.

#### What happens:
- I created a test pack, with forestry and modtweaker (Full list is forestry, modtweaker, crafttweaker and mtlib, JEI) - JEI must be there, otherwise mod tweaker returns `error mezz/jei/api/recipe/irecipewrapper`
- I added simple script wth one line:
`mods.forestry.Carpenter.addRecipe(<minecraft:bucket>, [[<minecraft:stick>, null, null], [null, null, null], [null, null, null]], 20, <liquid:milk> * 500, <forestry:waxCast>);` (This was minimalistic example. so this IS the full script)
- I enter the game and try to insert the milk into the carpenter.
- It works
- It is even visible that milk is now valid fluid for carpenter and the JEI see the receipt.
- I save the game and load it again (just there and back in the menu, no need to turn off the whole game)
- Now the carpenter does not accept milk any more, the tooltip does not show milk and only fix is to break the machine and replace it again.

What works as a fix is if I reload the script and break and replace the carpenter. Nothing less.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
 `mods.forestry.Carpenter.addRecipe(<minecraft:bucket>, [[<minecraft:stick>, null, null], [null, null, null], [null, null, null]], 20, <liquid:milk> * 500, <forestry:waxCast>);`
____
#### Affected Versions (Do *not* use "latest"): 

- Minecraft: 1.10.2
- Forge: 12.18.3.2511
- Crafttweaker: 3.0.26
- ModTweaker: 2.0.13
- MTLib: 1.0.3
- Forestry: 5.2.17.388

**Comment by jaredlll08** [comment]
1.10.2 isn't supported anymore.

**Comment by gdarai** [comment]
That is sad... since 1.10.2 has the most mods and most modsstill support it. Can you at least look at the issue and give me a hint if the problem is on your end or if guys from forestry can fix this?

Thanks for the quick response.

**Comment by gdarai** [comment]
I really tried and isolated in my whole modpack this single issue.

**Comment by jaredlll08** [comment]
It is probably a combination of both forestry and Modtweaker /
crafttweaker, and I can tell you that none of the mods you have installed
for this issue to happen support 1.10.2 anymore.
