### ISSUE TITLE
Chisel Support

### ISSUE THREAD

**Issue by Fortist** [jaredlll08/ModTweaker#616]
I cant seem to find the chisel section on the crafttweaker "read the docs" guide, and you luckly have examples for "Inspirations" here, at least.
Are they still the same as the Minetweaker codes?

**Comment by drakray** [comment]
Looking at [compat/chisel/Carving.java](https://github.com/jaredlll08/ModTweaker/blob/ea01a6e390ff77f52398fb7f026bcd3a672cf36c/src/main/java/com/blamejared/compat/chisel/Carving.java) , I think the new codes are:

```
mods.chisel.Carving.addGroup(String name);
mods.chisel.Carving.addVariation(String groupName, IItemStack stack);
mods.chisel.Carving.removeGroup(String name);
mods.chisel.Carving.removeVariation(String groupName, IItemStack stack);
```

with the command `/ct chiselGroups` to output Group Name in ctlog

EDIT: tested with `mods.chisel.Carving.addVariation("bloodMagic", <bloodmagic:blood_rune:0>);` is working :D

**Comment by HurtsAsHell** [comment]
Thanks, i love u!!

**Comment by jaredlll08** [comment]
https://github.com/CraftTweaker/CraftTweaker-Documentation/commit/61f1f3081c27cafab270e6d5a1528ed34d2df5a4
