### ISSUE TITLE
setEntryKnowledgeType takes priority before addEntry

### ISSUE THREAD

**Issue by kekvitirae** [jaredlll08/ModTweaker#617]
Adding mods.botania.Lexicon.addEntry and then adding mods.botania.Lexicon.setEntryKnowledgeType (even on a different file) returns an error that the new entry cannot be found due the setEntryKnowledgeType taking priority first in the initialization.

Script used: https://pastebin.com/zEnv2Y8j

Log file returns: https://pastebin.com/Luc9Fnrj

- Minecraft: 1.12.2
- Forge: x.2624
- Crafttweaker: 4.1.6
- ModTweaker: 4.0.8
- MTLib: 3.0.4

**Comment by jaredlll08** [comment]
No easy workaround in code, what you can do however is add nbt to the item itself instead of using this method
