### ISSUE TITLE
Avaritia extreme crafting recipes  not working.

### ISSUE THREAD

**Issue by Glebenator** [jaredlll08/ModTweaker#618]
Custom recipies for avaritia dont seem to work for me

`mods.avaritia.ExtremeCrafting.addShapeless(<projecte:transmutation_table>, [[<draconicevolution:chaotic_core>]]);
`
- Minecraft: 1.12
- Forge:
- Crafttweaker: 4.1.6
- ModTweaker: 4.0.8
- MTLib: 3.0.4

If somebody could send a pastable version of a working script, I should be fine)

**Comment by Glebenator** [comment]
Ok, I figured it out.
Here is a working version:
`mods.avaritia.ExtremeCrafting.addShapeless("YIKES", <projecte:transmutation_table>, [<draconicevolution:chaotic_core>]);`

**Comment by Lanse505** [comment]
Avaritia CraftTweaker support is Native to Avaritia not part of ModTweaker.
If you have an issue with their CrT implementation please go to their issue tracker for support:
https://github.com/Morpheus1101/Avaritia/issues
