### ISSUE TITLE
Thermal Expansion Compactor

### ISSUE THREAD

**Issue by donnerarsch** [jaredlll08/ModTweaker#619]
#### Issue Description:
Fail to remove recepies for Compactor Plate mode

#### What happens:
nothing -,-
 [crafttweaker]: Error executing {[0:crafttweaker]: Thermal\removed.zs}: com/blamejared/compat/thermalexpansion/Compactor$Remove

#### What you expected to happen:
Recepie remove for Enderium Plate

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/4GtgGvyf

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/dUb7Rq38

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.12.2
- Forge:1.12.2-14.23.1.2604
- Crafttweaker: 4.1.6.462
- ModTweaker:4.0.9
- MTLib:3.0.1

#### Your most recent log file where the issue was present: 

https://pastebin.com/dUb7Rq38

**Comment by jaredlll08** [comment]
update MTLib
