### ISSUE TITLE
TE Redstone Furnace recipe not being removed

### ISSUE THREAD

**Issue by Thedrummonger** [jaredlll08/ModTweaker#621]
#### Issue Description:
I have written a script to remove the furnace recipe that smelts dry rubber from industrial forgoing into plastic. The log says the operation was successful, but after reloading the game the recipe still exists in JEI and works in the furnace. I also have a script that removes the smelting recipe for iron into tech reborn refined iron. This script works as intend and the recipe is removed, so it seems to only be happening with industrial foregoing.

#### What happens:

The recipe is not removed as intended.

#### What you expected to happen:

The recipe should be removed.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/nttKRLC6

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/zckejicz
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.2.2654
- Crafttweaker: 1.12-4.1.6
- ModTweaker: 4.0.10
- MTLib: 3.0.4

#### Your most recent log file where the issue was present: 

https://pastebin.com/BvXny0nU

**Comment by jaredlll08** [comment]
The recipe is an oredict recipe, so its not being removed, you would need to use `<ore:rubber>.firstItem`, I'm not sure if that oredict is correct though, just check it beforehand
