### ISSUE TITLE
Thermal Expansion compatibility issues

### ISSUE THREAD

**Issue by BaseCrusher** [jaredlll08/ModTweaker#622]
#### What happens:
So, as already seen in the issue tracker, there are a few issues with Thermal Expansion. 
For one there are some recipes in every machine, that you can't remove. But there are no errors in the log and in the ingame chat. And since most of the recipes are being removed I'm not sure if it's ModTweakers fault. 
I supose that ModTweaker has a hard time removing other mods recipes that being implemented in Thermal Expansion and there seems to be some recipes that are hardcoded by Thermal expansion.

Example Script:
https://pastebin.com/HiKir8Vs

CraftTweaker Log:
https://pastebin.com/dK0sbyyP

- Minecraft: 1.12.2
- Forge: 14.23.2.2652
- Crafttweaker: 4.1.5
- ModTweaker: 4.0.10
- MTLib: 3.0.2

Forge/Minecraft Log:
https://pastebin.com/6hf67qRz

**Comment by jaredlll08** [comment]
I don't know about the other mods, but if there aren't any errors, it means the recipe exists and that it has been removed, if it hasn't been removed then it is out of my hands, either mods registering stuff too late or just TE not removing them

**Comment by PanSzelescik** [comment]
Easy fix:

Wrong:
`mods.thermalexpansion.InductionSmelter.removeRecipe(<thermalfoundation:material:768>, <thermalfoundation:material>);`

Good:
`mods.thermalexpansion.InductionSmelter.removeRecipe(<thermalfoundation:material>, <thermalfoundation:material:768>);`

I don't know but it's working
