### ISSUE TITLE
[Request] Null recipe bypass for dump?

### ISSUE THREAD

**Issue by irish-brigid** [jaredlll08/ModTweaker#623]
This is a request concerning recipe dumps.

`/minetweaker recipes`

The above command results in an unknown error. Apparently, the cause is one or more recipes with a null output which halts the dump. This means I get only a partial list of recipes in the log.

What I'd like to know is if there's any way to identify those null-output recipes and bypass them so I can get the rest of the recipes. I'd rather not have to copy all of them by hand.
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.7.10
- Forge: 10.13.4.1558
- Minetweaker: 3.0.10B
- ModTweaker: NA
- MTLib: NA

**Comment by jaredlll08** [comment]
No way to solve.
