### ISSUE TITLE
Bloodmagic Hellfire Forge

### ISSUE THREAD

**Issue by MasterEnderman** [jaredlll08/ModTweaker#624]
#### Issue Description:

Recipes are removed, but they still show up in JEI.

#### What you expected to happen:

The removed recipes, won't show up in JEI.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/4FxNiJ0R

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.2.2654
- Crafttweaker: 4.1.6
- ModTweaker: 4.0.10
- MTLib: 1.5.6

**Comment by jaredlll08** [comment]
I don't handle Jei removal. It's upto the mods to sort that out (which they shouldn't need to as my stuff runs before that)
