### ISSUE TITLE
[REQUEST] Thaumcraft Support

### ISSUE THREAD

**Issue by Sunconure11** [jaredlll08/ModTweaker#628]
Now that Thaumcraft is out on 1.12.2, would it be possible to revive Thaumcraft support?

**Comment by Hillage** [comment]
Just putting a comment here, I'm waiting on Thaumcraft support too, and I see commits being pushed with updates. Patiently waiting, I/we appreciate the dev work being done. :)

**Comment by Geethebluesky** [comment]
TC 6 is on beta 12 now and playable almost to the end, very much requesting support for it please :)

**Comment by Hillage** [comment]
Saw dev's comment about being swamped with uni work a few days ago. Support is coming, but uni comes first :)

Appreciate the support from modtweaker, looking forward to being able to make custom infusion recipes :P

**Comment by jaredlll08** [comment]
I *think* I actually just finished the support 2 minutes ago :p probably forgot something, but lets see
I should say, I'm not doing thaumanomicon code, you guys will be stuck there unfortunately, the api for everything else is just such a mess, I don't even want to imagine the gui stuff.

**Comment by Geethebluesky** [comment]
The main thing is probably the aspects for mods that don't want to / don't know how to integrate them themselves, I don't know what anyone would want to tweak other than that...! :)

**Comment by Hillage** [comment]
Wow, that's awesome. Thanks!
