### ISSUE TITLE
New version of Thermal Expansion

### ISSUE THREAD

**Issue by JWTHDYTWA** [jaredlll08/ModTweaker#629]
#### Issue Description:
It looks like newest version of Thermal Expansion (5.4) is no longer compatible with ModTweaker.

#### What happens:
Minecraft crashes at game's final loading stage.
Here is crashlog: [📦](https://gist.github.com/Warrock3280/cc4981473e5ab723a54b1d9ecd9743d3)

#### Script used:
<s>https://gist.github.com/Warrock3280/610f536212a7237983a8fc7765d37635</s> Probably not needed.

#### Minetweaker.log file:
<s>https://gist.github.com/Warrock3280/85f60801a6d91bf0253ed93e6d53d50c</s> It is not even getting updated in this case.

____
#### Affected Versions:
- Minecraft: 1.12.2
- Forge: 2673
- Crafttweaker: 4.1.8
- ModTweaker: 4.0.10
- MTLib: 3.0.4
- COFH Core: 4.4.0.10
- Thermal Expansion: 5.4.0.20

**Comment by MasterEnderman** [comment]
Another Crash Report: https://pastebin.com/AyHS2dYy

**Comment by jaredlll08** [comment]
fixed by pr
