### ISSUE TITLE
Changed method in Thermal Expansion 5.4.0 no longer recognized

### ISSUE THREAD

**Issue by VersilPerihelion** [jaredlll08/ModTweaker#630]
#### Issue Description:

ModTweaker seems to no longer be compatible with Thermal Expansion 5.4.0 from 2018/04/25.

#### What happens:

Fatal error during "available", NoSuchMethodError thrown. Looking up TE's source code and commit history points to the method having changed the number of arguments taken in the most recent update. Crash log and the link to the commit from TE's repo below. There could be other methods that were changed and are no longer recognized, but I can't tell for sure beyond what I came across.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.2.2611
- Crafttweaker: 4.1.3, 4.1.8
- ModTweaker: 4.0.7, 4.0.10
- MTLib: 3.0.2, 3.0.4
- CoFHCore: 4.4.0
- Thermal Expansion: 5.4.0
(multiple version numbers come from having the earlier version first and then updating to see if it solves the problem before writing the issue)

#### Your most recent log file where the issue was present, plus relevant links: 
Crash log:
https://pastebin.com/fLrJJB5k

Link to the likely cause of the issue in TE commit history:
https://github.com/CoFH/ThermalExpansion/commit/9cad65854f1b56ef460921ec7ba328cc357c302c#diff-8eee56a3f908df4a5a14cf357b55bbdb

**Comment by jaredlll08** [comment]
fixed by pr
