### ISSUE TITLE
Compactor package no longer working after Thermal Expansion update

### ISSUE THREAD

**Issue by dash16** [jaredlll08/ModTweaker#631]
#### Issue Description:
Compactor recipes aren't working after Thermal Expansion updated to 5.4.0.20.  This is likely due to how the Compactor removed alternate modes in favor of only performing whatever action the augment installed does.  For instance, having no augment installed gives you Press Mode, Numistatic Press installed gives you Mint Mode, Gearworking Die installed gives you Gear Mode.  Storage Mode has been removed entirely (seemingly moving that function to the new Factorizer device)

#### What happens:

ERROR: [crafttweaker]: Error executing {[0:crafttweaker]:ThermalExpansion.zs}: MINT

#### What you expected to happen:

I suppose ModTweaker will need to be updated to account for how the Compactor works in 5.4.0.20

#### Script used:

https://pastebin.com/W1ST7vQX

#### Minetweaker.log file:

https://pastebin.com/JW9fJ9eb
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.2.2635
- Crafttweaker: 4.1.8
- ModTweaker: 4.0.10
- MTLib: 3.0.4

**Comment by KingLemming** [comment]
Yeah sorry about that. Entirely my fault. :/

**Comment by jaredlll08** [comment]
@KingLemming it's fine, I'm just swamped with uni work atm so can't update

If you want to make up for it though, looking into this would be nice https://github.com/jaredlll08/ModTweaker/issues/632

I'm fairly sure it isn't on my side (like I just pass arguments to your api, so I don't know where I could go wrong) https://github.com/jaredlll08/ModTweaker/blob/1.12/src/main/java/com/blamejared/compat/thermalexpansion/Enchanter.java#L46

**Comment by jaredlll08** [comment]
fixed by pr

**Comment by Spodi** [comment]
Maybe I'm dumb but i can't remove coin recipes from the compactor via press upgrade.

**Code Snippet:**
import mods.thermalexpansion.Compactor;
Compactor.removePressRecipe(<ore:ingotGold>.firstItem);

**Log Snippet:**
[AVAILABLE][CLIENT][INFO] Altering Compactor Recipe(s) for <minecraft:gold_ingot> in mode: ALL
[AVAILABLE][CLIENT][ERROR] No Compactor recipe exists for: 1xitem.ingotGold@0

**Complete Script:**
https://pastebin.com/WCwu0M6u
Complete Log:
****https://pastebin.com/Rv10rQD3

**Versions:**
Minecraft: 1.12.2
ThermalFoundation: 2.6.1.22
ThermalExpansion: 5.5.2.39
CraftTweaker2: 4.1.13
modtweaker: 4.0.15
MTLib: 3.0.5
