### ISSUE TITLE
Turntable recipe not working

### ISSUE THREAD

**Issue by Davoleo** [jaredlll08/ModTweaker#636]
#### Issue Description:
Better with mods turntable recipe doesn't show up

#### What happens:
Recipe doesn't work and doesn't show up in JEI

#### What you expected to happen:
I expected the script to work

#### Minetweaker.log file: https://paste.ee/p/Gw7LL

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2678
- Crafttweaker: 4.1.8
- ModTweaker: 4.0.10
- MTLib: 3.0.4

#### Your most recent log file where the issue was present: 

https://paste.ee/p/TBEgS

**Comment by jaredlll08** [comment]
Don't lie to me about version numbers.
1.10.2 isn't supported.

**Comment by Davoleo** [comment]
Wrong logs sorry
(those were from Age of Engineering)
Crafttweaker log is under the MC one: https://paste.ee/p/YLJ1Q

**Comment by jaredlll08** [comment]
Can't reproduce.
tested with:
`mods.betterwithmods.Turntable.add(<minecraft:dirt>, <betterwithmods:unfired_pottery:1>, [<minecraft:clay_ball>]);`

honestly I think some BWM stuff changed in dev, so the next MoT release may fix this

**Comment by Davoleo** [comment]
mmh, ok going to reply here if it doesn't work again
