### ISSUE TITLE
Some BwM Saw recipes are being skipped (1.12.2)

### ISSUE THREAD

**Issue by SeriousCreeper** [jaredlll08/ModTweaker#637]
#### What happens:
I added a few recipes to the Better with Mods saw, some are being added, others being skipped. 
Double checked the IDs and everything several time, unless i'm super blind, the syntax should be fine too (no complaint from the CraftTweaker log either)

#### Script used:
https://pastebin.com/7MsQGu8D 
The first two saw lines are the ones being added, the other ones afterwards are skipped.

#### Minetweaker.log file:
https://pastebin.com/bfZ5KH7E

____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 2678
- Crafttweaker: 4.1.8
- ModTweaker: 4.0.10
- MTLib: 3.0.4
- Better With Mods: 2.1.12

#### Your most recent log file where the issue was present: 
https://gist.github.com/Kiyaku/a2b55796b24391487193661e6a129a58

**Comment by jaredlll08** [comment]
Update modtweaker

**Comment by SeriousCreeper** [comment]
Ah thanks, didn't see there was a newer one than the one i used (stupid twitch launcher still not showing a new update available, really can't trust that thing heh).
