### ISSUE TITLE
/mt LexiconEntries Dosen't work

### ISSUE THREAD

**Issue by TehporP** [jaredlll08/ModTweaker#640]
#### Issue Description:
/mt LexiconEntries Dosen't work

#### What happens:
When I using this command,modtweaker tells me this command doesnt exsit

#### What you expected to happen:
show me every lexicon entries

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
no script used cuz it just a command

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/Hpym1qMH

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.7.10
- Forge:1.7.10-10.13.4.1614-1.7.10
- Crafttweaker: 3.0.13
- ModTweaker:0.96
- MTLib:none  cuz 1710 doesnt need MTLib

#### Your most recent log file where the issue was present: 
https://pastebin.com/33L7UC4v

**Comment by jaredlll08** [comment]
1.7.10 isn't supported.
