### ISSUE TITLE
[Question/Request] Thaumcraft Entity Aspect

### ISSUE THREAD

**Issue by drakray** [jaredlll08/ModTweaker#642]
First, thank you very much for the Thaumcraft Support, it work very nicely :D
My question/request is: is there a way to set aspect to Entities? I haven't found anything like that in the doc, and that would be very nice, epecially since the thaumometer make my game lag it's life when looking over modded entities that don't have aspect(which I get a LOT)
If that's not possible for the moment, I'll live, but will be sad ;) :P

**Comment by jaredlll08** [comment]
So I have no idea if this works, like when I scan an entity, it doesn't show it's aspects or anything of the sort, but I mean, it didn't crash, so woo?

**Comment by drakray** [comment]
i'll test that as soon as I can :)

**Comment by drakray** [comment]
any ETA on the build containing this? :)
