### ISSUE TITLE
[Question/Request] Thaumcraft Heat source/Infusion Stabilization listing/changing

### ISSUE THREAD

**Issue by drakray** [jaredlll08/ModTweaker#644]
Those two might be tricky, if ever possible.
A command to list Crucible Heat source and Infusion Stabilizer block with value?
Even harder, Crucible Heat source and Infusion Stabilizer add/remove function?

I think with this, most of Thaumcraft support would be complete, again, IF those are possible :)

**Comment by jaredlll08** [comment]
Unfortunately these are hardcoded as specific blocks, and while mods can implement some interfaces on their blocks to make it work, there isn't an actual registry for it.

**Comment by drakray** [comment]
Thanks for the quick answer :), that what I thought it'd be :'(
