### ISSUE TITLE
[Bug][Compat] Thaumcraft additional aspect

### ISSUE THREAD

**Issue by drakray** [jaredlll08/ModTweaker#645]
#### Issue Description:
I can't use aspect from other mod than Thaumcraft in setAspect, namely Tempus and Spatium from Planar Artifice.
Ingame, before restarting with the script, /ct syntax say everything is ok, and /ct thaumcraftdump list Tempus and Spatium as valid aspect.

#### What happens:

crafttweaker.log says "Could not resolve <aspect : Spatium>" and a bunch of Bytecode.

#### What you expected to happen:

To add Tempus and/or Spatium to items/blocks

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

[14-ThaumcraftPlanar.zs](https://pastebin.com/xBLnBe7J)

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://www.dropbox.com/s/jbrtyu69gs41vbh/crafttweaker.log

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2702
- Crafttweaker: 4.1.8
- ModTweaker: 4.0.12
- MTLib: 3.0.4

#### Your most recent log file where the issue was present: 

https://www.dropbox.com/s/jbrtyu69gs41vbh/crafttweaker.log

Relevant line:
l#526 : Could not resolve
l#7003 : ThaumcraftDump start
l#7249/50 : Aspect from Planar Artifice
l#8737-8779 : /ct syntax with no error

/ct hand on Spatium Vis crystal : <thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "Spatium"}]}), note the capital on key, hence why I tried capitalizing Spatium

**Comment by kindlich** [comment]
I could've sworn there was an issue template that tells people to post more information on what is not working as well as a logs, a simple script, MC info and the like.

**Comment by drakray** [comment]
sorry, i'll fix that when I get the necessary info, in a couple of minute

**Comment by drakray** [comment]
OP fixed, I hope everything is in order

**Comment by drakray** [comment]
strangely, near line 525, script is loaded with "Could not resolve", but Print Out are not

**Comment by jaredlll08** [comment]
so whatever mod is adding that aspect, is adding it after our scripts are ran, so it doesn't exist as script compile time, I'm sorry but there isn't a fix for this :(

**Comment by drakray** [comment]
Yeah that's what I thought, I'm moving that to Planar Artifice, asking if they can register their aspect sooner

**Comment by Geethebluesky** [comment]
@jaredlll08 changing mod load order doesn't fix this?

**Comment by jaredlll08** [comment]
Nope, there are different loading stages, we run our scripts early, authors
are adding aspects later.

**Comment by drakray** [comment]
@jaredlll08 is preinit soon enough to register aspect? [Thaumic Addition Reconstructed](https://github.com/Zeitheron/ThaumicAdditions/blob/be39462da20bb6309d15dd1e10c3f0afba01e89c/src/main/java/com/zeitheron/thaumicadditions/TAReconstructed.java) add some aspect in preinit. I can't test it for now, but with it's next version I will.

**Comment by jaredlll08** [comment]
Anything before Register<IRecipe> is good

**Comment by drakray** [comment]
oki, thanks :D
