### ISSUE TITLE
Unable to remove blood from Tinkers Smeltery

### ISSUE THREAD

**Issue by stohun01** [jaredlll08/ModTweaker#646]
#### Issue Description:
I'm trying to disable liquid blood from accumulating in the the smeltery from mobs. Neither of these seem to have any effect:
`mods.tconstruct.Melting.removeEntityMelting(entity);`
`mods.tconstruct.Melting.removeRecipe(<liquid:blood>);`

I also tried the following but for some reason this is able to add blood to the smeltery with a volume of 0, which also means it can't be removed without replacing the controller.
`mods.tconstruct.Melting.addEntityMelting(entity, <liquid:blood>*0); `

#### [Minetweaker log file](https://pastebin.com/NmLnPN05)

____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.4.2703
- Crafttweaker: 4.1.8
- ModTweaker: 4.0.12
- MTLib: 3.0.4
- Tinkers: 2.10.0.81
- Mantle: 1.3.2.24

**Comment by jaredlll08** [comment]
So you need to set the liquid to `null`, like `mods.tconstruct.Melting.addEntityMelting(entity, null);`, however...
This will error without the latest MTLib (releasing it now, will be 3.0.5), and even then, this is a TiC issue, if an entity is in the smeltery that doesn't have a fluid returned (null), then it defaults to blood
