### ISSUE TITLE
[1.7.10] Attempting to Add Thaumcraft Aspects to Mod Entities Results in an Error

### ISSUE THREAD

**Issue by Next-Door-Tech** [jaredlll08/ModTweaker#647]
#### Issue Description:

Adding Thaumcraft aspects to entities derived from the /mt entities command results in an error and a failure to change aspects.

#### What happens:

Using Tiny Bird from Twilight Forest as an example (the last line of my script), the log and chat echo "ERROR: No such entity twilightforest.entity.passive.EntityTFTinyBird"

The issue persists if "twilightforest.entity.passive.EntityTFTinyBird" is changed to the entity name "Tiny Bird" in the script.

mods.thaumcraft.Aspects.setEntity(); works just fine using the Minecraft example entities from the [wiki page](http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Thaumcraft_4_Support).

#### What you expected to happen:

Again, using Tiny Bird as an example, the aspects Aer x1, Volatus x1, and Best x1 would be added to the mob in game.

#### Script used:

https://gist.github.com/Cancun101/bbe1e635033089cfcb4438d177c17e57

#### Minetweaker.log file:

https://gist.github.com/Cancun101/07934a3b408e3d9a65232b1586116c98

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.7.10
- Forge: 10.13.4.1614
- CraftTweaker: 3.0.13
- ModTweaker: 0.9.6
- MTLib: N/A

#### Your most recent log file where the issue was present: 

Minecraft log:
https://gist.github.com/Cancun101/71c2a8fd62fedaad30239f6a619762a4
FML Client Log:
https://gist.github.com/Cancun101/c13c4d2f2f40e2c47be246eee2580a3b

**Comment by jaredlll08** [comment]
1.7.10 isn't supported.
