### ISSUE TITLE
[Feature Request] Mekanism Thermal Evaporation Recipe Conversion Speed Control

### ISSUE THREAD

**Issue by Dragnier** [jaredlll08/ModTweaker#650]
#### Issue Description:
Using Craft/Mod Tweaker, I've added a Mekanism Thermal Evaporation recipe. I would like to suggest adding a way to control how fast the Mekanism Thermal Evaporation conversion is.

#### What happens:
My custom recipe converts much more quickly than the basic Brine to Lithium recipe and I actually want it to be slower than that recipe.

#### What you expected to happen:
I expected the recipe to at least be the same speed as the Brine to Lithium recipe, not faster.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://gist.github.com/Dragnier/b1227b2062d5d7208f824ecd0502759b

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://gist.github.com/Dragnier/4f3fa63c06e2494c86aef310501eca4e
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2708
- Crafttweaker: 4.1.8
- ModTweaker: 4.0.12
- MTLib: 3.0.5
- Mekanism: 9.4.13.349

#### Your most recent log file where the issue was present: 

https://gist.github.com/Dragnier/a06fc3534c91c861241073e77efd6700

**Comment by jaredlll08** [comment]
We don't add support for Mekanism, they add support themselves.
