### ISSUE TITLE
Minecraft crashes on initial load

### ISSUE THREAD

**Issue by hagar-qim** [jaredlll08/ModTweaker#651]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker or ModTweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:
Minecraft crashes while loading. 

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
N/A;  mineTweaker doesn't get to handle scripts. The game crashes during initial loading.
Note that MineTweaker works fine without modTweaker

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
crafttweaker.log exists, but is empty

____
#### Affected Versions (Do *not* use "latest"):
- Minecraft: 1.12.2
- Forge: 14.23.4.2705  
- Crafttweaker:  4.0.3
- ModTweaker: 4.0.12
- MTLib: 3.0.5

#### Your most recent log file where the issue was present: 
[pastebin/gist/etc link here]
[latest.log](https://github.com/jaredlll08/ModTweaker/files/2128590/latest.log)

**Comment by jaredlll08** [comment]
update crafttweaker...

**Comment by hagar-qim** [comment]
sorry, did what you asked, removed the old jar and replaced it by a new download from Curseforge. I even took a slightly older version after that, but the result is and remains the same. Crafttweaker keeps being reported  as version 4.03, by the way

**Comment by jaredlll08** [comment]
show me the log file of the latest run.
