### ISSUE TITLE
[Help] Can't edit melting recipes of TiC

### ISSUE THREAD

**Issue by Lictor000** [jaredlll08/ModTweaker#653]
#### Issue Description:
I'm getting an error when trying to edit some melting recipes when loading minecraft. I'm trying to balance the ore output when smelting it in the smeltery, specifically I'm trying to make so the output in molten liquid of one ore to be the same of some nuggets and not some ingots (TiC config doesn't allow to ask for outputs lower than the single ingot).
I followed the crafttweaker wiki (https://crafttweaker.readthedocs.io/en/latest/#Mods/Modtweaker/TConstruct/Melting/) and I don't understand if I'm getting something wrong or maybe TiC just changed how to refer to the molten liquids.

#### What happens:
I get an error when loading minecraft about the molten liquids I'm trying to edit  ("could not resolve").

#### What you expected to happen:
To get the molten liquid outputs desired.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/jHYFu1x6

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/Sp0BSqpm

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- Crafttweaker: 4.1.9
- ModTweaker: 4.0.12
- MTLib: 3.0.5

#### Your most recent log file where the issue was present: 
https://gist.github.com/Lictor000/b60adb32c5cf792ef312e8a308e219d0

**Comment by jaredlll08** [comment]
You have the wrong liquid names. Use /ct liquids to get a list of them

**Comment by Lictor000** [comment]
Thank you. I feel so dumb now, I was just too focused on the wiki example that it didn't even occur to me to use that command.
First time using CT, sorry to waste your time and thanks again.
