### ISSUE TITLE
Thaumcraft 6 Infusion doesnt work

### ISSUE THREAD

**Issue by ghost** [jaredlll08/ModTweaker#657]
#### What happens / Issue Description::

hey :D I have a small problem and although I have recently seen that there is a small integration for thaumcraft 6. I tried a bit and found out there was something wrong. The recipe itself is displayed to me in the jei. However, nothing happens ._. . also gives me no error message

#### What you expected to happen:

It works^^

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/s3tjUCVj

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2712
- Crafttweaker: 4.1.8
- ModTweaker: 4.0.12
- MTLib: 3.0.5

**Comment by jaredlll08** [comment]
If the recipe is being picked up, then it should work, as JEI is reading from thaumcraft's registry.

Probably on thaumcrafts side

**Comment by kindlich** [comment]
Make sure that the thaumcraft research labelled "RESEARCH" exists and that you have that research unlocked when trying to do the recipe!

**Comment by ghost** [comment]
can i leave that out? or does something have to be in there? I do not think there is research on this version. had used it only once in the infinity script.

**Comment by jaredlll08** [comment]
Just put an empty string, that means it isn't tied to a research
