### ISSUE TITLE
Adding RFTools' dimensional shard ore to Botania's Orechid

### ISSUE THREAD

**Issue by bobrob2004** [jaredlll08/ModTweaker#658]
#### Issue Description:
When I try to add RFTools' dimensional shard ore to the orechid, the game crashes.  I added the line

mods.botania.Orechid.addOre("oreDimensionalShard", 50000);

I used a really high number for testing purposes.  When the orechid tries to generate the ore, that's when the game crashes.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2732
- Crafttweaker: 1.12-4.1.9
- ModTweaker: 4.0.12
- MTLib: 3.0.5

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by bobrob2004** [comment]
I found a workaround. I added a new ore dict to the dimensional shard ore and used the new ore dict and it worked without crashing.

**Comment by jaredlll08** [comment]
Logs? Scripts? Anything?
