### ISSUE TITLE
Actually Addition Crusher removeRecipe game crash

### ISSUE THREAD

**Issue by UnPure** [jaredlll08/ModTweaker#659]
#### What happens:
I'm trying to remove a recipe from the Actually Addition crusher but as soon as i start the game, its crashing. The crafttweaker log tells me "Removing 0 Crusher Recipe(s) for Unknown item" while the item is correct.

#### Script used:
https://pastebin.com/z0kJ4Xmh

#### Affected Versions:
- Minecraft: 1.12.2
- Forge: 14.23.4.2732
- Crafttweaker: 4.1.9
- ModTweaker: 4.0.12
- MTLib: 3.0.5

#### Your most recent log file where the issue was present: 
https://pastebin.com/Bk893rcq

**Comment by jaredlll08** [comment]
Fixed in dev
