### ISSUE TITLE
IllegalAccessError in compat module with Actually Additions;Confirmed by AA repository staff to be not fault of AA

### ISSUE THREAD

**Issue by AncientShotgun** [jaredlll08/ModTweaker#660]
#### Issue Description:

The crash is cause by a call to the output field in the Actually Additions Empowerer recipe handler when the Empowerer class becomes inaccessible, thus throwing an IllegalAccessError. As stated in the issue title, Actually Additions repository maintainers have confirmed it as not the fault of Actually Additions.

#### What happens:

Minecraft crashes to desktop and displays the stack trace in the console.

#### What you expected to happen:

Minecraft would run normally.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/Atn1JgaN

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/y0fz2fED
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- Crafttweaker: 1.12-4.1.9
- ModTweaker: 4.0.12
- MTLib: 3.0.5

#### Your most recent log file where the issue was present: 

https://paste.ee/p/fwJjr

**Comment by jaredlll08** [comment]
fixed in dev
