### ISSUE TITLE
Add the ability to remove all recipes

### ISSUE THREAD

**Issue by axieum** [jaredlll08/ModTweaker#661]
I'm building a modpack and wish to remove all recipes from various Thermal Expansion machines. I see that CraftTweaker itself adds a `furnace.removeAll()` function and was wondering whether you could add this to ModTweaker for use with other mods.

**Comment by jaredlll08** [comment]
Not all mods account for there being no recipes, I would rather not risk it, and not all mods support removing all the recipes
