### ISSUE TITLE
[1.12.2]Error executing

### ISSUE THREAD

**Issue by Rumaruka** [jaredlll08/ModTweaker#664]
#### What happens:

Looking in screenshot

![image](https://user-images.githubusercontent.com/8148679/42908280-f14f97ae-8af9-11e8-962f-cf2f1ab40c85.png)

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/2bRDESZv

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
I found error - 
java.lang.NoSuchMethodError: de.ellpeck.actuallyadditions.api.recipe.LensConversionRecipe.<init>(Lnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;ILde/ellpeck/actuallyadditions/api/lens/LensConversion;)V
	at com.blamejared.compat.actuallyaddition.AtomicReconstructor.addRecipe(AtomicReconstructor.java:26)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2738
- Crafttweaker: 8.1.9
- ModTweaker: 4.0.12
- MTLib: 3.0.5

**Comment by jaredlll08** [comment]
I will not look in screenshot.
