### ISSUE TITLE
Unable to remove blood magic alchemy array (Binding) recipes

### ISSUE THREAD

**Issue by Thedrummonger** [jaredlll08/ModTweaker#665]
#### Issue Description:
I have attempted to remove the recipe for living armor in 1.12.2, however the recipe still exists after loading the game. I suspect this is because alchemy array recipes are different from alchemy array (Binding) recipes (They have different jei tabs). You will also notice in the script I tried the script two ways, Input then catalyst and catalyst then input. The reason for this is in the example for alchemy array scripts on the crafttweaker website the recipe creation is listed as IItemStack input, IItemStack catalyst, IItemStack output, I have found however that it actually goes IItemStack output, IItemStack input, IItemStack catalyst. Since that is out of order I thought the recipe removal example might be as well.

#### What happens:
I add a script to remove and alchemy array (Binding) recipe.

#### What you expected to happen:
The recipe is not removed.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
See Line 193
https://pastebin.com/QRnnkNu2

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/Ufjtju79

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2739
- Crafttweaker: 1.12.2-4.1.9
- ModTweaker: 4.0.13
- MTLib: 3.0.5

#### Your most recent log file where the issue was present: 

https://gist.github.com/Thedrummonger/6e0c11daa04ed5eeb52e8c57c3fdd4e8

**Comment by jaredlll08** [comment]
Bindings cannot be removed at all. Sorry.
