### ISSUE TITLE
Turntable recipes issue (remastered)

### ISSUE THREAD

**Issue by Davoleo** [jaredlll08/ModTweaker#668]
#### Issue Description:
Turntable custom recipe not working

#### What happens:
After putting the block that has the custom recipe written in scripts on the turntable it starts shooting particles just like if the recipe was working, however the item isn't going to be made it continues to shoot particles forever without executing the recipe.

#### What you expected to happen:
I expected to get the item and the byproduct

#### Script used:
https://pastebin.com/WCK83ZZm
it's a big file, the turntable recipes are under the Better with mods section 

#### Minetweaker.log file:
https://pastebin.com/TFNNaKdd

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2745
- Crafttweaker: 4.1.9
- ModTweaker: 4.0.13
- MTLib: 3.0.5
- Better With Mods: 2.3.4

#### Your most recent log file where the issue was present: 
https://pastebin.com/xh3J2i8E

**Comment by jaredlll08** [comment]
Spoke to BWM devs, this is an issue on their side.
