### ISSUE TITLE
Modtweaker Wiki lists wrong formula for TicMat

### ISSUE THREAD

**Issue by Peach774** [jaredlll08/ModTweaker#673]
on this page: https://crafttweaker.readthedocs.io/en/latest/#Mods/Modtweaker/TConstruct/Materials/ITICMaterial/
the old reference model for tinkers construct materials is still used. This can cause people to enter the wrong thing.
val stone = <material:stone>;
should be
val stone = <ticmat:stone>;

**Comment by kindlich** [comment]
Should be fixed.

**Comment by Peach774** [comment]
Yep, all better. Thanks!
