### ISSUE TITLE
[Suggeestion/Request] Thaumcraft Golem Scanning

### ISSUE THREAD

**Issue by drakray** [jaredlll08/ModTweaker#674]
As seen in https://github.com/Azanor/thaumcraft-beta/issues/1356

Could you please add a function to add Entities as Automaton Scannable?
Something like `mods.thaumcraft.Golem.add(<entity:mod:entity>);`, with NBT if possible for <entity>

**Comment by drakray** [comment]
Or just `mods.thaumcraft.Scannable.registerScan("researchName", <entity>, bool);`, for maximum possibility

**Comment by jaredlll08** [comment]
You can only add scanning things (according to the TC api) and I don't like adding features that only allow additions, it just seems half assed and leads to people asking me to add a remove feature, which I can't.

**Comment by drakray** [comment]
Oh I understand, that's sad, as TC only allow for Vanilla's Iron Golem to be used, and Extra Golem add SOOO much more.
I'll pass that to them directly then, thanks :)
