### ISSUE TITLE
[Suggestion] Support for Thaumcraft Tabs and Research?

### ISSUE THREAD

**Issue by ofseaandstars** [jaredlll08/ModTweaker#675]
#### Description:

It would be nice to have support for the Thaumcraft 6 Book to add new tabs and research. I know this was a thing for previous Thaumcraft versions, but I couldn't seem to get it to work for Thaumcraft 6 (also I checked the crafttweaker wiki and no reference to it).

I realise that TC6 is still in beta, and so it might not be possible, but it would be really great to have. If it's already implemented and I've just not seen it, I apologise.

I did try to use the old methods, but they don't seem to work.
(Eg. `import mods.thaumcraft.Research` and `mods.thaumcraft.Research.addTab("DEMENTIA", "thaumcraft", "textures/items/brain.png");` etc)

If this has already been suggested before, I apologise, I couldn't find a reference to it in the closed issues.

**Comment by kindlich** [comment]
https://github.com/jaredlll08/ModTweaker/issues/628#issuecomment-386822156

**Comment by ofseaandstars** [comment]
Ah I see. Oh well :)
