### ISSUE TITLE
[Bug] Thaumcraft's addSmeltingBonus does not seem to work properly

### ISSUE THREAD

**Issue by Mike-U5** [jaredlll08/ModTweaker#676]
#### Issue Description:
mods.thaumcraft.SmeltingBonus.addSmeltingBonus always gives the bonus item for every smelting action regardless of itemstack weight.

#### What happens:
Every Iron Ore smelted gives a Ghast Tears.
With all four arcane bellows attached, it'll always give 5 Ghast Tears.

#### What you expected to happen:
Every Iron Ore smelted in the infernal furnace has a 5% change to give a Ghast Tear as bonus.
(Or ~25% with all four bellows attached)

#### Script used
https://pastebin.com/NutTqVYQ

#### Minetweaker.log file
Just says
_Adding <minecraft:ghast_tear> as a possible smelting bonus for: oreTin_
And nothing else relevant.

#### Affected Version

- Minecraft: 1.12.2
- Forge: 14.23.4.2750
- Crafttweaker: 4.1.8
- ModTweaker: 4.0.13
- MTLib: 3.0.5

Extra note: It seems like the Thaumcraft API for addSmeltingBonus wants a float as third argument, but the Modtweaker handler provides an Int.

**Comment by jaredlll08** [comment]
I need that log,

What happens when you do 

`<minecraft:ghast_tear> % 100`?

**Comment by Mike-U5** [comment]
Sorry, I forgot to mention that this is with 4 Arcane Bellows attached. Those boost nugget output by 400% so that's why there's 5.

Doing what you suggested still gives 1 ghast tear every time without bellows and 5 ghast tears with all bellows.
So the issue is that players have 100% change to get the smelting bonus.

And here is the full log: https://pastebin.com/JTS2uakE
I used only the minimum required mods and a single line of script.
