### ISSUE TITLE
[1.12.2] Chisel group don't work with IChisel

### ISSUE THREAD

**Issue by TheSnowyChickens** [jaredlll08/ModTweaker#680]
#### Issue Description:
This:
"
mods.chisel.Carving.addVariation("blockFuelCoke", <chisel:block_coal_coke:0>);
"
don't work with the IChisel. (in a diamond and iron it works)
If I click on "chisel", nothing happend, no change of the block, but ONLY in the IChisel and ONLY this 1 kind of coal coke block. 
The other 2 (immersive and Thermal) work without any problems.

#### What happens:
IChisel don't change the block with the script.

#### What you expected to happen:
A block change.

#### Script used:
https://paste.dimdev.org/begevemire.cpp

#### Minetweaker.log file:
I can add it, but where can I find it? :D 

#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 2759
- Crafttweaker: 4.1.9 
- ModTweaker: 4.0.13
- MTLib: 3.0.5
- Chisel: 0.2.1.34

**Comment by jaredlll08** [comment]
If it works in any chisel, but not a single other chisel, then it is a chisel issue, report to them.

**Comment by TheSnowyChickens** [comment]
Okay
