### ISSUE TITLE
Alloy removal not working - TCon Support

### ISSUE THREAD

**Issue by Peach774** [jaredlll08/ModTweaker#681]
#### Issue Description:
Occuring in my own personal pack. Trying to remove Mirion Alloy from PlusTiC, script says it should work but it doesnt and the alloy can still be crafted.

#### What happens:
Mirion alloy removal script throws no error, doesnt work

#### What you expected to happen:
Mirion alloy is removed from smeltery

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/62Z76a0L

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/rP5pyJf1

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: .2760
- Crafttweaker: 4.1.9
- ModTweaker: 4.0.13
- MTLib: 3.0.5

#### Your most recent log file where the issue was present: 
https://gist.github.com/Peach774/2cf501b85185787bfebc791ac9a0367d

**Comment by kindlich** [comment]
You might need to multiply by the actual liquid values (You don't get 1mb mirion from cobalt, elementium, terrasteel, manasteel and glass, 1mb each (I suppose, no clue though)).

Also, did you try to use the other methods that only takes the output fluid?

**Comment by Peach774** [comment]
yes, same result

**Comment by jaredlll08** [comment]
TiC doesn't allow us to remove a recipe, it allows us to cancle an event though, so that is what we do, so what is most likely happening is that PlusTic is registering their stuff before we get told to cancle the event
