### ISSUE TITLE
1.10.2 railcraft support

### ISSUE THREAD

**Issue by Shovinus** [jaredlll08/ModTweaker#684]
Are you not supporting until railcraft gets put to 1.12?

**Comment by jaredlll08** [comment]
only 1.12.2 is supported.

**Comment by Shovinus** [comment]
Jesus you are fast, that means you are not back porting I take it.

**Comment by Shovinus** [comment]
Do I have to fork mod tweaker then to add it in? I have been making a pack for a week, I don't want it to fail over something so simple, please provide any information you can.

**Comment by jaredlll08** [comment]
Update to 1.12. I'm done with 1.10.2, and so is the community.

A fork most likely won't be accepted onto curseforge. 

If you really really really want support, the only thing I can recommend is making your own addon mod for it.

**Comment by Shovinus** [comment]
I would but railcraft isn't on 1.12 yet
