### ISSUE TITLE
Unable to remove Carpenter recipe

### ISSUE THREAD

**Issue by Palimon** [jaredlll08/ModTweaker#687]
#### Issue Description:
I'm unable to remove a Carpenter recipe for torch.

#### What happens:
There is a carpenter recipe for one stick and one wool plus creosote oil = 1 torch.  I'm trying to remove this recipe and replace with a more complex recipe.  I do add the new recipe, but the old recipe is still there.

which according to documentation is exactly how I should remove the recipe: http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Forestry_Support_1.10.2

#### What you expected to happen:
I expect the recipe to be removed from the carpenter.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/hQ1Hf4aM

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/PJ8FMS0h

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2511
- Crafttweaker: 1.10.2-3.0.26
- ModTweaker: 2-2.0.13
- MTLib: 1.0.3

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
Can't post the entire log, so here's the relevant part: https://pastebin.com/Rbkn31hc

**Comment by jaredlll08** [comment]
1.10 isn't supported anymore.
