### ISSUE TITLE
ModTweaker wiki page doesn't contain a list of mods currently supported, those planned, or those that won't be added.

### ISSUE THREAD

**Issue by OrphanedPixel** [jaredlll08/ModTweaker#688]
#### Issue Description: I needed to check the [ModTweaker wiki page](http://crafttweaker.readthedocs.io/en/latest/Mods/Modtweaker/Modtweaker/) to see which mods were supported, but there was nothing on the page beyond "Modtweaker is an addon for Crafttweaker that adds support for many mods!".

**Comment by kindlich** [comment]
![screenshot](https://user-images.githubusercontent.com/10351787/45966832-8ce96480-c02c-11e8-9ff2-165f613161c0.PNG)

Let me break your issue down into 3 parts:
- "ModTweaker wiki page doesn't contain a list of mods currently supported" Wrong, check the screenshot
- "ModTweaker wiki page doesn't contain a list of mods planned to be supported" Correct, but you can check the GH issue tracker for those that have been requested.
- "ModTweaker wiki page doesn't contain a list of mods that won't be added" Correct, but there are few mods that definitely won't be added and the reasons for those is mainly that they add support by themselves or other mods already provide the functionality. Again, you can check the issue tracker for closed mod requests.

**Comment by jaredlll08** [comment]
As kindlich said, we don't know what mods we plan on supporting, and the list of what is currently supported is on the wiki.
