### ISSUE TITLE
[1.12.2] [Request] Add Support for Thermal Expansion's Igneous Extruder

### ISSUE THREAD

**Issue by Draskh** [jaredlll08/ModTweaker#690]
Modtweaker has already added support for many machines, but not for the Igneous Extruder.
It aim to be able to add recipes for Underground Biomes or Chisel or stones from other mods. https://teamcofh.com/docs/thermal-expansion/igneous-extruder/

**Comment by jaredlll08** [comment]
There is no way to remove an extruder recipe, I either provide full support or no support, sorry.
