### ISSUE TITLE
[Request] Thaumcraft 6 research check

### ISSUE THREAD

**Issue by MightyBidoof** [jaredlll08/ModTweaker#691]
Apologies in advance if this is the wrong place to make a request.

This is a minor request, but add a research check for custom Thaumcraft recipes, and if the research doesn't exist/isn't registered, print an error in chat.

mainly making this request since I was dumb and got the research string and recipe name string mixed up, but it could help with catching miswritten research or research that's case sensitive (e.g. the "discover x aspect" requirements) that you've messed up the case of.

**Comment by jaredlll08** [comment]
I can't seem to find a way to see if a research is registered or not, sorry.
