### ISSUE TITLE
[Suggestion] mtgui command working like ctgui for crafttweaker

### ISSUE THREAD

**Issue by darthvader45** [jaredlll08/ModTweaker#696]
I noticed there's a crafttweaker command that allows for recipe editing via GUI instead of having to mess with files manually.  I'd love for that kind of functionality to be added to modtweaker.  The command would be /mtgui, to be similar yet different.  What do you think?

**Comment by jaredlll08** [comment]
No. Learn the language, there are way to many machines for this to be feasible and honestly just promotes laziness.

**Comment by darthvader45** [comment]
Alrighty then.
