### ISSUE TITLE
Crash when adding a recipe for Actually Additions Empowerer

### ISSUE THREAD

**Issue by Rundas01** [jaredlll08/ModTweaker#697]
[latest.log](https://github.com/jaredlll08/ModTweaker/files/2559058/latest.log)
When adding a recipe for the Empowerer the game crashes. I looked here how to add them: 

https://crafttweaker.readthedocs.io/en/latest/#Mods/Modtweaker/ActuallyAdditions/Empowerer/

It works when leaving the "ParticleColourArray" parameter out, but with one the game crashes.
To reproduce the crash you just need to add a "ParticleColourArray" parameter in the the edited recipe.

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2745
- Crafttweaker: 1.12-4.1.11
- ModTweaker: 4.0.15
- MTLib: 3.0.5

https://pastebin.com/KfzkYzXF (Zen-Script)
https://pastebin.com/70EpKGe0 (Minetweaker-Log)

The log-file is too large for the free version of pastebin to process. And I believe that posting it raw is better than not posting it or posting it in parts.

**Comment by jaredlll08** [comment]
Upload it to gist.

**Comment by jaredlll08** [comment]
Actually don't bother. The colour array is for RGB, you need 3 values as shown in the wiki example.

**Comment by Rundas01** [comment]
Thank you for your quick response.
The funny thing is, that I originally tried it with 3 values and it crashed.
It seems that the values cannot be separated like this [0.5, 0.3, 0.2] but rather be close together like this.
[0.5,0.3,0.2].
