### ISSUE TITLE
Add regular crafting recipes that can only be crafted by specific blocks

### ISSUE THREAD

**Issue by 016Nojr** [jaredlll08/ModTweaker#699]
Is it possible to add an option to specify what blocks can craft a new crafting recipe, for example when adding a crafting recipe, specify it can only be crafted with a machine that can autocraft recipes (for example the "Crafter" from EnderIO), removing the option to use a normal crafting table.

If it's possible, can you add it?

**Comment by jaredlll08** [comment]
No, most mods pull from the recipe registry and don't have their own.
