### ISSUE TITLE
[Feature Request] Thaumcraft Add Salis Mundus Recipes

### ISSUE THREAD

**Issue by Dragnier** [jaredlll08/ModTweaker#700]
I would love to see the ability to add recipes to the new Salis Mundus mechanic. For example, right clicking Smooth Stone in the world with Salis Mundus to turn it into something else. I do not know how this is originally coded, so I have no idea how possible it might be, but I thought I could at least ask.

**Comment by jaredlll08** [comment]
Just looked at the code for this, unfortunately it isn't possible. Sorry.

**Comment by Dragnier** [comment]
Thanks for looking at least. Was worth a shot!
