### ISSUE TITLE
Issue with modtweaker crashing ActuallyAdditions and ActuallyBaubles

### ISSUE THREAD

**Issue by eonrickity** [jaredlll08/ModTweaker#701]
this keeps happening when i open up minecraft.
https://i.imgur.com/4esxziJ.png

let me get the crash log.
here you go.
https://paste.dimdev.org/safasavuke.mccrash
help pleaz idk what to do.

**Comment by jaredlll08** [comment]
Use the issue template is what you do.

Also update Modtweaker.
