### ISSUE TITLE
JEI integration about BWM Kiln structure block

### ISSUE THREAD

**Issue by Snownee** [jaredlll08/ModTweaker#703]
#### Issue Description:

I am not sure if I am supposed to report here. 

Addtional structure blocks not showing in JEI's catalyst list. I am pretty sure these blocks can form multi-block from my debug screen (it turns to be `betterwithmods:kiln`), but JEI only shows the default brick block.

![image](https://user-images.githubusercontent.com/16059084/50493770-91be1a00-0a5a-11e9-86d8-d5f3bc50c1cd.png)

#### Script used

```
import mods.betterwithmods.Kiln;

Kiln.registerBlock(<minecraft:stone>);
```

____
#### Affected Versions

- Minecraft: 1.12.2
- Forge: 2796
- Crafttweaker: 4.1.13
- ModTweaker: 4.0.15
- MTLib: 3.0.5

**Comment by jaredlll08** [comment]
If it works, but doesn't show the recipe in Jei, it's an issue with BWM.
