### ISSUE TITLE
[Suggestion] Railcraft support

### ISSUE THREAD

**Issue by Skillotic0703** [jaredlll08/ModTweaker#704]
Now that Railcraft is on 1.12 maybe it would be possible to get support for it please? (Rolling Machine + Crusher)

**Comment by TheDeviantCrafter** [comment]
According to the [old wiki](http://minetweaker3.powerofbytes.com/wiki/ModTweaker), Railcraft was supported in 1.7.10. The Railcraft team has also apparently delegated this to ModTweaker in [this issue](https://github.com/Railcraft/Railcraft/issues/1193).

**Comment by Draskh** [comment]
Be aware of https://github.com/Railcraft/Railcraft/issues/1610. Until not all recipes are moved to init this could be a thing.

**Comment by jaredlll08** [comment]
Railcraft is very much still in beta, and as that issue said I can't actually do anything with their recipes right now.

If Railcraft gets a proper release, please feel free to create a new issue for this.
