### ISSUE TITLE
[Bug or not Implemented] Thaumcraft 6 Recipes wont show up in Thaumonomicon

### ISSUE THREAD

**Issue by Mr3DAlien** [jaredlll08/ModTweaker#706]
#### Issue Description:
So i want to change the Recipe for the Infsuion Matrix in Thaumcraft 6, and it also works, the only Problem is, that it will only show up in Thaumic Jei, but it wont show up in the Thaumonomicon. I also changed the Recipe for the Thaumometer, and this one does show up in the Thaumonomicon.

So this is how I changed the Recipes:

## Thaumometer
mods.thaumcraft.ArcaneWorkbench.removeRecipe(<thaumcraft:thaumometer>);
mods.thaumcraft.ArcaneWorkbench.registerShapedRecipe("thaumometer", "FIRSTSTEPS", 20, [<aspect:aer>, <aspect:ignis>, <aspect:terra>, <aspect:ordo>, <aspect:perditio>, <aspect:aqua>], <thaumcraft:thaumometer>, [[null, <minecraft:gold_ingot>, null], [<minecraft:gold_ingot>, <botania:managlass>, <minecraft:gold_ingot>], [null, <minecraft:gold_ingot>, null]]);

## Infusion Matrix
mods.thaumcraft.ArcaneWorkbench.removeRecipe(<thaumcraft:infusion_matrix>);
mods.thaumcraft.ArcaneWorkbench.registerShapedRecipe("infusion_matrix_crafting", "INFUSION", 150, [<aspect:aer>, <aspect:ignis>, <aspect:terra>, <aspect:ordo>, <aspect:perditio>, <aspect:aqua>], <thaumcraft:infusion_matrix>, [[<thaumcraft:stone_arcane_brick>, <bloodmagic:slate:1>, <thaumcraft:stone_arcane_brick>], [<botania:manaresource:7>, <ore:nitor>, <botania:manaresource:7>], [<thaumcraft:stone_arcane_brick>, <bloodmagic:slate:1>, <thaumcraft:stone_arcane_brick>]]);

____

#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 
- Crafttweaker: 4.1.13
- ModTweaker: 4.0.15
- MTLib: 3.0.5

**Comment by jaredlll08** [comment]
You must be doing something wrong, if it worked for one thing, but not the other, it most likely means that your recipe name is wrong.

**Comment by Mr3DAlien** [comment]
But how do I find out what the recipe name is, I can change the Recipes and I can craft them, but the recipes won't show up in the Thaumonomicon Tab... Only the Thaumometer Recipe does show up. If you have the Technic Launcher you can install TheZeroProject 4 and look for yourself :/

**Comment by MuffinPrison** [comment]
Hi, have you tried to change the craft of items from taumcraft in the vanilla workbench? not arcane workbench. i try change wood table recipe but my recipe wont show up in thaumonomicon. Have you encountered such a problem? did you find a solution?
can there be special commands? maybe
 (mods.thaumcraft.Workbench.removeRecipe(<thaumcraft:table_wood>);
mods.thaumcraft.Workbench.registerShapedRecipe("tablewood", "THEORYRESEARCH", 0, [], <thaumcraft:table_wood>, [[null, null, null], [<thaumcraft:slab_greatwood>, <thaumcraft:slab_greatwood>, <thaumcraft:slab_greatwood>], [<thaumcraft:plank_greatwood>, null, <thaumcraft:plank_greatwood>]]);) 
?

recipes.removeShaped(<thaumcraft:table_wood>);
recipes.addShaped("tablewood", <thaumcraft:table_wood>, [[<thaumcraft:slab_greatwood>, <thaumcraft:slab_greatwood>, <thaumcraft:slab_greatwood>], [<thaumcraft:plank_greatwood>, null, <thaumcraft:plank_greatwood>], [null, null, null]]);
