### ISSUE TITLE
[1.12.2] BWM Adding heating source error

### ISSUE THREAD

**Issue by serialtasted** [jaredlll08/ModTweaker#708]
#### Issue Description:
Adding BWM heat source  throws error and stops script from loading.

#### What happens:
https://pastebin.com/gaKG06PF

#### What you expected to happen:
New heat source should be added.

#### Script used:
https://pastebin.com/cYHX8Vkk

#### Minetweaker.log file:
https://pastebin.com/wJRywK4i

____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.5.2808
- Crafttweaker: 4.1.14
- ModTweaker: 4.0.16
- MTLib: 3.0.5
- BWM: 2.3.20-1027

#### Your most recent log file where the issue was present: 
[latest.log](https://github.com/jaredlll08/ModTweaker/files/2823082/latest.log)

**Comment by kindlich** [comment]
I do not know why that does not show in your log but `<minecraft:lava>` should not say it cannot parse that item.

Try to use `<blockstate:minecraft:lava>` instead.

**Comment by serialtasted** [comment]
Does nothing unfortunately. For a moment the flame icon inside the ui lits up but as soon as you close an reopen the ui the flame just gets to its grey state.

**Comment by Mr-Tinkerman** [comment]
Try using `<liquid:lava>`

I haven't tested it but I think I read something about this on the minetweaker wiki. IDK

**Comment by serialtasted** [comment]
No, liquids are not an valid method. I've tried that already. Should have mentioned up there

**Comment by jaredlll08** [comment]
Apparently BWM doesn't accept liquids at all for the heat registry.
