### ISSUE TITLE
Particle errors

### ISSUE THREAD

**Issue by Shibva** [jaredlll08/ModTweaker#710]
#### Issue Description:
Particle are not working correctly

#### What happens:
when the particle generator is used along with the particles that come from the shockwave and the draconic energy storage they apear to be ether grey or missing

ex; Set particle generator to emit Red 255 particles
particles generated are grey

#### What you expected to happen:
For the correct colors to be produced and for the apropate colors to appear from the pylons pulling and emiting Rf into the energy core

#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: lattest *for me* (14.23.5.2807
- Crafttweaker: 1.12-4.1.13
- ModTweaker: not Present
- MTLib: not Present

#### Your most recent log file where the issue was present: 

https://gist.githubusercontent.com/SteamDoge9000/6ecffbf05c8d4cd06c4721e82833f6d6/raw/76368db1c93996cd23e0c555759b08224cbc08a3/Gaamelog
  (this is the full file due to tucking)

**Comment by jaredlll08** [comment]
I don't see how this is my issue. Report to whatever move adds the particle generator

**Comment by Shibva** [comment]
your mod adds the particle generator
your custom particle effects

https://ftbwiki.org/Particle_Generator_(Draconic_Evolution)

**Comment by Shibva** [comment]
oh
im on the wrong github
this link was suppose to be for draconic evolution

Srry
