### ISSUE TITLE
Tinker's Melting: No such member

### ISSUE THREAD

**Issue by GalacticSilver** [jaredlll08/ModTweaker#712]
#### Issue Description:
I am trying to create a modpack, and I am trying to add a recipe for the tc smeltery to melt 1 redstone dust into 1000mb of destabilized redstone.

#### What happens:
I get the error:
No such member: Smeltery

#### What you expected to happen:
A melting recipe for redstone dust into destabilized redstone in the smeltery.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/ZuDtuHsW

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/2ciAj21z

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2815
- Crafttweaker: 1.12-4.1.14 (4.1.14)
- ModTweaker: 4.0.16 (4.0.16)
- MTLib: 3.0.5 (3.0.5)

#### Your most recent log file where the issue was present: 
[crafttweaker.log](https://github.com/jaredlll08/ModTweaker/files/2911778/crafttweaker.log)

[pastebin/gist/etc link here]

**Comment by kindlich** [comment]
Use `.Melting` instead of `.Smeltery`

**Comment by GalacticSilver** [comment]
Now I get the error:
ERROR: thermalrecipes.zs:13 > No such static member in mods.tconstruct.Melting: addMelting

**Comment by jaredlll08** [comment]
Please read the wiki.
https://docs.blamejared.com/en/#Mods/Modtweaker/TConstruct/Melting/
