### ISSUE TITLE
Melting.removeRecipe cannot be used to remove recipes that use the ore dictionary.

### ISSUE THREAD

**Issue by ErzengelLichtes** [jaredlll08/ModTweaker#713]
#### Issue Description:
The Tinker's Construct Melting.removeRecipe sets the "input" as an IItemStack rather than an IIngredient that's used by Melting.addRecipe, preventing the removal of recipes that use Ore Dictionaries. For example, <ore:sand> is used to make glass, so you cannot remove the recipe.

#### What happens:
You get an error when you try to use an ore dictionary.

#### What you expected to happen:
The recipe to create the liquid from the ore dictionary item will be correctly removed.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/qtcwqqJV

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/BHGhmSDY

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2808
- Crafttweaker: 4.1.15
- ModTweaker: 4.0.16
- MTLib: 3.0.6

#### Your most recent log file where the issue was present: [pastebin/gist/etc link here]
https://pastebin.com/rwjvW1Xt

**Comment by jaredlll08** [comment]
There is no way to remove by OreDict, since TIC asks for a list of ItemStacks, but they have checks for oredict, aslong as the item is in an oredict, it should work, if it doesn't, report to TIC.
