### ISSUE TITLE
Thaumcraft Vis Crystals are somewhat buggy

### ISSUE THREAD

**Issue by Rundas01** [jaredlll08/ModTweaker#714]
Hello,
my goal is making the seeds from mystical agriculture craftable using the altars from astral sorcery. Also, different vis crystals are necessary to complete the craft. The problem is, that even tough I specified the vis crystal in  the corresponding .zs file (ignis for coal seeds for example), every sort of crystal is allowed in the recipe. Look near the bottom of the zen-script to find the ones I'm referring to.

- Minecraft: 1.12.2
- Forge: 14.23.5.2796
- Crafttweaker: 1.12-4.1.11
- ModTweaker: 4.0.15
- MTLib: 3.0.5
-Thaumcraft: 1.12.2-6.1 beta 26
-Astral Sorcery: 1.12.2-1.10.11

zen script: https://pastebin.com/7cMuizES 
latest log: https://pastebin.com/95idiBp3
crafttweaker log: https://pastebin.com/j5p4kAmy

Thanks in advance,
Blackluigi

**Comment by kindlich** [comment]
First, Try `.onlyWithTag` as well as `.withTag`
Second, since AstralSorcery adds the CrT suport on their own, this issue is in the wrong place.

**Comment by Rundas01** [comment]
I also posted this issue there.
.onlyWithTag made it worse, since .withTag showed the correct recipe in JEI and .onlyWithTag showed the blank vis crystal (the %'s one).
So that's not the answer. 
I'll wait for a response from the team from Astral.
But thanks anyway.
