### ISSUE TITLE
i'm trying to add a recipe but i suck

### ISSUE THREAD

**Issue by Bjark7834** [jaredlll08/ModTweaker#715]
#### Issue Description:
i'm trying to add a recipe for dawnstone and i don't know what i am doing wrong

it says it can't run the script

mods.tconstruct.Casting.addTableRecipe(<embers:ingot_dawnstone>, <liquid:dawnstone.molten> * 144, null, false, 20);

[crafttweaker.log](https://github.com/jaredlll08/ModTweaker/files/2963324/crafttweaker.log)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:
- Forge:
- Crafttweaker: 
- ModTweaker:
- MTLib:

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
Use the template. I'm not download log files, and your script is messed because you didn't read the template.
