### ISSUE TITLE
Factorizer [Thermal Expansion] is not recognized

### ISSUE THREAD

**Issue by Freebi85** [jaredlll08/ModTweaker#716]
#### Issue Description:

The Factorizer [Thermal Expansion] is not recognized. Or i do somthing wrong?
I'm sorry, I've been husked and pressed too fast^^

import mods.thermalexpansion.Factorizer
mods.thermalexpansion.Factorizer.addRecipeCombine(<minecraft:dye:4> * 9, <minecraft:lapis_block>);
mods.thermalexpansion.Factorizer.addRecipeSplit(<minecraft:lapis_block>, <minecraft:dye:4> * 9);

It says no such member: Factorizer
Other Thermal scripts works fine so far.

Minecraft 1.12.2
Forge .2821
Modtweaker: 4.0.16

**Comment by jaredlll08** [comment]
No info doesn't help.

**Comment by Freebi85** [comment]
I'm sorry I accidentally hit the button while I was writing. I didn't know you were so fast^^

**Comment by Freebi85** [comment]
Do you want me to open a new issue with more information or how should I proceed now? 
I just want to help you keep the great mod bug-free. Sorry if the mistake is on my site.

**Comment by jaredlll08** [comment]
We don't have support for the Thermal Factorizer, didn't even know it was a machine.

If it is a machine, please make a new feature request for it.

**Comment by Freebi85** [comment]
Alright thank you. Then you should delete this informations from the webside.

https://crafttweaker.readthedocs.io/en/latest/#Mods/Modtweaker/ThermalExpansion/Factorizer/

**Comment by jaredlll08** [comment]
OH! I see the issue, so the docs are a bit more upto date compared to the mod, there is a PR that adds the factorizer, but I need to actually release it, the next modtweaker version will support it
