### ISSUE TITLE
Dynamo Additions (Compression)

### ISSUE THREAD

**Issue by Fortist** [jaredlll08/ModTweaker#717]
For some reason, when adding a fuel to the compression dynamo, nothing happens.
The log says "Altering CompressionDynamo Recipe(s) for <liquid:biofuel>"
While in game it isnt added to JEI for reference or is it allowed to be bucketed/piped in
Plus all the Dynamo documentation is literally copy pasted for all of them changing only the machine/call, so Im unsure if thats all that needs to be added to the recipe line.

I started with just this line
`CompressionDynamo.addFuel(<liquid:biofuel>, 160);`
(Imported the mod.thermal~etc)
and then tried this line
`mods.thermalexpansion.CompressionDynamo.addFuel(<liquid:biofuel>, 160);`
and neither seem to work.

Though, I just realized I didnt Import ILiquidStacks, so ill test that a bit later to see if that changes anything.

**Comment by jaredlll08** [comment]
We simply pass the info to Thermal, if you are not getting errors in any of the logs (which you didn't give us) then there is nothing wrong on our side, and you need to report to thermal.

**Comment by Fortist** [comment]
There is no error in the log, but okay I guess it's on thermal's side.

**Comment by Fortist** [comment]
Heres the Big Dick log that you wanted
https://pastebin.com/g7Ms1iJf
