### ISSUE TITLE
[request] tcomplement steelworks mixing

### ISSUE THREAD

**Issue by Yoghurt4C** [jaredlll08/ModTweaker#718]
https://github.com/KnightMiner/TinkersComplement/blob/master/src/main/java/knightminer/tcomplement/library/steelworks/IMixRecipe.java

**Comment by Riernar** [comment]
Hi @Yoghurt4C @jaredlll08,

I started working on adding tinker's complement's high oven compatibility in a [fork](https://github.com/Riernar/ModTweaker). I tried keeping the same implementation style as other tcomplement's support code (if anything doesn't suit your taste @jaredlll08 , let me now and I'll change it)

I have yet to figure out how to remove default fuel/heat recipes/mix recipes - it seems the function I use to cancel the register event is never fired. Mix recipes do not seems to work yet, either.
I'll wait until everything is working to submit a pull request.

**Comment by jaredlll08** [comment]
I believe this has been implemented in a PR.
