### ISSUE TITLE
[Request] Custom blocks as TC6 Infusion Stabilizers

### ISSUE THREAD

**Issue by reuy** [jaredlll08/ModTweaker#722]
During the use of TC6's Infusion Altar, certain blocks can be placed around, like Tallow Candles or mob heads to reduce the instability and deter unwanted consequences. I request a way to set what blocks can serve this purpose.

Primarily, I want to add Botania's Mana Pylons to the stabilizer, as those things are surprisingly useless for how cool they look.

**Comment by DoomRater** [comment]
Botania's Mana Pylons are already stabilizers as noted in the Thaumcraft Integration page in the Lexica. "...and any variety of Pylons."

**Comment by kindlich** [comment]
There is no way for us to directly add Infusion stabilizers.
Infusion stabilizers need to implement a ThaumCraft interface, which is something we cannot do for another class.
