### ISSUE TITLE
problem with adding fuel to TE compression dynamo

### ISSUE THREAD

**Issue by ToserBan** [jaredlll08/ModTweaker#724]
#### Issue Description:
I tried to add new fuels to thermal expansion compression dynamo, but failed. 
I wanted to add extra planets liquid methane and liquid hydrogen from galacticraft and mekanism
as valid fuel types, i also tried other fluids, but none of them worked.

#### What happens:
Added the code to the tweaks.zs file, started minecraft, no error message. Tried to fill the compression dynamo with liquid hydrogen from mekanism and from galacticraft and with liquid methane from extra planets, but the dynamo didnt accepted those liquids.

#### What you expected to happen:
That the compression dynamo accept the new liquids as valids fuel.

#### Script used 
mods.thermalexpansion.CompressionDynamo.addFuel(<liquid:hydrogen>, 500);
mods.thermalexpansion.CompressionDynamo.addFuel(<liquid:methane_fluid>, 200);

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/ToserBan/51dc2a99acfd99def3707c79536ed2d2

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.12.2
- Forge: 14.23.5.2824
- Crafttweaker: CraftTweaker2-1.12-4.1.16.jar
- ModTweaker: modtweaker-4.0.17.jar
- MTLib: MTLib-3.0.6.jar

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by GreatestFool** [comment]
I’m pretty sure you just forgot the **<>** around your fluids. They should look like this:
`mods.thermalexpansion.CompressionDynamo.addFuel(<liquid:hydrogen>, 500);
mods.thermalexpansion.CompressionDynamo.addFuel(<liquid:methane_fluid>, 200);`

If it still doesn’t work. Did you remember to import the compression dynamo?

**Comment by kindlich** [comment]
Check that the liquids are in fact the liquids you added.
You can use `/ct liquids` to get a list of them all.

Also, I am not sure if the compactor has JEI support for its fuels but if it has, check if the fuels are listed there.

**Comment by jaredlll08** [comment]
If the log doesn't have an error, it means thermal is getting the data correctly and handling it there, there isn't anymore that I can do.

**Comment by ToserBan** [comment]
I used the right code with the brackets <>, github deleted them however.
mods.thermalexpansion.CompressionDynamo.addFuel(<liquid:hydrogen>, 500); mods.thermalexpansion.CompressionDynamo.addFuel(<liquid:methane_fluid>, 200);
and tried with and without 
import mods.thermalexpansion.CompressionDynamo;
at the beginning of the script. Also, i used the /ct liquids command to doublecheck if they are valid fluids. They are, but the compression dynamo does not accept a bucket with these liquids and hydrogen and methane_fluid are not listed in the recipe list. The world starts without any error message.
