### ISSUE TITLE
[Request] Add quantity value to Tinkers' Construct entity melting recipes

### ISSUE THREAD

**Issue by TheDeviantCrafter** [jaredlll08/ModTweaker#725]
#### Issue Description:

ModTweaker adds CraftTweaker support for Tinkers' Construct. One of these recipes allows you to customize entity melting recipes.

In my testing, this only creates a single milibucket of liquid for each damage tick dealt. I'd like to be able to change the quantity of liquid created per damage tick.

This is my example script:

```
// Melt cows in a smeltery to get milk
mods.tconstruct.Melting.addEntityMelting(<entity:minecraft:cow>, <liquid:milk>);
```

A cow only created 5mb of milk before dying, 1mb at a time. A villager (with more health) creates 60 mb of liquid over its life time, 6mb at a time. Liquid emerald is a much more valuable resource than milk.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Crafttweaker: 1.12-4.1.18
- ModTweaker: 4.0.17
- MTLib: 3.0.6
- Tinkers' Construct: 1.12.2-2.12.0.135

**Comment by jaredlll08** [comment]
```java
<liquid:milk> * amount
```

**Comment by kindlich** [comment]
Did you try `<liquid:milk> * 100`
?
Damn ninjaed

**Comment by TheDeviantCrafter** [comment]
I guess the documentation needs to be updated.

**Comment by jaredlll08** [comment]
I believe the docs are fine.
https://docs.blamejared.com/en/#Vanilla/Liquids/ILiquidStack#creating-an-iliquidstack
