### ISSUE TITLE
Thermal Expansion Compactor recipe isn't removed

### ISSUE THREAD

**Issue by GreatestFool** [jaredlll08/ModTweaker#727]
I’ve been trying to remove the compactor recipe for the thermal foundation coin(s). I’ve been able to disable the numismatic dynamo and remove all its recipes successfully. However when it comes to the compactor, all I’ve been able to do is remove and hide the numismatic press augment.

If I cheat in the augment, I can still make the coins and if I look up the compactor’s uses in JEI I can find the recipe for the coins.

[Here’s the script](https://ybin.me/p/e36923494dc3f213#TMLBj/kDnXq/xtFlDbwx2DPOFXcPvHpIwW1DH5j5cjg=), note that I’ve commented more or less all of it. I’ve been using the iron coin entry as the one to experiment with.

As you can see, I’ve tried using the `removePressRecipe,` `removeMintRecipe,` `removeStorageRecipe` and `removeGearRecipe` to no avail. All I get in return is `ERROR: No Compactor recipe exists for: 1xitem.thermalfoundation.coin@0`

You can see the error on [line 121 of the log](https://ybin.me/p/a217aec124ad680e#1gRcqYvg5Ovk/RXxXjY/03aAY470j3kN/lGtjdjn9SI=).

If I use 'mods.jei.JEI.removeAndHide` however, I get no error, [as you can see in the log.](https://ybin.me/p/4a78d1238f0e3228#ZQvh2W6e04YrV36vJAaB0Yuo55etUZnYqzyNN+vbA/4=)

Despite one log showing an error, and the other not doing so, both still do nothing. I can still craft the item, and still find them in JEI.

If it's needed, [here's the mod list.](https://ybin.me/p/34bd2a63d1451093#0IgpeqtKLR5ZBCbk5qPGI7TrpzTPDPEdiao/o9D2y/4=)

I don't know if it's a bug or not, and I don't know if it's proper conduct to ask here. I apologize if it is, but I thought it prudent to do so just in case. If I don't reply in a timely manner, it's probably because I'm not home. I'm going to be somewhat unavailable from tomorrow night to around midday sunday, I'm going on a trip and my phone is prone to having a shitty signal. I'll try to check regardless, but I might not be able to do much until Sunday if you require more information.

**Comment by kindlich** [comment]
`removeAndHide` is only for **crafting table** recipes, so of course it will not remove the recipe.

Try only using the minting remove operation, as I do not know whether the script continues after an error.

**Comment by GreatestFool** [comment]
@kindlich If you actually properly read my comment instead of looking at only one line of the script, you'd not only see that I mention having used all four documented recipe removals for the Compactors, but also that right underneath `removeAndHide` in the script, they're commented.

Right below the first log which uses the documented recipe removals [as documented here](https://crafttweaker.readthedocs.io/en/latest/#Mods/Modtweaker/ThermalExpansion/Compactor/), any of the four return the same error. I mention that while removeAndHide doesn't provide an error but also doesn't work, like expected, I only mention it for prosterities sake.

So yes, it's quite obvious that `removeAndHide` doesn't work, but that's not what is the problem either.

**Comment by GreatestFool** [comment]
Just in case it wasn't obvious, I've used the four documented recipe removals individually, but only commented them out should I need to experiment further.

**Comment by jaredlll08** [comment]
Thermal expansion uses remove by input, not remove by output, so removing the coin won't do anything, as *the recipe doesn't exist*.

**Comment by GreatestFool** [comment]
So I have to remove every single recipe using every single ore the coins are made of?
