### ISSUE TITLE
Support or No Support?

### ISSUE THREAD

**Issue by Boolyman** [jaredlll08/ModTweaker#732]
Can someone please give me a firm answer on whether or not Thermal Expansion Fluid Transposers do or do not have ModTweaker support as of 08/13/2019... there is an infuriating amount of incorrect information, old and incorrect script syntax examples... and just plain outdated information all over google when I try to find out why my scripts don't work.  I have been through  numerous forums, sites, wikis, Craftweaker, Modtweaker, and Gits for everyone involved, and I can not get results... even simply copy and pasting the example scripts.

**Comment by jaredlll08** [comment]
As said on the official wiki. Yes.
https://docs.blamejared.com/en/#Mods/Modtweaker/ThermalExpansion/Fluid_Transposer/

As said on the github. Yes.
https://github.com/jaredlll08/ModTweaker/blob/1.12/src/main/java/com/blamejared/compat/thermalexpansion/Transposer.java
