### ISSUE TITLE
I think this mod breaks exnihilocreatio but I need it for several mods.

### ISSUE THREAD

**Issue by Tankman222** [jaredlll08/ModTweaker#733]
#### Issue Description:
I added mods sky factory 4 and by doing this it prevented ore pieces from being crafted into ore chunks from exnihiloCreatio. simply put I need to know how to work this mod so I can fix the problem. If this is the wrong mod (and if craft tweaker is the reason) then I am sorry but I need this mod because the creator of sky orchard decided to not have any way to make ore saplings and this mod is required for it to function.

I have no idea how this mod works or how to edit it. there is nothing in the exnilihocreatio config folder.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:
- Forge:
- Crafttweaker: 
- ModTweaker:
- MTLib:

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
Don't change mods in a pack if you don't know what you're doing.
