### ISSUE TITLE
Magma Crucible Issues

### ISSUE THREAD

**Issue by Boolyman** [jaredlll08/ModTweaker#737]
How do you specify the amount of fluid that an item will generate in a custom Magma Crucible script?  Items are just coming up as producing 1mb

**Comment by Riernar** [comment]
Did you try specifying the amount in the [ILiquidStack](https://crafttweaker.readthedocs.io/en/latest/#Vanilla/Liquids/ILiquidStack/), e.g. `<liquid:water> * 50` to get 50 mB ?
