### ISSUE TITLE
[Bug] botania.Brew.addRecipe method not recognizing Botania brew name "warpWard"

### ISSUE THREAD

**Issue by m-bigaignon** [jaredlll08/ModTweaker#738]
#### Issue Description:
With Thaumcraft 6 installed alongside it, Botania provides a new brew with the "Warp Ward" effect. This brew is registered, according to the `/ct botbrews` command, under the name "warpWard".

Calling `mods.botania.Brew.removeRecipe("warpWard")` method works as expected, however attempting to add a recipe for this brew raises the following error :

`[INITIALIZATION][CLIENT][ERROR] Unknown brew name "warpWard" for Botania Brew recipe.`

#### What happens:

Calling `mods.botania.Brew.addRecipe(IIngredient[] input, String brewName);` with the "warpWard" value for brewName raises the aforementioned error.

#### What you expected to happen:

The `addRecipe()` method should correctly add a Botania brewing recipe for the "warpWard" brew.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
[Test Script](https://pastebin.com/cytbQdb5)

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
[Crafttweaker Log File](https://pastebin.com/kJXfN1mg)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Crafttweaker: 4.1.19
- ModTweaker: 4.0.17
- MTLib: 3.0.6
- Thaumcraft: 6.1.BETA26
- Botania: r1.10-362

#### Your most recent log file where the issue was present: 
[Crafttweaker Log File](https://pastebin.com/kJXfN1mg)

**Comment by jaredlll08** [comment]
Fairly sure you got an item name wrong, there I no minecraft reeds, there is sugarcane though, that may fix the issue.

**Comment by m-bigaignon** [comment]
Well.... the actual handler for sugarcane is in fact <minecraft:reeds>, because Vanilla is extremely consistent with its naming.

When I first came across the error, I also assumed that my script was incorrect. So I simply took the example provided in the CraftTweaker wiki, under the ModTweaker -> Botania -> Brew category : 
`mods.botania.Brew.addRecipe([<minecraft:nether_wart>, <minecraft:reeds>, <minecraft:redstone>], "speed");`

This one worked as intended. I then simply replaced "speed" with "warpWard" and the issue happened again.

Note : I updated my original post with the versions of Thaumcraft and Botania I used in testing. I'll try to test with previous versions of the mods as soon as I have some time.

**Comment by jaredlll08** [comment]
My only guess is that thaumcraft / botania is adding the recipe after the actions are applied, if it works for one thing, but not the other, that kinda makes it not a modtweaker issue, since our code works, it is other mods doing things at the wrong time.
