### ISSUE TITLE
Added Lexica Botanica crafting pages have empty crafting grid

### ISSUE THREAD

**Issue by nihiltres** [jaredlll08/ModTweaker#739]
#### Issue Description:

If using the method to add crafting pages to the Lexica Botanica (`mods.botania.Lexicon.addCraftingPage(String name, String entry, int page_number, String... recipeNames);`), the page is added as expected, but the crafting grid displayed in the Lexicon is empty except for the output slot. The crafting grid should display the input of the specified recipe.

#### Script used

As a simple example, using a vanilla recipe to avoid any secondary problems:

```
mods.botania.Lexicon.removePage("botania.entry.cacophonium", 1);
mods.botania.Lexicon.addCraftingPage(
	"Doot doot",
	"botania.entry.cacophonium",
	1,
	["minecraft:crafting_table"]
);
```
The methods work *largely* as expected, adding a page with a crafting grid, and there's nothing unusual in the CraftTweaker log, but the crafting grid displayed in the Lexicon is empty except for the output slot.

#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.5.2831
- CraftTweaker: 1.12-4.1.19
- ModTweaker: 4.0.17
- MTLib: 3.0.6

**Comment by jaredlll08** [comment]
This will be a Botania issue, we don't define the output item anywhere, so they are getting that, but apparently are having issues getting the actual recipe.
