### ISSUE TITLE
Remove recipes from thermal expansion

### ISSUE THREAD

**Issue by Wolf-TMB** [jaredlll08/ModTweaker#743]
Hello, please tell me how to remove all recipes from the machine thermal expansion, for example from the induction smelter. There are more than 400 recipes and I need to delete them all. Delete one by one is not an option. Prompt a way to delete everything at once. Thanks in advance.
Now I delete so: 
`mods.thermalexpansion.InductionSmelter.removeRecipe(<ore:sand>.firstItem, <ore:gearSiliconRubber>.firstItem);`

**Comment by jaredlll08** [comment]
There is no way to remove all the recipes at once
