### ISSUE TITLE
CraftTweaker recipes.removeAll(); also removes Arcane Workbench recipes

### ISSUE THREAD

**Issue by IchHabeHunger54** [jaredlll08/ModTweaker#747]
I'm making a modpack with all-new recipes, so I'm using recipes.removeAll(); to remove the existing recipes. Unfortunately, this also removes all Arcane Workbench recipes. This isn't that bad for me, because I'm also planning to make new Arcane Workbench recipes, but it might be annoying to other people.
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Crafttweaker: 1.12-4.1.19
- ModTweaker: 4.0.17
- MTLib: 3.0.6

**Comment by jaredlll08** [comment]
That is because thaumcraft stores their recipes in the recipe manager, nothing I can do about that.
