### ISSUE TITLE
Thaumcraft 6 ResearchKey's?

### ISSUE THREAD

**Issue by drago87** [jaredlll08/ModTweaker#748]
Is it possible to get all thaumcraft 6 ResearchKey's printed to the CraftTweaker log?
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12
- Crafttweaker: 4.1.20
- ModTweaker: 4.0.17
- MTLib: 3.0.6

**Comment by kindlich** [comment]
IT should be included in the `/ct thaumcraftDump` command
<https://docs.blamejared.com/1.12/en/#Mods/Modtweaker/Thaumcraft/Commands/#thaumcraftdump>

**Comment by drago87** [comment]
It is for Infusion and Crucible but not for ArcaneWorkbench

**Comment by kindlich** [comment]
Have you checked the commands provided by thaumcraft then?
`/thaumcraft research list` or something..?

**Comment by drago87** [comment]
That was what i was looking for
