### ISSUE TITLE
Thaumcraft 6 Crucible recipes problems

### ISSUE THREAD

**Issue by drago87** [jaredlll08/ModTweaker#749]
Trying to add and change some Thaumcraft Crucible recipes
If i remove the crucibleTest3 one the script loads without eny error in chat with it is the on in the logs
However with or without no recipe is changed
Arcane Workbench recipe changes work (disabled for debugging)

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/KEg5zhD8

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/aEKMd2Dg
stanhebben.zenscript.parser.TokenException: Invalid character at Thaum-Cru.zs:79 - ￿
Should be
stanhebben.zenscript.parser.TokenException: Invalid character at Thaum-Cru.zs:79 - xEF xBF xBF
with a black background in Notepad++
____
#### Affected Versions (Do not use "latest"):
Minecraft: 1.12
Crafttweaker: 4.1.20
ModTweaker: 4.0.17
MTLib: 3.0.6

#### Your most recent log file where the issue was present: 

https://gist.github.com/drago87/fa98f585cb5b2776b579f3afd033fe90

**Comment by jaredlll08** [comment]
You need to fix that error before we can provide actual help. (that error is probably the reason it isn't working)

**Comment by drago87** [comment]
I think i have narrowed it down to the removeRecipe

```
mods.thaumcraft.Crucible.removeRecipe(<thaumcraft:ingot>); Works
mods.thaumcraft.Crucible.removeRecipe("thaumiumingot"); Dont work

```

**Comment by kindlich** [comment]
if you want to remove by recipe name you need the full recipe name.
So something like
```
"thaumcraft:thaumiumingot"
```

**Comment by jaredlll08** [comment]
I believe Kindlich Answered this one
