### ISSUE TITLE
Immersive Tech

### ISSUE THREAD

**Issue by tgstyle** [jaredlll08/ModTweaker#750]
#### Issue Description:
Immersive Tech support was already provided in the new project release Immersive Technology. It was originally forked but has become it's own project. It was released as compatible with Immersive Tech as an upgrade path. The calls look almost identical to what was just put in to modtweaker. Is there any way to differentiate in modtweaker so it disables Immersive Tech support if Immersive Technology is running?

https://www.curseforge.com/minecraft/mc-mods/immersive-technology

**Comment by tgstyle** [comment]
https://gist.github.com/tgstyle/f7e829db9651ffabcb1dc63e6f01e83a

**Comment by jaredlll08** [comment]
That is just bound to cause nightmares honestly.

According to the curse page:
```
*** This is unofficially an update to Immersive Tech so if you use it they cannot run side by side. However, it will swap seamlessly with Immersive Tech. ***
```

If you have a different mod, it should probably use a different zenclass name.
so maybe `mods.immersivetechnology` instead of `mods.immersivetech`

like serious question, if immersive tech updated, what was your plan?

**Comment by tgstyle** [comment]
Thanks, i'll change the zenclass name. 

If Ferro ever chooses to revive the mod that is his problem to deal with since he abandoned it almost 2 years ago.
