### ISSUE TITLE
Thaumcraft: Salis Mundus Transform - FTB Barrier Block

### ISSUE THREAD

**Issue by MokahTGS** [jaredlll08/ModTweaker#751]
#### Issue Description:
I'm trying to make a custom Salis Mundus transform and it only seems to work in reverse of what I want.  I'm trying to allow the player to transform FTB Barrier Blocks into Weedwood blocks from the Betweenlands mod.  The script doesn't seem to work in that direction but works flawlessly in the reverse.

Here's the script that works:

> import mods.thaumcraft.SalisMundus;

> //mods.thaumcraft.SalisMundus.addSingleConversion(IBlock in, IItemStack out, @Optional String research);
> SalisMundus.addSingleConversion(<thebetweenlands:weedwood>, <ftbquests:barrier>);

Here's what it should be:

> import mods.thaumcraft.SalisMundus;

> //mods.thaumcraft.SalisMundus.addSingleConversion(IBlock in, IItemStack out, @Optional String research);
> SalisMundus.addSingleConversion(<ftbquests:barrier>, <thebetweenlands:weedwood>);

#### What happens:

Reversing the block names in the script stops the script from working.  There is no error however.

#### What you expected to happen:

The script should work with any block in any order.

#### Minetweaker.log file 

https://gist.github.com/MokahTGS/7df117a4cc6e431b687e7796830055e8

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2847
- Crafttweaker: CraftTweaker2-1.12-4.1.20
- ModTweaker: modtweaker-4.0.17
- MTLib: MTLib-3.0.6

#### Your most recent log file where the issue was present: 

https://gist.github.com/MokahTGS/7e8eb590ece170be31afcd3fc38fc0a1

**Comment by jaredlll08** [comment]
I'm going to say this is a limitation on the FTB Barrier blocks and how ThaumCraft does infusion.

If it is working in one case but not the other, chances are it has to do with the block you are transforming

**Comment by MokahTGS** [comment]
I put an issue on FTB quests to see if this can get fixed.

https://github.com/FTBTeam/FTB-Quests/issues/378

**Comment by MokahTGS** [comment]
After further testing, it's not the FTB block...I tried this with bedrock to dirt and it still doesn't work.  Something else is going on here.  I'm not sure this issue should be closed.

**Comment by jaredlll08** [comment]
maybe don't try and replace blocks that are unbreakable...

**Comment by MokahTGS** [comment]
But that's the whole point

**Comment by jaredlll08** [comment]
then what you want to do is a limitation on ThaumCraft and possibly minecraft itself.
nothing is broken.
everything is working as intended.
