### ISSUE TITLE
massive error while attempting to add new fuel to TConstruct

### ISSUE THREAD

**Issue by varappdev** [jaredlll08/ModTweaker#753]
#### Issue Description:
I attempted to use craftteaker to add blazing pyrotheum as fuel for smeltery in tconstruct, and I got this massive error
[crafttweaker.log](https://github.com/jaredlll08/ModTweaker/files/4356596/crafttweaker.log)

#### What happens:
I got a massive error

#### What you expected to happen:
Make blazing pyrotheum a fuel with a very high temperature (I attempted to use issue #439 as help)

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/tftws37w

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
It is way too large for pastebin free check the file I uploaded in issue description

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Crafttweaker: 2-1.12-4.1.20
- ModTweaker: 4.0.18
- MTLib: 3.0

#### Your most recent log file where the issue was present: 

[latest.log](https://github.com/jaredlll08/ModTweaker/files/4356615/latest.log)

**Comment by jaredlll08** [comment]
Use gist.github.com for large things.

Read the docs:
https://docs.blamejared.com/1.12/en/#Mods/Modtweaker/TConstruct/Fuel/
it is `Fuel` not `Smeltery`

**Comment by varappdev** [comment]
What about setting the temperature?

**Comment by jaredlll08** [comment]
/shrug
that is a question for the TIC devs, but last I checked it uses the liquids temperature in general, not settable via api
