### ISSUE TITLE
Some casting recipes don't work

### ISSUE THREAD

**Issue by hacatu** [jaredlll08/ModTweaker#755]
I have added several casting recipes, many of which work, but some of which do not.  It seems that the ones that do not work all have an input item whose meta value is meaningful.  For example, I want steel rods to be castable via the immersive engineering metal press rod mold, and I want diamond gear to be castable via iron gear.  These do not work, but for instance my custom recipes to create casts from dawnstone on obsidian parts or menril shards from menril in a shard cast do work.

#### What happens:
For eg the steel rod recipe, if I export molten steel via a drain or via integrated tunnels pipes, either way the smeltery visually pours steel for a flicker and then stops.  There is no steel visually in the table or in the table according to top.  The amount of steel in the smeltery is not decreased.  If I spam click the drain, I can get there to visually be a pool of steel in the table, although top reveals it is illusory.  In this case, the smeltery controller reports the amount needed for the recipe was drained, but a couple seconds later reverts to the undrained amount.

#### What you expected to happen:
I expect the recipe to craft.

#### Script
[armor.zs](https://pastebin.com/s99fvmGu)

#### Log file
There are no errors for the tconstruct files in the crafttweaker log, although interestingly it does not report adding casting recipes for the iron to diamond gear.

____
#### Affected Versions:
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Crafttweaker: 4.1.18
- ModTweaker: 4.0.17
- MTLib: 3.0.6

**Comment by jaredlll08** [comment]
Sounds like a tic issue. A general rule of thumb, unless there is an error, it usually means we passed everything to the mod just fine, and it is and issue with them
