### ISSUE TITLE
Unable to create recipe for casting in empty basin

### ISSUE THREAD

**Issue by MagnusWright** [jaredlll08/ModTweaker#757]
I'm trying to add casting basin recipes for blocks of gregtech metals, but I can't figure out how to specify an empty basin. I tried passing in `null`, `<minecraft:air>`, and `<minecraft:dirt> * 0` as the second parameter, but none of those work. What is the `IIngredient` for an empty basin?

**Comment by jaredlll08** [comment]
We have an issue template. Use it.
