### ISSUE TITLE
BWM Filtered Hopper not converting items for recipes added

### ISSUE THREAD

**Issue by MatokHunt** [jaredlll08/ModTweaker#760]
#### Issue Description:
I’ve created a simple script to add a couple new recipes to the Better With Mods Filtered Hopper. The new recipes show in JEI and appear correct there, however when I throw the items into the hopper they are collected, but not converted to the outputs they should be.

#### What happens:
After placing a BWM Filtered Hopper and putting my filter item into it (wood block in this case), I then throw either sand or grass into the Filtered Hopper. The Filtered Hopper collects the items that I throw in, but does not convert them. This is different behavior than some of the default recipes.

#### What you expected to happen:
I expected that when I threw in sand, it would get converted to 9 diamonds, and when I threw in grass it would get converted to 9 diamonds and a piece of flint.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

[test.zs](https://gist.github.com/MatokHunt/e2d07b850a12dbd813b402ec3aafa805)

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

[Log File](https://gist.github.com/MatokHunt/77a1a3f2a136d01f402e3a80d11b5b23)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Crafttweaker: 4.1.20
- ModTweaker: 4.0.18
- MTLib: 3.0.6
- Better With Mods: 2.3.23
- Better With Lib: 1.5

#### Your most recent log file where the issue was present: 

[Log File](https://gist.github.com/MatokHunt/152a00e31e3a7f09b5809a7a619d4556)

**Comment by democat3457** [comment]
Remove lines 5 and 6. These lines take precedent over your filter recipes. Filtered items indicate which items go straight into the hopper's inventory - thus, if you create recipes with those items as input, they would go straight into the inventory, bypassing the recipes.

**Comment by MatokHunt** [comment]
That would be it, was confusion on my part. Thought those lines were required to instruct what items are allowed to be used with the filter.

Thanks much for the help.
