### ISSUE TITLE
Blood Magic Blood Altar ignores NBT information so keeps filling already full <ceramics:clay_bucket>.

### ISSUE THREAD

**Issue by ubergarm** [jaredlll08/ModTweaker#763]
#### Issue Description:
Adding a recipe to Blood Magic Blood Altar to fill `<ceramics:clay_bucket>` with Life Essence fluid does not "respect" NBT tags so it keeps trying to fill already full buckets. The Ceramics mod buckets are the same item, just with different NBT tags to specify what they contain. Vanilla/forge buckets turn into a different item name after filling so don't exhibit this issue.

Would changing the Mod Tweaker function from `IItemStack input` to `IIngredient input` allow me to use conditionals as inputs? Or does Blood Magic just not support this and I should give up and move forget about ceramics buckets.. haha... ? Thanks!

#### What happens:
The script does indeed add the ability to fill Ceramics buckets just like regular buckets, but it will continue to fill a Ceramics bucket or fill Ceramics buckets already containing other fluids.

#### What you expected to happen:
I expect the Blood Altar to only try to fill *empty* Ceramics buckets that have no NBT tags. It should *not* try to fill <ceramics:clay_bucket> that has NBT tags. (The JEI looks correct in that the input bucket has no NBT information, and the output bucket does have NBT tags as expected).

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://gist.github.com/ubergarm/2fc55c89ca56a492461c16eb7e657122 (first file in the gist)

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/ubergarm/2fc55c89ca56a492461c16eb7e657122 (second file in the gist)

#### Affected Versions (Do *not* use "latest"):

- Minecraft:  1.12.2
- Forge: forge-14.23.5.2854
- Crafttweaker: CraftTweaker2-1.12-4.1.20.574.jar
- ModTweaker: modtweaker-4.0.18.jar
- MTLib: MTLib-3.0.6.jar

**Comment by jaredlll08** [comment]
We pass the nbt along to blood magic, so there is literally nothing more that can be done on our side, changing to IIngredient doesn't make their recipes call our conditional code.

**Comment by ubergarm** [comment]
Hey thanks for the quick response! I'll consider this a 4 hour tutorial in zen script, lmao! Cheers!
