### ISSUE TITLE
 [ Feature Request ] Fermentation Station / Industrial Foregoing

### ISSUE THREAD

**Issue by LnX-OrioN** [jaredlll08/ModTweaker#764]
Hi, Can you add compatibility with the fermentation station in industrial foregoing mod, i want add custom recipes for my modpack ( Ascensio on curseforge ).
Fermentation station fits perfectly to use with rustic and others alcool mods for brewing.
The rustic brewing barrels doesn't allow automations with pipes or floppers.

Thanks for consider my request 😉

Minecraft 1.12.2 
Forge 14.23.5.2847

**Comment by jaredlll08** [comment]
1.12 isn't supported anymore, so either ask the mod dev of that mod, or make an addon mod yourself.
