### ISSUE TITLE
Ticking block entity error with tinker's complement high oven, custom heat recipes. MC1.12.2

### ISSUE THREAD

**Issue by Squatlock** [jaredlll08/ModTweaker#767]
#### Issue Description:
When adding a custom heat recipe to the tinkers high oven the game crashes when trying to preform the recipe 

#### What happens:
The game crashes with the error code 
Error: java.lang.ArithmeticException: / by zero
Exit Code: -1

#### What you expected to happen:
Have the oven turn the water to steam

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://gist.github.com/Squatlock/f6ba4086f7d77fcfec72c64607c23d6f#file-steam-zs

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/Squatlock/7bfd4426f588317a7575e9cd3f8b13b9

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.12.2
- Forge: 14.23.5.2847
- Crafttweaker: 4.1.20
- ModTweaker: 4.0.18
- MTLib: 3.0.6

#### Your most recent log file where the issue was present: 

https://gist.github.com/Squatlock/e87d06cd87b44b5f7c8de1c4f86f0c62

**Comment by jaredlll08** [comment]
Your game log doesn't have a crash in it at all, what is the actual full crash log?

**Comment by Squatlock** [comment]
Here's a crash log 

https://gist.github.com/Squatlock/1efbbcc2d4ef8e82b986e02b96906f49

**Comment by jaredlll08** [comment]
Report to tcomplement, seems to be on their end
