### ISSUE TITLE
mods.tconstruct.Melting.addRecipe does not work

### ISSUE THREAD

**Issue by Michael-Hozza** [jaredlll08/ModTweaker#769]
#### Issue Description:
mods.tconstruct.Melting.addRecipe does not work. In log there is this thrown:
[tconstruct-API]: Registration of melting recipe for fluid.tconstruct.aluminum from tile.basic_block_core.ore_aluminum_gc has been cancelled by event

#### What happens:
When I try add Aluminum ore from Galacticraft to smeltery -> molten aluminum, script does nothing.

#### What you expected to happen:
I expect to add aluminum ore to smeltery recipes.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/xFKaYNXg

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/fqVbf89d
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Crafttweaker: 1.12-4.1.20.586
- ModTweaker: 4.0.18
- MTLib :3.0.6

#### Your most recent log file where the issue was present: 

https://gist.github.com/NymburkSRO/ef7a75f330dde7321b60087c42410c39

**Comment by jaredlll08** [comment]
```
[AVAILABLE][SERVER][INFO] Altering Melting Recipe(s) for <liquid:aluminum> * 288
```
The recipe appears to being added fine, at least on our side.

Try crafting the recipe? it may be an issue with it not showing in JEI.

If that doesn't work, I would say report to Tinkers Construct, but I doubt they could help since 1.12 is old at this point.

**Comment by Michael-Hozza** [comment]
Found the issue... It was the shadows of greg's integration with tinkers.
