### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by forresthopkinsa** [jaredlll08/ModTweaker#770]
Between the CurseForge page, the Github readme, and the CraftTweaker wiki, there are a number of things that are not at all clear to me:

- Does CraftTweaker require a separate ModTweaker jar to be installed for certain mod integrations to work?
- Does *this* ModTweaker project only work with MineTweaker, or is it made for CraftTweaker as well?
  - If the former, should I be looking for a different version of ModTweaker?
- Does this mod require MTLib to work?

It would help a lot to add just a little more documentation to the aforementioned pages.

**Comment by jaredlll08** [comment]
> Does CraftTweaker require a separate ModTweaker jar to be installed for certain mod integrations to work?

CraftTweaker doesn't provide mod support, modtweaker adds support for some mods, so if you want to tweak them, you need modtweaker (the list is on the docs)

> Does this ModTweaker project only work with MineTweaker, or is it made for CraftTweaker as well? 

Minetweaker is no longer updated, it works fine with CraftTweaker, which is an updated Minetweaker

> Does this mod require MTLib to work? 
Yes


I know the curse description needs updating, I just don't really have time to actually do it.

**Comment by forresthopkinsa** [comment]
Thanks.
