### ISSUE TITLE
TC6 Crucible Recipes add "recipes for Unknown Item"

### ISSUE THREAD

**Issue by DoomRater** [jaredlll08/ModTweaker#773]
#### Issue Description:
I am using registerRecipe to add Crucible recipes that I can then include in the book, however each and every attempt to add recipes results in a log entry stating "[AVAILABLE][CLIENT][INFO] Altering Crucible Recipe(s) for Unknown item", making it impossible to register the recipe with the Thaumonicon.  This also occurs when I remove a recipe from the Crucible.

#### What you expected to happen:
Recipes given an appropriate name that can be used in the Thaumonicon.

#### Scripts used:
https://pastebin.com/Yv4cgNtB

#### CraftTweaker.log file:
https://1drv.ms/t/s!AtxnGH_CK3O22kT9p7nUIQ0GmOkh?e=7luJTd (file is too big to pastebin)

____
#### Affected Versions

- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Thaumcraft: 1.12.2-6.1.BETA26
- Thaumic Augmentation: custom, based on 1.12.2-2.0.13
- Crafttweaker: 1.12-4.1.20.608
- ModTweaker: 4.0.18
- MTLib: 3.0.6

____
#### Additional Notes
/crafttweaker thaumcraftDump results in an IllegalArgumentException saying "stack cannot be null". Log snippet with trace: https://pastebin.com/Y5gNQnH1

**Comment by jaredlll08** [comment]
I'm confused, the log is telling you that it is altering (adding in this case) recipes. it says the item is unknown, but the recipe should still be added and given a name (the name is what you set, so like `wheat_to_flour`).

The actual recipe name is `thaumcraft:wheat_to_flour`

**Comment by DoomRater** [comment]
That should indeed be what's happening, but while I can see the recipe in JEI, attempting to reference any of the recipes in the Thaumonicon yields nothing.  I should point out that the recipe does indeed work in the Crucible as expected (I can only create the items when the Thaumonicon research is unlocked, and JEI reflects this)

To reference the recipes, I am using an unreleased Thaumcraft Research Patcher.  However, manually editing the JSON file inside Thaumcraft or Thaumic Augmentation does not work either.  I have verified that adding recipe references to the Research Patcher mod does work otherwise and can add other listed recipes to Thaumonicon pages.

**Comment by jaredlll08** [comment]
I'm not sure what the issue could be then, unfortunately 1.12 isn't really supported anymore, more focusing on porting to 1.16 now.

**Comment by DoomRater** [comment]
It turns out I did miss the part where you point out there is a "thaumcraft:" prefix attached to every recipe added in the name. Adding the prefix does indeed result in the recipe being displayed.
