### ISSUE TITLE
a method available but none matches the parameters 

### ISSUE THREAD

**Issue by Darktotaled** [jaredlll08/ModTweaker#774]
#### Issue Description:
Basically im trying to integrate ex nihilo gravel/sand/dust ores with tinkers construct, but not the base ones that comes with the mod but the ones generated by another one bites the dust. Pretty much all metals from Metallurgy 4 + osmium from Mekanism.

#### What happens:
Im getting errors saying im not using the correct way or correct parameters even though its the one here: http://minetweaker3.powerofbytes.com/wiki/ModTweaker:TConstruct_Support

#### What you expected to happen:
The ore blocks should be able to be melted on TC Smeltery

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue): this is a part of the script as the other 3 are basically a repetition with small changes

https://pastebin.com/3Ya64jKD

also, i commented the lines that arent working due to aobd(fluid.aobd.anymetalhere) for some reason the fluid appears in crafting recipes but it doesnt appear on NEI if you search for it

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

this log is just before i changed ExtraTiC:moltenAdamantine to Metallurgy:adamantine.molten. I didnt open minecraft again because i hardfroze and had to manually reboot. No alterations other than that

https://pastebin.com/BwvMYf8E

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.7.10
- Forge: 10.13.4.1614
- Crafttweaker: using minetweaker 3 3.0.1.0B for 1.7.10
- ModTweaker: MT2 0.9.6
- MTLib: not for 1.7.10

#### Your most recent log file where the issue was present: 

log file is above pastebin max size, so ill attach it here
[latest.log](https://github.com/jaredlll08/ModTweaker/files/5810620/latest.log)

also, this is what im using as parameter:
![tooltip](https://user-images.githubusercontent.com/15343248/104509759-e17fc780-55c8-11eb-9104-641c1b5e2320.jpeg)

looking at this in the aforementioned site
//Smeltery
//InputStack, OutputFluid, TemperatureAmount, BlockRender
mods.tconstruct.Smeltery.addMelting(<minecraft:porkchop>, <liquid:blood> * 200, 200, <TConstruct:MeatBlock>);

minecraft:porkchop appears in the area called Code Name, so I used that designation for the inputstack, outputfluid and blockrender

**Comment by jaredlll08** [comment]
1.7.10 is no longer supported.

You're also trying to pass items to a parameter that asks for a fluid.

**Comment by Darktotaled** [comment]
I see, thanks
