### ISSUE TITLE
Dev Builds don't exist anymore

### ISSUE THREAD

**Issue by Phlosioneer** [jaredlll08/ModTweaker#775]
#### Issue Description:
Hey, I was looking for a version of ModTweaker with the Mill Ticks feature. However, the jenkins link in the Readme is broken, ModTweaker doesn't seem to be on ci.blamejared.com anymore.

This issue is just checking if this was intentional, and if there's any plan to continue with dev builds.

**Comment by jaredlll08** [comment]
There are no dev builds. honestly don't remember there ever being dev builds

**Comment by democat3457** [comment]
also the mill ticks feature requires bwm to update anyway
