### ISSUE TITLE
Multiple Thermal Expansion Dynamos fail to register new fuels, with no errors

### ISSUE THREAD

**Issue by Pacca64** [jaredlll08/ModTweaker#776]
#### Issue Description:
The numismatic, steam, and enervation dynamos are supposed to be supported by modtweaker, but the ability to add fuels doesn't work. The routines will run successfully according to the log file, but no change occurs in game. I'm using redstone dust as an example for the steam and numismatic dynamos, and sticks for the enervation dynamo (the items I was intending to use got removed when I started narrowing down my mods to just modtweaker, the thermal series mods, and their dependencies). The dynamos won't accept redstone/sticks in the slot, but the log confirms that it should...

#### What happens:
The dynamo functions as if mod tweaker wasn't doing anything. Redstone/sticks are not accepted as a fuel source. No error appears in game or in crafttweaker.log

#### What you expected to happen:
The dynamos accept redstone/sticks as a fuel source.

#### Scripts used
[numismaticDynamo.zs](https://pastebin.com/zcHKkxxE)
[enervationDynamo.zs](https://pastebin.com/qwbrhKS9)
[steamDynamo.zs](https://pastebin.com/Uin30c2b)

#### Minetweaker.log file
[crafttweaker.log](https://pastebin.com/NgHsaZQ3)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Crafttweaker: 4.1.20.625
- ModTweaker: 4.0.18
- MTLib: 3.0.6
- Thermal Expansion: 5.5.7.1
- Thermal Foundation: 2.6.7.1
- CodeChickenLib: 3.2.3.358
- RedstoneFlux: 2.1.1.1
- COFHCore: 4.6.6.1

#### Your most recent log file where the issue was present: 
[latest.log](https://pastebin.com/05ymxY45)
If you need/want debug.log, I can send one separately. pastebin wouldn't accept it.

The mod pack I'm trying to build with this means a lot to me. I'm willing to do whatever it takes to get this fixed. Thermal Expansion is my primary tech mod, and I have a lot of potential fuel items that I plan to add to these dynamos.

**Comment by Pacca64** [comment]
After further testing, _none_ of the thermal expansion dynamos work! All 6 of them share the same behavior; crafttweaker says that everything worked successfully, but there is no effect in game.

scripts
[reactantDynamo.zs](https://pastebin.com/Ub3C5pXj)
[magmaticDynamo.zs](https://pastebin.com/fkWBUB8m)
[compressionDynamo.zs](https://pastebin.com/nSy09Q3q)

logs
[crafttweaker.log](https://pastebin.com/7qpP8rY7)
[latest.log](https://pastebin.com/cSzVZ40y)

This is a major broken feature! I'd be pretty upset if there was no way to fix this, I use the dynamos regularly, and plan to add a lot of fuels to them...

**Comment by jaredlll08** [comment]
Yea so unfortunately I can't even set up a modtweaker 1.12 workspace anymore, so I doubt this will be getting a fix unless someone else who has a working workspace can fix it.

**Comment by Pacca64** [comment]
What exactly is required in setting one up? I have an older 1.12 mod setup that I can still edit in eclipse and build, but I haven't tried working with mod apis' yet

**Comment by jaredlll08** [comment]
I more so mean, it has so many dependencies and half the mavens don't work anymore that it is impossible to actually get it running, having a 1.12 workspace for another mod won't help much unless you have the deps.

In this case I can't load the game because of blood magic and guide api.

**Comment by Pacca64** [comment]
Ah, I see, that's quite the mess. I guess I'll have to look into making a more direct approach by making my own mod. Thank you for going into the effort to make this mod, every other integration I've tried thus far has worked wonders.

**Comment by jaredlll08** [comment]
Ah this is fun, I got the workspace working by mangling it...


Anyway... Thermal Expansion has limits on the amount of energy a dynamo can create, both a minimum and a maximum.

```
Compression:
energy < 10000 || energy > 200000000

Enervation:
energy < 2000 || energy > 200000000

Magmatic:
energy < 10000 || energy > 200000000

Numistic:
energy < 2000 || energy > 200000000

Reactant:
energy < 10000 || energy > 200000000

Steam:
energy < 2000 || energy > 200000000
```

So if you make the energy be between those mins and maxes it should work just fine.

I can confirm using 
```zenscript
mods.thermalexpansion.NumisticDynamo.addFuel(<minecraft:redstone>, 10000);
```
works fine.

**Comment by Pacca64** [comment]
Ah. Perhaps the crafttweaker 2 documentation site needs updating, it tricked me into thinking that you were supposed to input small numbers: [Numismatic Dynamo Documentation](https://docs.blamejared.com/1.12/en/Mods/Modtweaker/ThermalExpansion/Dynamos/NumisticDynamo/)

I assumed the value would be multiplied by 1000...

**Comment by jaredlll08** [comment]
Yep, the docs are a bit misleading in this case.

If you make an issue here:
https://github.com/CraftTweaker/CraftTweaker-Documentation/issues
I'll update them when I get a chance.
