### ISSUE TITLE
Unable to add Melting/Alloying/Casting Recipe to Tcon Smeltery

### ISSUE THREAD

**Issue by coffinbag** [jaredlll08/ModTweaker#783]
Issue Description:
When I load minecraft the script does not load, and instead throws an error in the crafttweaker log. I copied the lines off of the crafttweaker documentation site. This does not cause my game to crash, the specific script just fails to load. I have tried the script with out using a defined value and just the straight ILiquidStack <liquid:coal>, but it still fails.

What happens:
the script in question fails to load on startup.

What you expected to happen:
The script to load and add the ability to melt coal and alloy steel in the smeltery.

Script: https://pastebin.com/ndLsmRAQ

Minetweaker.log file: https://paste.ee/p/5O2g4
(I use MultiMC and it uses Paste.ee)

____
Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.5.2855
- Crafttweaker: 1.12-4.1.20.670
- ModTweaker: 4.0.20.5
- MTLib: 3.0.7

**Comment by jaredlll08** [comment]
Line 9
```zenscript 
mods.tconstruct.Casting.addBasinRecipe(<bigreactors:blockgraphite>,<minecraft:air>,lcoal,1,296)
```

There isn't a method that accepts 2 ints at the end.

Not sure what you're trying to do, but take a look at the docs
https://docs.blamejared.com/1.12/en/Mods/Modtweaker/TConstruct/Casting#add-casting-recipes
