### ISSUE TITLE
Thaumcraft 6 Thaumonomicon do not reflect current recipe

### ISSUE THREAD

**Issue by Shazuli** [jaredlll08/ModTweaker#784]
#### Issue Description:
When you change a recipe in Thaumcraft the Thaumonomicon does not reflect the change. And if you remove the old recipe the recipe disappears from the book.

### Before
![2022-01-19_09 39 12](https://user-images.githubusercontent.com/9884180/150095695-4d5c8105-a0d7-48d1-ae51-b2f5a0b044b3.png)

![2022-01-19_09 38 56](https://user-images.githubusercontent.com/9884180/150095753-dbe12f0c-5253-4674-b33b-197dcadf38d8.png)

### After
![2022-01-19_09 55 40](https://user-images.githubusercontent.com/9884180/150097126-8e3a9b21-8d06-4075-b7ee-e63f3910b2d0.png)

*Recipe for the Thaumometer is not there anymore*
![2022-01-19_09 53 52](https://user-images.githubusercontent.com/9884180/150096715-64d795fe-d52e-4a77-8686-319994897104.png)

#### What you expected to happen:
The recipe change reflected as seen in JEI. Perhaps a function to override rather than remove and replace a recipe, or maybe a function to update the recipe visible in the book.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/SsBwSCna

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2860
- Crafttweaker: 1.12-4.1.20.673
- ModTweaker: 4.0.20.4
- MTLib: 3.0.7

**Comment by kindlich** [comment]
That would only work, if the recipe name stayed the same.
But since you created a new recipe, it would create the recipe in the CrT namespace.

In older versions (1.7) you were able to modify thaumonomicon entries.
I don't know how Thaumonomicon entries are handled in 1.12, you could see if you can change the recipe id via a resource pack or something?

**Comment by jaredlll08** [comment]
1.12 has no thaumonomicon support, you will need to use a different mod for that, which I believe does exist.

Also recipes are registered under the "thaumcraft" namespace, so if you do it with the same name, it should show the new recipe.

**Comment by Shazuli** [comment]
@jaredlll08 I've been looking a bit in the wiki, but I can't find any mentions of registering a recipe in a different namespace. I also tried searching "Thaumcraft 6 recipe changer" into Google and did not get any matches. You think you could explain how to register a recipe in a different namespace?

**Comment by jaredlll08** [comment]
> You think you could explain how to register a recipe in a different namespace?

You don't.

We hardcoded it to the "thaumcraft" namespace.

It was an oversight at the time, and can't really be fixed now.

**Comment by Vapaman** [comment]
https://www.curseforge.com/minecraft/mc-mods/thaumcraft-research-patcher
