### ISSUE TITLE
[request] thaumic addition handling

### ISSUE THREAD

**Issue by Biviho** [jaredlll08/ModTweaker#785]
hi, i don't know if you accept suggestion/requests, but if so, it would be great if it's possible to add creafttweaker compatibility with some thaumic addition reconstructed machine/feature:

-Flux Concentrator: transformation from block to block and if possible, setting the cost

-vis salt potion effect: addition of a potion effect to vis salt that don't have one

**Comment by jaredlll08** [comment]
The mod is no longer receiving feature requests, especially for 1.12.
