### ISSUE TITLE
[Feature Suggestions] More Thaumcraft 6 support

### ISSUE THREAD

**Issue by Vapaman** [jaredlll08/ModTweaker#787]
Here are some miscellaneous suggestions for Thaumcraft 6. While TC6 is not updated anymore, there is an active community around it and it is still used widely in modpacks.

**Pech trading**
Pech trading does not use loot tables and seems to be hardcoded, it would be nice if the trades and accepted items could be edited. This one shouldn't be too hard to implement.

**Theorycrafting minigame**
I've suggested this here: https://github.com/TheCodex6824/ThaumcraftResearchPatcher/issues/15, but as the suggestion may be out of the reach of that project, it may better fit here.

**Golem crafting**
Golem crafting seems to be hardcoded. Could be very hard to implement a proper way to edit the materials and aspects used in it.

**Flux rift drops**
Editing the items that flux rift drops would be useful. Maybe this could extend to adding custom rift events (eg. spawning taint seeds, wisps, etc.). Could be hard to implement.

**Comment by jaredlll08** [comment]
ModTweaker 1.12 will not be receiving any more feature updates.
