### ISSUE TITLE
[ERROR] No InductionSmelter recipe exists for:

### ISSUE THREAD

**Issue by 57331Fury** [jaredlll08/ModTweaker#789]
#### Issue Description:
I am trying to fix the issue with recipes and machines outputting the wrong ingot when it comes to things like Tungsten and Titanium, and am slowly losing the will to live. The problem is with Thermal Expansion stating that the recipe I am trying to remove from the machines, does not exist, despite it clearly showing in JEI. I started off changing Tungsten, and on the whole, the changes worked, despite throwing out lots of errors telling me the recipes didn`t exist. However since changing Titanium, it now throws out lots more errors, and doesn`t change all recipes. It also seems to be completely random as to which recipes it removes, and which it says doesn`t exist. For example: 
Pulverizer.removeRecipe(<jaopca:item_clustertitanium>);  Works just fine, but the very next line:
Pulverizer.removeRecipe(<jaopca:item_hunktitanium>);  throws out an error telling me the recpie doesn`t exist
Both items are from the same mod meaning it has nothing to do with the order the recipes are registered in. Also I noticed that when I changed the vanilla furnace recipe for the Tungsten ingots, the Redstone Furnace automatically updated to show the correct output, but when doing the same with Titanium, initally the Redstone furnace showed the new output, but then when making changes to the Pulverizer recipes, the Redstone furnace is now showing the wrong ingot again, even though the vanilla furnace shows correctly. I have heard that TE automatically deals with oredicting, and thought this was the cause, but that would make no sense why <cyclicmagic:tungsten_nether_ore> is removed no problems, but <cyclicmagic:tungsten_end_ore> has errors and is not removed, since they are both oredicted as oreTungsten, and why <cyclicmagic:titanium_nether_ore> and <cyclicmagic:titanium_end_ore> both don`t work.

#### What happens:
Some recipes are removed, allowing me to write a new machine recipe, while others throw up errors and are not removed.

#### What you expected to happen:
For recipes that show in JEI to be removed when using the exact syntax stated in the wki.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/akq9Ebug

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/Ezp5n8Lw

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2859
- Crafttweaker: 4.1.20.674
- ModTweaker: 4.0.20.5
- MTLib: 3.0.6

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
Unfortunately I don't have a good answer for you.

We check to see if a recipe exists before trying to remove it, there is no bug with this code, it is dead simple:
https://github.com/jaredlll08/ModTweaker/blob/1.12/src/main/java/com/blamejared/compat/thermalexpansion/InductionSmelter.java#L69-L72

chances are, the mod that adds the recipes you are trying to remove is running after our scripts are applied, so you can't remove those recipes.

It is that, or you are not removing by the correct input (it could want a tag and not the item you are giving it), also try without specifying the sand.

**Comment by 57331Fury** [comment]
I have had previous issues with the recipe register order, for example unidict adding plate recipes etc after CT has done it's thing, but that doesn't appear to be the case as it just doesn`t make sense that one JAOPCA item is removed, and the very next line which tries to remove a second JAOPCA item fails, or why the cyclic nether tungsten ore works, but the cyclic end tungsten ore doesn't work. And as the script shows, the syntax on those lines is identical.

**Comment by jaredlll08** [comment]
Yea I'm not sure what to tell you, the recipe you are trying to remove simply doesn't exist with those items, I don't know any of those mods well enough to tell you what it should be unfortunately

**Comment by 57331Fury** [comment]
No problems, thanks for trying. I still think it may be something to do with how TE is oredicting stuff. I might try removing all oredicting of Galacticraft tungsten and titanium, and just writing the machine recipes for those items myself. This should hopefully 'fix' the problem.

**Comment by 57331Fury** [comment]
Yeah, thats fully resolved the problem. I didn't even have to rewrite the un-dicted Galacticraft ores/ingots/blocks recipes at all. And thankfully all the existing recipes which use GC ingots don't use oredicting, so I haven't messed up any other recipes.
